force-app/main/default/objects/Case/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Complemento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/BairroRepresentante__c.field-meta.xml
<CustomField>
    <fullName>BairroRepresentante__c</fullName>
    <label>Bairro Representante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CEPRepresentante__c.field-meta.xml
<CustomField>
    <fullName>CEPRepresentante__c</fullName>
    <label>CEP Representante</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CertidaoNegativaCivel__c.field-meta.xml
<CustomField>
    <fullName>CertidaoNegativaCivel__c</fullName>
    <label>Certidão Negativa Cível</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CertidaoNegativaCriminal__c.field-meta.xml
<CustomField>
    <fullName>CertidaoNegativaCriminal__c</fullName>
    <label>Certidão Negativa Criminal</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CertidaoNegativaFederal__c.field-meta.xml
<CustomField>
    <fullName>CertidaoNegativaFederal__c</fullName>
    <label>Certidão Negativa Federal</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CertidaoNegativaTrabalhista__c.field-meta.xml
<CustomField>
    <fullName>CertidaoNegativaTrabalhista__c</fullName>
    <label>Certidão Negativa Trabalhista</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CidadeRepresentante__c.field-meta.xml
<CustomField>
    <fullName>CidadeRepresentante__c</fullName>
    <label>Cidade Representante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ComplementoRepresentante__c.field-meta.xml
<CustomField>
    <fullName>ComplementoRepresentante__c</fullName>
    <label>Complemento Representante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContaCorrente__c.field-meta.xml
<CustomField>
    <fullName>ContaCorrente__c</fullName>
    <label>Conta Corrente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContratoSocialUltimaAlteracao__c.field-meta.xml
<CustomField>
    <fullName>ContratoSocialUltimaAlteracao__c</fullName>
    <label>Contrato Social e Última Alteração</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CPFRepresentante__c.field-meta.xml
<CustomField>
    <fullName>CPFRepresentante__c</fullName>
    <label>CPF Representante</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DesejaSeTornarConsultor__c.field-meta.xml
<CustomField>
    <fullName>DesejaSeTornarConsultor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deseja se tornar consultor ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/DocPessoais_Socios_Representantes__c.field-meta.xml
<CustomField>
    <fullName>DocPessoais_Socios_Representantes__c</fullName>
    <label>Doc Pessoais Socios/Representantes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/EmailConsultorWeb__c.field-meta.xml
<CustomField>
    <fullName>EmailConsultorWeb__c</fullName>
    <label>Email do Consultor</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/EmailIntegradorWeb__c.field-meta.xml
<CustomField>
    <fullName>EmailIntegradorWeb__c</fullName>
    <label>Email do Integrador</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/EmailRepresentante__c.field-meta.xml
<CustomField>
    <fullName>EmailRepresentante__c</fullName>
    <label>Email Representante</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <inlineHelpText>Endereço do cliente</inlineHelpText>
    <label>Endereço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/EnderecoRepresentante__c.field-meta.xml
<CustomField>
    <fullName>EnderecoRepresentante__c</fullName>
    <label>Endereço Representante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/EstadoRepresentante__c.field-meta.xml
<CustomField>
    <fullName>EstadoRepresentante__c</fullName>
    <label>Estado Representante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FotosInstalacoes__c.field-meta.xml
<CustomField>
    <fullName>FotosInstalacoes__c</fullName>
    <label>Fotos de Instalações</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NomeConsultorWeb__c.field-meta.xml
<CustomField>
    <fullName>NomeConsultorWeb__c</fullName>
    <label>Nome do Consultor</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/NomeFantasia__c.field-meta.xml
<CustomField>
    <fullName>NomeFantasia__c</fullName>
    <inlineHelpText>Nome fantasia do cliente</inlineHelpText>
    <label>Nome Fantasia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NomeIntegradorWeb__c.field-meta.xml
<CustomField>
    <fullName>NomeIntegradorWeb__c</fullName>
    <label>Nome do Integrador</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/NomeRepresentante__c.field-meta.xml
<CustomField>
    <fullName>NomeRepresentante__c</fullName>
    <inlineHelpText>Nome do representante do cliente</inlineHelpText>
    <label>Nome Representante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PaisIntegrador__c.field-meta.xml
<CustomField>
    <fullName>PaisIntegrador__c</fullName>
    <label>Pais Integrador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brasil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PortfolioEmpresa__c.field-meta.xml
<CustomField>
    <fullName>PortfolioEmpresa__c</fullName>
    <label>Portfólio da Empresa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RazaoSocial__c.field-meta.xml
<CustomField>
    <fullName>RazaoSocial__c</fullName>
    <inlineHelpText>Razão social do cliente</inlineHelpText>
    <label>Razao Social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TelefoneRepresentante__c.field-meta.xml
<CustomField>
    <fullName>TelefoneRepresentante__c</fullName>
    <label>Telefone Representante</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/modules/communities/CommunityFormController.cls
// Apex Class: CommunityFormController (Updated)
public without sharing class CommunityFormController {
    @AuraEnabled
    public static Id createCase(String payload) {
        Map<String, Object> formData = (Map<String, Object>) JSON.deserializeUntyped(payload);
        System.debug('Payload: ' + payload);
        System.debug('Form Data: ' + formData);

        Id queueId = getQueueIdByName('Qualificação de Integradores');

        // Create a Contact record with Integrador information
        Contact integradorContact = new Contact();
        integradorContact.LastName = (String) formData.get('nomeRepresentante');
        integradorContact.Email = (String) formData.get('email');
        integradorContact.Phone = (String) formData.get('telefone');
        integradorContact.MailingState = (String) formData.get('estado');
        integradorContact.MailingCity = (String) formData.get('cidade');
        integradorContact.MailingStreet = (String) formData.get('endereco');
        integradorContact.MailingPostalCode = (String) formData.get('cep');
        integradorContact.MailingCountry = 'Brasil';

        insert integradorContact;

        // Define all fields and ensure they are present in formData
        Case caseRecord = new Case();
        caseRecord.Description = (String) formData.get('mensagem');
        caseRecord.Subject = 'Integrador - ' + (String) formData.get('razaoSocial');
        caseRecord.Status = 'Novo';
        caseRecord.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Qualificação de Integradores').getRecordTypeId();
        caseRecord.OwnerId = queueId == null ? UserInfo.getUserId() : queueId;
        // Map fields to Case object
        caseRecord.NomeIntegradorWeb__c = (String) formData.get('nomeFantasia');
        caseRecord.EmailIntegradorWeb__c = (String) formData.get('email');
        caseRecord.SuppliedPhone = (String) formData.get('telefone');
        caseRecord.Estado__c = (String) formData.get('estado');
        caseRecord.Cidade__c = (String) formData.get('cidade');
        caseRecord.NomeConsultorWeb__c = (String) formData.get('nomeConsultor');
        caseRecord.EmailConsultorWeb__c = (String) formData.get('emailConsultor');
        caseRecord.DesejaSeTornarConsultor__c = formData.get('beConsultant') == 'true' ? true : false;
        caseRecord.EmailConsultorWeb__c = (String)  formData.get('emailConsult');
        caseRecord.DesejaSeTornarConsultor__c = formData.get('tornarConsultor') == 'true' ? true : false;
        caseRecord.PaisIntegrador__c = 'Brasil';
        
        // Additional fields from formData
        caseRecord.CNPJ__c = (String) formData.get('cnpj');
        caseRecord.RazaoSocial__c = (String) formData.get('razaoSocial');
        caseRecord.NomeFantasia__c = (String) formData.get('nomeFantasia');
        caseRecord.Endereco__c = (String) formData.get('endereco');
        caseRecord.Bairro__c = (String) formData.get('bairro');
        caseRecord.CEP__c = (String) formData.get('cep');
        caseRecord.Contactid = integradorContact.Id;

        // Representante Legal fields
        caseRecord.NomeRepresentante__c = (String) formData.get('nomeRepresentante');
        caseRecord.EnderecoRepresentante__c = (String) formData.get('enderecoRepresentante');
        caseRecord.BairroRepresentante__c = (String) formData.get('bairroRepresentante');
        caseRecord.CidadeRepresentante__c = (String) formData.get('cidadeRepresentante');
        caseRecord.ComplementoRepresentante__c = (String) formData.get('complementoRepresentante');
        caseRecord.EstadoRepresentante__c = (String) formData.get('estadoRepresentante');
        caseRecord.CEPRepresentante__c = (String) formData.get('cepRepresentante');
        caseRecord.TelefoneRepresentante__c = (String) formData.get('telefoneRepresentante');
        caseRecord.EmailRepresentante__c = (String) formData.get('emailRepresentante');
        caseRecord.CPFRepresentante__c = (String) formData.get('cpfRepresentante');

        // Dados Bancários fields
        caseRecord.Banco__c = (String) formData.get('banco');
        caseRecord.Agencia__c = (String) formData.get('agencia');
        caseRecord.ContaCorrente__c = (String) formData.get('contaCorrente');
        
        caseRecord.CertidaoNegativaTrabalhista__c = (String) formData.get('certidaoTrabalhista');
        caseRecord.CertidaoNegativaCivel__c = (String) formData.get('certidaoCivel');
        caseRecord.CertidaoNegativaCriminal__c = (String) formData.get('certidaoCriminal');
        caseRecord.CertidaoNegativaFederal__c = (String) formData.get('certidaoFederal');
        caseRecord.ContratoSocialUltimaAlteracao__c = (String) formData.get('contratoSocial');
        caseRecord.DocPessoais_Socios_Representantes__c = (String) formData.get('docPessoais');
        caseRecord.PortfolioEmpresa__c = (String) formData.get('portfolioEmpresa');
        caseRecord.FotosInstalacoes__c = (String) formData.get('fotosInstalacoes');
        
        insert caseRecord;
        return caseRecord.Id;
    }

    @AuraEnabled
    public static Id saveFile(Map<String, Object> fileDataMap, Id caseId) {
        FileInfo fileData = new FileInfo();
        fileData.Title = (String) fileDataMap.get('name');
        fileData.VersionData = (String) fileDataMap.get('content');
        System.debug('File Data: ' + JSON.serialize(fileData));

        ContentVersion objCntVersion = new ContentVersion();
        objCntVersion.PathOnClient = fileData.Title;
        objCntVersion.Title = fileData.Title;
        objCntVersion.VersionData = EncodingUtil.base64Decode(fileData.VersionData); // Convert to Blob
        insert objCntVersion;

        return objCntVersion.Id;
    }

    @AuraEnabled
    public static void createContentVersion(List<Id> contentVersionId, Id linkedEntityId) {
        createContentVersionAsync(contentVersionId, linkedEntityId);
    }

    @future
    private static void createContentVersionAsync(List<Id> contentVersionId, Id linkedEntityId) {
        for (Id versionId : contentVersionId) {
            ContentVersion version = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :versionId LIMIT 1];
            if (version != null) {
                ContentDocumentLink link = new ContentDocumentLink();
                link.ContentDocumentId = version.ContentDocumentId;
                link.LinkedEntityId = linkedEntityId;
                link.Visibility = 'AllUsers';
                link.ShareType = 'V';
                insert link;
            } else {
                System.debug('ContentVersion not found for ID: ' + versionId);
            }
        }
    }

    public class FileInfo {
        public String Title;
        public String VersionData;
    }

    public static Id getQueueIdByName(String queueName) {
        Group queue = [SELECT Id FROM Group WHERE Name = :queueName AND Type = 'Queue' LIMIT 1];
        return queue != null ? queue.Id : null;
    }

}