force-app/main/default/objects/ProposalCover__c/ProposalCover__c.object-meta.xml
<CustomObject>
    <label>Capa de Proposta</label>
    <nameField>
        <label>Nome de Capa de Proposta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capa de Propostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProposalCover__c/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <label>Grupo Tarifario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Padrão ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProposalCoverBO.cls
public with sharing class ProposalCoverBO {
  public static void updateDefaultStatus(
    List<ProposalCover__c> proposalCovers
  ) {
    Map<String, Boolean> isDefaultSetByGroup = new Map<String, Boolean>();

    // Identificar se uma capa padrão foi definida para cada grupo tarifário
    for (ProposalCover__c cover : proposalCovers) {
      if (cover.IsDefault__c == true) {
        isDefaultSetByGroup.put(cover.GrupoTarifario__c, true);
      }
    }

    // Se uma capa padrão foi definida, atualizar as demais para cada grupo tarifário
    if (!isDefaultSetByGroup.isEmpty()) {
      List<ProposalCover__c> otherDefaults = [
        SELECT Id, GrupoTarifario__c
        FROM ProposalCover__c
        WHERE IsDefault__c = TRUE AND Id NOT IN :proposalCovers
      ];
      for (ProposalCover__c otherCover : otherDefaults) {
        if (isDefaultSetByGroup.containsKey(otherCover.GrupoTarifario__c)) {
          otherCover.IsDefault__c = false;
        }
      }
      update otherDefaults;
    }
  }
}