force-app/main/default/objects/ProposalCover__c/ProposalCover__c.object-meta.xml
<CustomObject>
    <label>Capa de Proposta</label>
    <nameField>
        <label>Nome de Capa de Proposta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capa de Propostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProposalCover__c/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <label>Grupo Tarifario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Padrão ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ModeloPropostaA</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaB</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaBowe</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaEzeeConnect</fullName>
            </value>
            <value>
                <fullName>WorkDeliveryReportPdf</fullName>
                <isActive>false</isActive>
                <label>WorkDeliveryReportPdf</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProposalCoverTriggerTest.cls
/**
 * @description       : 
 * @author            : Daniel Belini
 * @group             : 
 * @last modified on  : 11-16-2025
 * @last modified by  : Daniel Belini
**/
@isTest
private class ProposalCoverTriggerTest{

    // Método para criar dados de teste
    private static ProposalCover__c createTestProposalCover(String grupoTarifario, Boolean isDefault) {
        ProposalCover__c cover = new ProposalCover__c();
        cover.GrupoTarifario__c = grupoTarifario;
        cover.IsDefault__c = isDefault;
        cover.IsActive__c = true;
        cover.Template__c ='ModeloPropostaB';
        

        return cover;
    }

    // Teste para o cenário de inserção
    @isTest 
    static void testProposalCoverInsert() {
        // Prepare dados de teste
        ProposalCover__c cover1 = createTestProposalCover('Grupo A', true);
        insert cover1;

        ProposalCover__c cover2 = createTestProposalCover('Grupo A', false);
        ProposalCover__c cover3 = createTestProposalCover('Grupo A', true);

        // Inicie um contexto de teste
        Test.startTest();

        // Insira os dados de teste
        insert new List<ProposalCover__c>{cover2, cover3};

        // Encerre o contexto de teste
        Test.stopTest();

        // Faça as verificações
        List<ProposalCover__c> insertedCovers = [SELECT Id, IsDefault__c FROM ProposalCover__c WHERE Id IN :new List<Id>{cover1.Id, cover3.Id}];
        //System.assertEquals(false, insertedCovers[0].IsDefault__c);
        //System.assertEquals(true, insertedCovers[1].IsDefault__c);
    }

    // Teste para o cenário de atualização
    @isTest 
    static void testProposalCoverUpdate() {
        // Prepare e insira dados de teste
        ProposalCover__c cover1 = createTestProposalCover('Grupo A', true);
        insert cover1;
        ProposalCover__c cover2 = createTestProposalCover('Grupo A', false);
        insert cover2;
        ProposalCover__c cover3 = createTestProposalCover('Grupo A', true);
        insert cover3;

        // Atualize um registro para ser padrão
        cover2.IsDefault__c = true;
        
        // Inicie um contexto de teste
        Test.startTest();

        // Atualize os dados de teste
        update cover2;

        // Encerre o contexto de teste
        Test.stopTest();

        // Faça as verificações
        List<ProposalCover__c> updatedCovers = [SELECT Id, IsDefault__c FROM ProposalCover__c WHERE Id IN :new List<Id>{cover1.Id, cover2.Id}];
        //System.assertEquals(false, updatedCovers[0].IsDefault__c);
        //System.assertEquals(true, updatedCovers[1].IsDefault__c);
    }
}