force-app/main/default/objects/ClickSign__c/ClickSign__c.object-meta.xml
<CustomObject>
    <label>ClickSign</label>
    <nameField>
        <displayFormat>DS-{000000000}</displayFormat>
        <label>ClickSign</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClickSign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSign__c/fields/CurrentStep__c.field-meta.xml
<CustomField>
    <fullName>CurrentStep__c</fullName>
    <label>Current Step</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>Recipients</fullName>
            </value>
            <value>
                <fullName>Prepare &amp; Send</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Document Send to Assign</fullName>
            </value>
            <value>
                <fullName>Document Assign</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSignLog__c/ClickSignLog__c.object-meta.xml
<CustomObject>
    <label>ClickSignLog</label>
    <nameField>
        <label>Nome de ClickSign Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClickSignLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSignLog__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Classe do APEX</description>
    <label>Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClickSignLog__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <description>Callout - Corpo da Response</description>
    <label>Response Body</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClickSignLog__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>Callout - Código do Status</description>
    <label>Status Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integrador__mdt/Integrador__mdt.object-meta.xml
<CustomObject>
    <description>Metadado para armazenar informações de Endpoints, login, senha</description>
    <label>Integração</label>
    <pluralLabel>Integradores</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integrador__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/modules/click-sign/test/ClickSignUtilsTest.cls
@IsTest
public with sharing class ClickSignUtilsTest {
    
    @IsTest
    static void testGetIntegration() {
        // Arrange
        String name = 'CREATE_ENVELOPE';

        // Act
        Integrador__mdt result = ClickSignUtils.getIntegration(name);

        // Assert
    }

    @IsTest
    static void testCreateLogWithException() {
        // Arrange
        String className = 'TestClass';
        String methodName = 'testMethod';
        Exception source = new DmlException('Test exception');

        // Act
        ClickSignLog__c log = ClickSignUtils.createLog(className, methodName, source);

        // Assert
        System.assertNotEquals(null, log);
        System.assertEquals(className, log.Class__c);
        System.assertEquals(methodName, log.Method__c);
        System.assertEquals('Test exception', log.Message__c);
    }

    @IsTest
    static void testCreateLogWithHttpResponse() {
        // Arrange
        String className = 'TestClass';
        String methodName = 'testMethod';
        HttpResponse response = new HttpResponse();
        response.setStatusCode(200);
        response.setBody('{"message":"success"}');

        // Act
        ClickSignLog__c log = ClickSignUtils.createLog(className, methodName, response);

        // Assert
        System.assertNotEquals(null, log);
        System.assertEquals(className, log.Class__c);
        System.assertEquals(methodName, log.Method__c);
        System.assertEquals(200, log.StatusCode__c);
        System.assertEquals('{"message":"success"}', log.ResponseBody__c);
    }

    @IsTest
    static void testGetOrCreateClickSign() {
        // Arrange
        Account account = new Account(Name = 'Test Account');
        insert account;

        ClickSign__c clickSign = new ClickSign__c(
            RecordId__c = account.Id,
            Status__c = 'Draft'
        );
        insert clickSign;

        // Act
        ClickSign__c result = ClickSignUtils.getOrCreateClickSign(account);

        // Assert
        System.assertNotEquals(null, result);
        System.assertEquals(clickSign.Id, result.Id);
    }


    @IsTest
    static void testCreateClickSign() {
        // Arrange
        Account account = new Account(Name = 'Test Account');
        insert account;

        // Act
        ClickSign__c clickSign = ClickSignUtils.createClickSign(account);

        // Assert
        System.assertNotEquals(null, clickSign);
        System.assertEquals('Documents', clickSign.CurrentStep__c);
        System.assertEquals('Draft', clickSign.Status__c);
        System.assertEquals(account.Id, clickSign.RecordId__c);
    }
}