force-app/main/default/objects/ClickSign__c/ClickSign__c.object-meta.xml
<CustomObject>
    <label>ClickSign</label>
    <nameField>
        <displayFormat>DS-{000000000}</displayFormat>
        <label>ClickSign</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClickSign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSign__c/fields/ClickSignEnvelope__c.field-meta.xml
<CustomField>
    <fullName>ClickSignEnvelope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Envelope</label>
    <referenceTo>ClickSignEnvelope__c</referenceTo>
    <relationshipLabel>ClickSign</relationshipLabel>
    <relationshipName>ClickSign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSign__c/fields/ClickSignTemplate__c.field-meta.xml
<CustomField>
    <fullName>ClickSignTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Template</label>
    <referenceTo>ClickSignTemplate__c</referenceTo>
    <relationshipLabel>ClickSign</relationshipLabel>
    <relationshipName>ClickSign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSign__c/fields/CurrentStep__c.field-meta.xml
<CustomField>
    <fullName>CurrentStep__c</fullName>
    <label>Current Step</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>Recipients</fullName>
            </value>
            <value>
                <fullName>Prepare &amp; Send</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Document Send to Assign</fullName>
            </value>
            <value>
                <fullName>Document Assign</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSignEnvelope__c/ClickSignEnvelope__c.object-meta.xml
<CustomObject>
    <label>ClickSign Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClickSignEnvelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSignSigner__c/ClickSignSigner__c.object-meta.xml
<CustomObject>
    <label>ClickSign Signer</label>
    <nameField>
        <label>Nome de ClickSign Signer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClickSignSigners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSignSigner__c/fields/ClickSign__c.field-meta.xml
<CustomField>
    <fullName>ClickSign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign</label>
    <referenceTo>ClickSign__c</referenceTo>
    <relationshipLabel>ClickSignSigners</relationshipLabel>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/ClickSignEnvelope__c.field-meta.xml
<CustomField>
    <fullName>ClickSignEnvelope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Envelope</label>
    <referenceTo>ClickSignEnvelope__c</referenceTo>
    <relationshipLabel>ClickSignSigners</relationshipLabel>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/ClickSignTemplate__c.field-meta.xml
<CustomField>
    <fullName>ClickSignTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Template</label>
    <referenceTo>ClickSignTemplate__c</referenceTo>
    <relationshipLabel>ClickSignSigners</relationshipLabel>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ClickSignSigners</relationshipLabel>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/ContactsMapping__c.field-meta.xml
<CustomField>
    <fullName>ContactsMapping__c</fullName>
    <label>Contacts Mapping</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/fieldName__c.field-meta.xml
<CustomField>
    <fullName>fieldName__c</fullName>
    <label>Nome do Campo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/RoleLabel__c.field-meta.xml
<CustomField>
    <fullName>RoleLabel__c</fullName>
    <label>RoleLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/SFexternalId__c.field-meta.xml
<CustomField>
    <fullName>SFexternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>SF external Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/SignerType__c.field-meta.xml
<CustomField>
    <fullName>SignerType__c</fullName>
    <label>Tipo do destinatario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>contactId</fullName>
            </value>
            <value>
                <fullName>UserId</fullName>
            </value>
            <value>
                <fullName>object</fullName>
            </value>
            <value>
                <fullName>Any</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criado</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Assinado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante Legal</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/ClickSignTemplate__c.object-meta.xml
<CustomObject>
    <label>ClickSign Template</label>
    <nameField>
        <label>ClickSign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Click Sign Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSignTemplate__c/fields/ButtonLabel__c.field-meta.xml
<CustomField>
    <fullName>ButtonLabel__c</fullName>
    <label>Button Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/ClickSignEnvelope__c.field-meta.xml
<CustomField>
    <fullName>ClickSignEnvelope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Envelope</label>
    <referenceTo>ClickSignEnvelope__c</referenceTo>
    <relationshipLabel>Click Sign Templates</relationshipLabel>
    <relationshipName>ClickSignTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/ContactsMapping__c.field-meta.xml
<CustomField>
    <fullName>ContactsMapping__c</fullName>
    <label>Contacts Mapping</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/IsActivate__c.field-meta.xml
<CustomField>
    <fullName>IsActivate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Activate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/Mapping__c.field-meta.xml
<CustomField>
    <fullName>Mapping__c</fullName>
    <label>Mapping</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/ObjectMappings2__c.field-meta.xml
<CustomField>
    <fullName>ObjectMappings2__c</fullName>
    <label>ObjectMappings2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/ObjectMappings__c.field-meta.xml
<CustomField>
    <fullName>ObjectMappings__c</fullName>
    <label>ObjectMappings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/SourceObject__c.field-meta.xml
<CustomField>
    <fullName>SourceObject__c</fullName>
    <label>Source Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Select Source</fullName>
            </value>
            <value>
                <fullName>Add Fields</fullName>
            </value>
            <value>
                <fullName>Upload Documents</fullName>
            </value>
            <value>
                <fullName>Preview Documents</fullName>
            </value>
            <value>
                <fullName>Add Recipient</fullName>
            </value>
            <value>
                <fullName>Create button Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClickSignDAO.cls
public with sharing class ClickSignDAO {
    public static ClickSign__c getClickSignById(Id clickSignId) {
        return [SELECT Id, Name, CurrentStep__c, Status__c, ClickSignEnvelope__c, ClickSignTemplate__c 
                FROM ClickSign__c WHERE Id = :clickSignId LIMIT 1];
    }

    public static void updateClickSign(ClickSign__c clickSign) {
        update clickSign;
    }
    
    
    public static void deleteClickSign(ClickSign__c clickSign) {
        delete clickSign;
    }

    public static List<ClickSignTemplate__c> getActiveTemplates() {
        return [SELECT Id, Name FROM ClickSignTemplate__c WHERE IsActivate__c = true];
    }

    public static ClickSign__c getOrCreateClickSign(Id recordId) {
        SObject record = Database.query('SELECT Id FROM ' + recordId.getSObjectType().getDescribe().getName() + ' WHERE Id = :recordId LIMIT 1');
        return ClickSignUtils.getOrCreateClickSign(record);
    }

    public static void saveTemplateId(Id clickSignId, Id templateId) {
        ClickSign__c clickSign = getClickSignById(clickSignId);
        clickSign.ClickSignTemplate__c = templateId;
        update clickSign;
    }

    public static ClickSign__c cancelAndCreateClickSign(Id recordId) {
        
        List<ClickSign__c> clickSigns = [SELECT Id, Status__c FROM ClickSign__c WHERE RecordId__c = :recordId and Status__c ='Draft'];
        for(ClickSign__c clickSign:clickSigns){
            clickSign.Status__c = 'Cancelled';
        }
        update clickSigns;
        return getOrCreateClickSign(recordId);
    }

    @AuraEnabled
    public static List<ClickSign__c> getClickSignRecords(Id recordId) {
        try {
            return [
                SELECT Id, Name,CurrentStep__c,Status__c, ClickSignEnvelope__c,ClickSignTemplate__c
                FROM ClickSign__c
                WHERE RecordId__c = :recordId AND Status__c != 'Cancelled' order by lastmodifieddate desc limit 10
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching ClickSign records: ' + e.getMessage());
        }
    }

    public static List<ClickSignTemplate__c> getTemplatesByRecordId(Id recordId) {
        try {
            string objectName = recordId.getSObjectType().getDescribe().getName();
            return [
                SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastViewedDate, LastReferencedDate, Mapping__c, Stage__c, ObjectMappings__c, ObjectMappings2__c, SourceObject__c, Description__c, ClickSignEnvelope__c, ExternalId__c, FileName__c, IsActivate__c, ContactsMapping__c, ButtonLabel__c
                FROM ClickSignTemplate__c
                WHERE SourceObject__c = :objectName
                AND IsActivate__c = true
                AND ButtonLabel__c != null
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching templates: ' + e.getMessage());
        }
    }

    public static List<ClickSignTemplate__c> getTemplatesById(Id recordId) {
        try {
            return [
                SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastViewedDate, LastReferencedDate, Mapping__c, Stage__c, ObjectMappings__c, ObjectMappings2__c,
                 SourceObject__c, Description__c, ClickSignEnvelope__c,
                  ExternalId__c, FileName__c, IsActivate__c, ContactsMapping__c, ButtonLabel__c,
                  (SELECT Id, Name, Status__c, ClickSignEnvelope__c, ClickSign__c, Email__c, ExternalId__c, Role__c, SFexternalId__c, ClickSignTemplate__c, Contact__c, User__c, fieldName__c, SignerType__c, ContactsMapping__c, RoleLabel__c from ClickSignSigners__r)
                FROM ClickSignTemplate__c
                WHERE IsActivate__c = true
                AND Id =: recordId
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching templates: ' + e.getMessage());
        }
    }
}