force-app/main/default/objects/ClickSign__c/ClickSign__c.object-meta.xml
<CustomObject>
    <label>ClickSign</label>
    <nameField>
        <displayFormat>DS-{000000000}</displayFormat>
        <label>ClickSign</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClickSign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSign__c/fields/ClickSignEnvelope__c.field-meta.xml
<CustomField>
    <fullName>ClickSignEnvelope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Envelope</label>
    <referenceTo>ClickSignEnvelope__c</referenceTo>
    <relationshipLabel>ClickSign</relationshipLabel>
    <relationshipName>ClickSign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Document Send to Assign</fullName>
            </value>
            <value>
                <fullName>Document Assign</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSignEnvelope__c/ClickSignEnvelope__c.object-meta.xml
<CustomObject>
    <label>ClickSign Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClickSignEnvelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSignSigner__c/ClickSignSigner__c.object-meta.xml
<CustomObject>
    <label>ClickSign Signer</label>
    <nameField>
        <label>Nome de ClickSign Signer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClickSignSigners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSignSigner__c/fields/ClickSign__c.field-meta.xml
<CustomField>
    <fullName>ClickSign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign</label>
    <referenceTo>ClickSign__c</referenceTo>
    <relationshipLabel>ClickSignSigners</relationshipLabel>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/ClickSignEnvelope__c.field-meta.xml
<CustomField>
    <fullName>ClickSignEnvelope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Envelope</label>
    <referenceTo>ClickSignEnvelope__c</referenceTo>
    <relationshipLabel>ClickSignSigners</relationshipLabel>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criado</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Assinado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/ClickSignEnvelope__c.field-meta.xml
<CustomField>
    <fullName>ClickSignEnvelope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Envelope</label>
    <referenceTo>ClickSignEnvelope__c</referenceTo>
    <relationshipLabel>Versões do conteúdo</relationshipLabel>
    <relationshipName>ContentVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Objeto para gravar logs em caso de erros</description>
    <label>Log</label>
    <nameField>
        <label>Nome de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Método do APEX</description>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <description>API Custom - Corpo da Request</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Callout - Status da Response</description>
    <label>Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/modules/click-sign/ClickSignREST.cls
@RestResource(urlMapping='/clicksign-update/*')
global without sharing class ClickSignREST {

    private static final String SECRET_KEY = '58a75003d36ccb8acfb9482436084784';

    @HttpPost
    global static String updateRecords() {

        String requestBody = RestContext.request.requestBody.toString();

        String receivedSignature = RestContext.request.headers.get('Content-Hmac');

        try{
            if (String.isEmpty(receivedSignature)) {
                //RestContext.response.statusCode = 400;
                //return 'Assinatura ausente';
            }
    
            // Calcular a assinatura HMAC SHA256
            String calculatedSignature = calculateHMAC(requestBody, SECRET_KEY);
    
            // Comparar a assinatura recebida com a calculada
            if (!receivedSignature.equals(calculatedSignature)) {
                //RestContext.response.statusCode = 401; // Unauthorized
                //return 'Assinatura inválida';
            }
                
            // Processa o conteúdo do body (exemplo: JSON)
            ClickSignInboundDTO dto = (ClickSignInboundDTO) JSON.deserialize(requestBody, ClickSignInboundDTO.class);

            List<ContentVersion> versions = [SELECT Id, ContentDocumentId, Title, PathOnClient, ExternalId__c, ClickSignEnvelope__c FROM ContentVersion WHERE ExternalId__c = :dto.document.key];

            ContentVersion currentVersion = versions[0];
                
            if(dto.event.name == 'sign'){
                
                Log__c lg = new Log__c(
                    Class__c  = 'ClickSignRest',
                    Method__c = 'update',
                    RequestBody__c = requestBody 
                );
                insert lg;

                ClickSignSigner__c signer = [SELECT Id, Status__c FROM ClickSignSigner__c WHERE ExternalId__c = :dto.event.data.signer.key];
                signer.Status__c = 'Assinado';
                update signer;
    
            }else if(dto.event.name == 'auto_close'){
                
                Log__c lg = new Log__c(
                    Class__c  = 'ClickSignRest',
                    Method__c = 'update',
                    RequestBody__c = requestBody 
                );
                insert lg;
    
                ClickSign__c clickSign = [SELECT Id, ClickSignEnvelope__c, RecordId__c FROM ClickSign__c WHERE ClickSignEnvelope__c = :currentVersion.ClickSignEnvelope__c];
    
                clickSign.Status__c = 'Document Assign';
                update clickSign;
                
                update new ClickSignEnvelope__c(
                    Id = clickSign.ClickSignEnvelope__c,
                    Status__c = 'Concluído'
                );
            }else if(dto.event.name == 'document_closed'){
                
                Http http = new Http();
                HttpRequest request = new HttpRequest();
    
                request.setEndpoint(dto.document.downloads.signed_file_url);
                request.setMethod('GET');
                request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
                request.setTimeout(120000);
    
                HttpResponse response = http.send(request);
    
                Blob file = response.getBodyAsBlob();
                System.debug('file: ' + file);
    
                if(versions?.isEmpty()) return 'Documento não encontrado: '  + dto.document.key + ' ' + versions;
    
                ClickSign__c clickSign = [SELECT Id, ClickSignEnvelope__c, RecordId__c FROM ClickSign__c WHERE ClickSignEnvelope__c = :currentVersion.ClickSignEnvelope__c];
    
                // Criar nova versão do arquivo
                ContentVersion newVersion = new ContentVersion(
                    ContentDocumentId = currentVersion.ContentDocumentId,
                    VersionData = file,
                    Title = currentVersion.Title + '_signed.pdf',
                    PathOnClient = currentVersion.Title.replace('docx', 'pdf'),
                    ExternalId__c =  currentVersion.ExternalId__c
                );
                
                Log__c lg = new Log__c(
                    Class__c  = 'ClickSignRest',
                    Method__c = 'update',
                    RequestBody__c = requestBody 
                );
                insert lg;
    
                // Inserir a nova versão
                currentVersion.ExternalId__c = currentVersion.ExternalId__c + '_original';
                update currentVersion;
                
                insert newVersion;
    
                newVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :newVersion.Id];
    
                // Criar link entre documento e envelope
                ContentDocumentLink newLink = new ContentDocumentLink(
                    ContentDocumentId = newVersion.ContentDocumentId,
                    LinkedEntityId = clickSign.RecordId__c
                );
    
                insert newLink;
            }
    
            return 'Registros atualizados com sucesso';
        }catch(Exception ex){
            Log__c lg = new Log__c(
                Class__c  = 'ClickSignRest',
                Method__c = 'update',
                RequestBody__c = requestBody 
            );
            insert lg;
            return ex.getMessage() + ' ' + String.valueOf(ex.getLineNumber());
        }
        
    }

    private static String calculateHMAC(String data, String key) {
        Blob mac = Crypto.generateMac('HMACSHA256', Blob.valueOf(data), Blob.valueOf(key));
        return EncodingUtil.base64Encode(mac); // Codificação base64 (alterar conforme necessário)
    }
}