force-app/main/default/objects/Integrador__mdt/Integrador__mdt.object-meta.xml
<CustomObject>
    <description>Metadado para armazenar informações de Endpoints, login, senha</description>
    <label>Integração</label>
    <pluralLabel>Integradores</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id no virtual office</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/StatusBodyIntegracaoNivello__c.field-meta.xml
<CustomField>
    <fullName>StatusBodyIntegracaoNivello__c</fullName>
    <description>Status Code e Body do retorno da integração Nivello</description>
    <label>Status e Body Integração Nivello</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/StatusViabilidade__c.field-meta.xml
<CustomField>
    <fullName>StatusViabilidade__c</fullName>
    <label>Status da Viabilidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Viável</fullName>
            </value>
            <value>
                <fullName>Inviável</fullName>
            </value>
            <value>
                <fullName>Parcialmente Viável</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SucessoIntegracaoNivello__c.field-meta.xml
<CustomField>
    <fullName>SucessoIntegracaoNivello__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar se houve sucesso na integração Nivello ao enviar dados.</description>
    <label>Sucesso na Integração Nivello</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TextoEstudo__c.field-meta.xml
<CustomField>
    <fullName>TextoEstudo__c</fullName>
    <inlineHelpText>Informe o campo texto de estudo com o resultado do estudo feito pelo técnico de campo, quando o status da viabilidade estiver parcialmente viável.</inlineHelpText>
    <label>Texto de Estudo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TextoMotivo__c.field-meta.xml
<CustomField>
    <fullName>TextoMotivo__c</fullName>
    <inlineHelpText>Informe o campo texto de motivo com o resultado do estudo feito pelo técnico de campo, quando o status da viabilidade estiver inviável.</inlineHelpText>
    <label>Texto de Motivo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/IntegracaoNivelloAnaliseVisitaTecnica.cls
public class IntegracaoNivelloAnaliseVisitaTecnica {
  @future(callout=true)
  public static void sendTechnicalVisitAnalysis(Set<Id> triggerIds) {
    List<Opportunity> oppList = [
      SELECT
        Id,
        IdVirtualOffice__c,
        StatusViabilidade__c,
        TextoEstudo__c,
        TextoMotivo__c
      FROM Opportunity
      WHERE Id IN :triggerIds
    ];

    for (Opportunity opp : oppList) {
      TechnicalVisitAnalysisRequest corpoRequisicao = new TechnicalVisitAnalysisRequest();
      corpoRequisicao.id = opp.IdVirtualOffice__c;
      corpoRequisicao.status = opp.StatusViabilidade__c.equalsIgnoreCase(
          'Viável'
        )
        ? 'Viavel'
        : opp.StatusViabilidade__c.equalsIgnoreCase('Inviável')
            ? 'Inviavel'
            : opp.StatusViabilidade__c.equalsIgnoreCase('Parcialmente Viável')
                ? 'ParcialmenteInviavel'
                : '';

      corpoRequisicao.study = corpoRequisicao.status.equalsIgnoreCase(
          'ParcialmenteInviavel'
        )
        ? opp.TextoEstudo__c
        : null;
      corpoRequisicao.reason = corpoRequisicao.status.equalsIgnoreCase(
          'Inviavel'
        )
        ? opp.TextoMotivo__c
        : null;

      try {
        HttpResponse response = chamadaIntegracao(
          JSON.serialize(corpoRequisicao),
          'AnaliseVisitaTecnica',
          opp.Id,
          'sendTechnicalVisitAnalysis'
        );

        //Sucesso
        if (response.getStatusCode() == 200) {
          System.debug('SUCCESS');
          opp.SucessoIntegracaoNivello__c = true;
        }
        //Erro
        else {
          System.debug('ERROR');
          opp.SucessoIntegracaoNivello__c = false;
        }
        opp.StatusBodyIntegracaoNivello__c =
          response.getStatusCode() +
          ' ' +
          response.getBody();
      } catch (Exception e) {
        Utils.createLog(
          'IntegracaoNivelloAnaliseVisitaTecnica',
          'sendTechnicalVisitAnalysis',
          e,
          opp.Id
        );

        opp.SucessoIntegracaoNivello__c = false;
        opp.StatusBodyIntegracaoNivello__c =
          e.getMessage() +
          ' ' +
          e.getStackTraceString();
      }
    }
    OpportunityTriggerHandler.disableTrigger();
    update oppList;
    OpportunityTriggerHandler.enableTrigger();
  }

  private static HttpResponse chamadaIntegracao(
    String body,
    String metadataDeveloperName,
    Id relatedId,
    String logMethodName
  ) {
    Integrador__mdt parametrosIntegracao = [
      SELECT Id, URL__c
      FROM Integrador__mdt
      WHERE DeveloperName = :metadataDeveloperName
    ];

    Http httpObj = new Http();
    HttpRequest request = new HttpRequest();

    request.setEndpoint(parametrosIntegracao.URL__c);
    request.setMethod('PUT');
    request.setHeader('Content-Type', 'application/json');
    request.setBody(body);

    HttpResponse response = Utils.callIntegrationNivello(request);

    Utils.LogDTO logDTO = new Utils.LogDTO();
    logDTO.className = 'IntegracaoNivelloAnaliseVisitaTecnica';
    logDTO.methodName = logMethodName;
    logDTO.relatedId = relatedId;
    logDTO.httpMethod = request.getMethod();
    logDTO.requestBody = body;
    logDTO.requestURI = parametrosIntegracao.URL__c;
    if (response != null) {
      logDTO.statusCode = response.getStatusCode();
      logDTO.status = response.getStatus();
      logDTO.responseBody = response.getBody();
    }
    Utils.createLog(logDTO);

    return response;
  }

  public class TechnicalVisitAnalysisRequest {
    public String id;
    public String status;
    public String study;
    public String reason;
  }
}