force-app/main/default/objects/Integrador__mdt/Integrador__mdt.object-meta.xml
<CustomObject>
    <description>Metadado para armazenar informações de Endpoints, login, senha</description>
    <label>Integração</label>
    <pluralLabel>Integradores</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/BDI__c.field-meta.xml
<CustomField>
    <fullName>BDI__c</fullName>
    <label>BDI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DescontoUFV__c.field-meta.xml
<CustomField>
    <fullName>DescontoUFV__c</fullName>
    <label>R$ Desconto UFV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Direct__c.field-meta.xml
<CustomField>
    <fullName>Direct__c</fullName>
    <description>Campo para definição de Direct.</description>
    <label>Direct</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id no virtual office</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ObservacaoAprovacao__c.field-meta.xml
<CustomField>
    <fullName>ObservacaoAprovacao__c</fullName>
    <label>Observação Aprovação</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pontos__c.field-meta.xml
<CustomField>
    <fullName>Pontos__c</fullName>
    <description>Campo para definição de Pontos.</description>
    <label>Pontos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rede3750__c.field-meta.xml
<CustomField>
    <fullName>Rede3750__c</fullName>
    <label>Rede</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/StatusAprovacaoDesconto__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacaoDesconto__c</fullName>
    <label>Status Aprovação de Desconto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciado</fullName>
                <default>true</default>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorPropostoBDI__c.field-meta.xml
<CustomField>
    <fullName>ValorPropostoBDI__c</fullName>
    <label>Valor Proposto BDI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorPropostoDirect__c.field-meta.xml
<CustomField>
    <fullName>ValorPropostoDirect__c</fullName>
    <label>Valor Proposto Direct</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorPropostoPontos__c.field-meta.xml
<CustomField>
    <fullName>ValorPropostoPontos__c</fullName>
    <label>Valor Proposto Pontos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorPropostoRede3750__c.field-meta.xml
<CustomField>
    <fullName>ValorPropostoRede3750__c</fullName>
    <label>Valor Proposto Rede</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/IntegracaoNivelloAprovacaoDesconto.cls
/**
 * @description       : 
 * @author            : Daniel Belini
 * @group             : 
 * @last modified on  : 11-08-2025
 * @last modified by  : Daniel Belini
**/
public with sharing class IntegracaoNivelloAprovacaoDesconto {
    @future(callout=true)
    public static void enviarStatusAprovacaoDesconto(Set<Id> triggerIds) {
        List<Opportunity> opplist = [
            SELECT  Id, IdVirtualOffice__c, StatusAprovacaoDesconto__c, ObservacaoAprovacao__c, DescontoUFV__c,
                    ValorPropostoBDI__c, ValorPropostoRede3750__c, ValorPropostoPontos__c, ValorPropostoDirect__c,
                    BDI__c, Rede3750__c, Pontos__c, Direct__c
            FROM    Opportunity
            WHERE   Id IN :triggerIds
        ];

        List<Opportunity> oppsToUpdate = new List<Opportunity>();

        for(Opportunity opportunity : opplist){
            try {
                // Prepara a requisição de aprovação do desconto
                DiscountApprovalRequest payload = new DiscountApprovalRequest();
                payload.id = opportunity.IdVirtualOffice__c;
                payload.statusDiscount = (opportunity.StatusAprovacaoDesconto__c == null)  ? 0 : (opportunity.StatusAprovacaoDesconto__c == 'Pendente') ? 1 : (opportunity.StatusAprovacaoDesconto__c == 'Aprovado') ? 2 : 3;
                payload.discountReturnApprovalComments = opportunity.ObservacaoAprovacao__c;
                payload.request = getDecimalOrZero(opportunity.DescontoUFV__c);
                payload.Bdi = getDecimalOrZero(opportunity.ValorPropostoBDI__c);
                payload.Direct = getDecimalOrZero(opportunity.ValorPropostoDirect__c);
                payload.Rede = getDecimalOrZero(opportunity.ValorPropostoRede3750__c);
                payload.Pontos = getDecimalOrZero(opportunity.ValorPropostoPontos__c);
                
                if(opportunity.StatusAprovacaoDesconto__c == 'Aprovado'){
                    payload.returnRequestDiscount = payload.request;
                }else{
                    payload.returnRequestDiscount = 0;
                    opportunity.DescontoUFV__c = 0;
                    oppsToUpdate.add(opportunity);
                }
                
                // Chama a API da Nivello para enviar o status de aprovação do desconto
                HttpResponse response = chamadaIntegracao(JSON.serialize(payload), 'Aprovacao_Desconto', opportunity.Id, 'aprovacaoDesconto');

                if (response.getStatusCode() == 200) {
                    // Parsing the response
                    Map<String, Object> resMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                    if (resMap.containsKey('data')) {
                        Map<String, Object> dataMap = (Map<String, Object>) resMap.get('data');

                        opportunity.BDI__c = (Decimal) dataMap.get('discountedBdi');
                        opportunity.Rede3750__c = (Decimal) dataMap.get('discountedRede');
                        opportunity.Pontos__c = (Decimal) dataMap.get('discountedPontos');
                        opportunity.Direct__c = (Decimal) dataMap.get('discountedDirect');

                        oppsToUpdate.add(opportunity);
                    }
                } else {
                    System.debug('Error in response: ' + response.getBody());
                }
            } catch(Exception ex) {
                Utils.createLog('IntegracaoNivelloAprovacaoDesconto', 'aprovacaoDesconto', ex, opportunity.Id);
            }   
        }

        if (!oppsToUpdate.isEmpty()) {
            OpportunityTriggerHandler.disableTrigger();
            //update oppsToUpdate;
            OpportunityTriggerHandler.enableTrigger();
        }
    }

    private static HttpResponse chamadaIntegracao(String body, String developerName, Id relatedId, String logMethodName) {
        Integrador__mdt parametrosIntegracao = [
            SELECT  Id, URL__c
            FROM    Integrador__mdt 
            WHERE   DeveloperName = :developerName
        ];

        Http httpObj = new Http();
        HttpRequest request = new HttpRequest();
            
        request.setEndpoint(parametrosIntegracao.URL__c);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setBody(body);
        
        HttpResponse response = Utils.callIntegrationNivello(request);

        Utils.LogDTO logDTO = new Utils.LogDTO();
        logDTO.className = 'IntegracaoNivelloAprovacaoDesconto';
        logDTO.methodName = logMethodName;
        logDTO.relatedId = relatedId;
        logDTO.httpMethod = request.getMethod();
        logDTO.requestBody = body;
        logDTO.requestURI = parametrosIntegracao.URL__c;
        if(response != null){
            logDTO.statusCode = response.getStatusCode();
            logDTO.status = response.getStatus();
            logDTO.responseBody = response.getBody();
        }
        Utils.createLog(logDTO);

        return response;
    }

    private static Decimal getDecimalOrZero(Decimal value){
        return value == null ? 0 : value;
    }

    public class DiscountApprovalRequest {
        public String  id;			
        public Integer statusDiscount;		
        public String  discountReturnApprovalComments;
        public Decimal request;	
        public Decimal returnRequestDiscount;	
        public Decimal Bdi;
        public Decimal Direct;
        public Decimal Rede;
        public Decimal Pontos;
    }
}