force-app/main/default/objects/Kit_Instalacao__c/Kit_Instalacao__c.object-meta.xml
<CustomObject>
    <label>Kit Instalação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nºdo Kit Instalacao</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kit Instalações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Kit_Instalacao__c/fields/Nome_da_Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Nome_da_Oportunidade__c</fullName>
    <label>Nome da Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Kit Instalacao</relationshipLabel>
    <relationshipName>Kit_Instalacoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Kit_Instalacao__c.field-meta.xml
<CustomField>
    <fullName>Kit_Instalacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Instalacao</label>
    <referenceTo>Kit_Instalacao__c</referenceTo>
    <relationshipLabel>Produto do Kit</relationshipLabel>
    <relationshipName>Produto_de_oportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/KitInstalacaoTriggerTest.cls
/**
 * @description       :
 * @author            : Daniel Belini
 * @group             :
 * @last modified on  : 03-15-2026
 * @last modified by  : Daniel Belini
 * @test              : N/A - classe de teste executavel
 **/
@isTest
public class KitInstalacaoTriggerTest {
  @TestSetup
  static void makeData() {
    Opportunity opportunity = (Opportunity) TestFactory.createSObject(
      new Opportunity(Pricebook2Id = Test.getStandardPricebookId()),
      true
    );
    String productExternalId =
      'kit-prod-' + String.valueOf(DateTime.now().getTime());
    Product2 product = (Product2) TestFactory.createSObject(
      new Product2(
        ExternalId__c = productExternalId,
        Id_Externo__c = productExternalId,
        ProductCode = productExternalId,
        Name = 'Produto Kit Teste'
      ),
      true
    );
    OpportunityLineItem item = (OpportunityLineItem) TestFactory.createSObject(
      new OpportunityLineItem(
        OpportunityId = opportunity.Id,
        Product2Id = product.Id
      ),
      true
    );
  }

  @isTest
  static void sendKitRecordsToSAPTest() {
    Test.startTest();

    Opportunity opportunity = [
      SELECT Id
      FROM Opportunity
      LIMIT 1
    ];

    Kit_Instalacao__c kit = (Kit_Instalacao__c) TestFactory.createSObject(
      new Kit_Instalacao__c(Nome_da_Oportunidade__c = opportunity.Id),
      true
    );

    OpportunityLineItem item = [
      SELECT Kit_Instalacao__c
      FROM OpportunityLineItem
      LIMIT 1
    ];
    item.Kit_Instalacao__c = kit.Id;
    update item;

    update kit;

    Test.stopTest();
  }

  @isTest
  static void coverageOtherTriggerMethods() {
    Opportunity opportunity = [
      SELECT Id
      FROM Opportunity
      LIMIT 1
    ];

    Kit_Instalacao__c kit = (Kit_Instalacao__c) TestFactory.createSObject(
      new Kit_Instalacao__c(Nome_da_Oportunidade__c = opportunity.Id),
      true
    );

    delete kit;

    KitInstalacaoTriggerHandler.disableTrigger();
    System.assert(!KitInstalacaoTriggerHandler.isTriggerEnabled());

    KitInstalacaoTriggerHandler.enableTrigger();
    System.assert(KitInstalacaoTriggerHandler.isTriggerEnabled());
  }
}