force-app/main/default/objects/Integradores__c/Integradores__c.object-meta.xml
<CustomObject>
    <label>Integrador</label>
    <nameField>
        <label>Nome de Integrador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integradores__c/recordTypes/Integrador.recordType-meta.xml
<RecordType>
    <fullName>Integrador</fullName>
    <active>true</active>
    <label>Integrador</label>
</RecordType>

force-app/main/default/objects/MessagingEndUser/fields/Integrador__c.field-meta.xml
<CustomField>
    <fullName>Integrador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integrador</label>
    <referenceTo>Integradores__c</referenceTo>
    <relationshipLabel>Usuários do Messaging</relationshipLabel>
    <relationshipName>Usuarios_do_Messaging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MessagingEndUser/fields/Telefone_Formatado__c.field-meta.xml
<CustomField>
    <fullName>Telefone_Formatado__c</fullName>
    <formula>IF(
    
    LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 13,
    LEFT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 4) &amp; MID(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 6, LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) - 5),
    
   IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 12,
   SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;),

   IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 11,
   LEFT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(&quot;55&quot; + MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 4) &amp; MID(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(&quot;55&quot; + MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 6, LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(&quot;55&quot; + MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) - 5),
    IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 11,
    &quot;55&quot; + SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;),
    IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 10,
    &quot;55&quot; + SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;),
    IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) &lt; 11, &quot;Número faltando informação: &quot; + MessagingPlatformKey, MessagingPlatformKey))
)))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Telefone Formatado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegradorBO.cls
public with sharing class IntegradorBO {
  public static void sendIntegradorToSAP(List<Integradores__c> integradores) {
    Set<Id> integradorIds = new Set<Id>();

    for (Integradores__c integrador : integradores) {
      integradorIds.add(integrador.Id);
    }

    if (!integradorIds.isEmpty()) {
      IntegracaoSAPIntegrador.sendIntegrador(integradorIds);
    }
  }

  public static void createMessagingUser(
    List<Integradores__c> integradores,
    Map<Id, Integradores__c> oldMap
  ) {
    try {
      List<MessagingEndUser> messagingUsers = new List<MessagingEndUser>();
      Map<String, Integradores__c> integByPhone = new Map<String, Integradores__c>();
      Id channelPartnerId = MessagingEndUserService.resolveChannelId(
        '+55 11 4003-8852'
      );

      for (Integradores__c integ : integradores) {
        if (String.isBlank(integ.Telefone__c)) {
          continue;
        }

        Integradores__c oldInteg = oldMap.get(integ.Id);

        if (oldInteg != null && (oldInteg.Telefone__c == integ.Telefone__c))
          continue;

        integByPhone.put(integ.Telefone_Formatado__c, integ);
      }

      Map<String, MessagingEndUser> endUserByKey = MessagingEndUserService.findAvailableByPhone(
        integByPhone.keySet(),
        'Integrador__c',
        null
      );

      for (Integradores__c integ : integByPhone.values()) {
        MessagingEndUser endUser = endUserByKey.get(
          integ.Telefone_Formatado__c
        );

        if (endUser == null) {
          endUser = MessagingEndUserService.buildNewEndUser(
            integ.Telefone_Formatado__c,
            integ.Name,
            channelPartnerId
          );
          endUser.Integrador__c = integ.Id;
        } else {
          endUser.Integrador__c = integ.Id;
        }

        messagingUsers.add(endUser);
      }

      MessagingEndUserService.save(messagingUsers, true);
    } catch (Exception ex) {
      System.debug('##Erro ao criar messaging user: ' + ex.getMessage());
      System.debug('##Stack: ' + ex.getStackTraceString());
      System.debug('##Line: ' + ex.getLineNumber());
    }
  }
}