force-app/main/default/objects/Account/fields/BairroCobranca__c.field-meta.xml
<CustomField>
    <fullName>BairroCobranca__c</fullName>
    <label>Bairro de Cobrança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BairroEntrega__c.field-meta.xml
<CustomField>
    <fullName>BairroEntrega__c</fullName>
    <label>Bairro de Entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>Campo para CNPJ.</description>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ComplementoCobranca__c.field-meta.xml
<CustomField>
    <fullName>ComplementoCobranca__c</fullName>
    <label>Complemento de Cobrança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ComplementoEntrega__c.field-meta.xml
<CustomField>
    <fullName>ComplementoEntrega__c</fullName>
    <label>Complemento de Entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>Campo para CPF.</description>
    <label>CPF</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <description>Campo Id no virtual office.</description>
    <externalId>true</externalId>
    <label>Id no Gerador de Oportunidades</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/MunicipioCobranca__c.field-meta.xml
<CustomField>
    <fullName>MunicipioCobranca__c</fullName>
    <label>Municipio de Cobrança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MunicipioEntrega__c.field-meta.xml
<CustomField>
    <fullName>MunicipioEntrega__c</fullName>
    <label>Municipio de Entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroRuaCobranca__c.field-meta.xml
<CustomField>
    <fullName>NumeroRuaCobranca__c</fullName>
    <label>Número da Rua de Cobrança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroRuaEntrega__c.field-meta.xml
<CustomField>
    <fullName>NumeroRuaEntrega__c</fullName>
    <label>Número da Rua de Entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SeCPFouCNPJ__c.field-meta.xml
<CustomField>
    <fullName>SeCPFouCNPJ__c</fullName>
    <description>Campo para pegar ou CPF ou CNPJ.</description>
    <formula>IF( CNPJ__c =null,SUBSTITUTE(SUBSTITUTE(CPF__c, &quot;-&quot;, null),&quot;.&quot;, null),
SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(CNPJ__c , &quot;-&quot;, null),&quot;.&quot;, null), &quot;/&quot;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SeCPFouCNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/StatusBodyIntegracaoSAP__c.field-meta.xml
<CustomField>
    <fullName>StatusBodyIntegracaoSAP__c</fullName>
    <label>Status Body Integracao SAP</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/SucessoIntegracaoSAP__c.field-meta.xml
<CustomField>
    <fullName>SucessoIntegracaoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sucesso Integração SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IntegracaoSAPCliente.cls
/**
 * @description       :
 * @author            : Daniel Belini
 * @group             :
 * @last modified on  : 03-18-2026
 * @last modified by  : Daniel Belini
 * @test              : IntegracaoSAPClienteTest
 **/
public with sharing class IntegracaoSAPCliente implements Queueable, Database.AllowsCallouts {
  private final Set<Id> recordIds;

  public IntegracaoSAPCliente(Set<Id> recordIds) {
    this.recordIds = recordIds;
  }

  public void execute(QueueableContext ctx) {
    List<Account> accountList = [
      SELECT
        Id,
        IdVirtualOffice__c,
        CPF__c,
        CNPJ__c,
        Description,
        SeCPFouCNPJ__c,
        Name,
        Type,
        Email__c,
        Phone,
        BillingStreet,
        BillingPostalCode,
        BillingCity,
        BillingCountry,
        BillingState,
        BillingAddress,
        BairroCobranca__c,
        MunicipioCobranca__c,
        ComplementoCobranca__c,
        NumeroRuaCobranca__c,
        ShippingStreet,
        ShippingPostalCode,
        ShippingCity,
        ShippingCountry,
        ShippingState,
        ShippingAddress,
        BairroEntrega__c,
        MunicipioEntrega__c,
        ComplementoEntrega__c,
        NumeroRuaEntrega__c,
        SucessoIntegracaoSAP__c,
        StatusBodyIntegracaoSAP__c
      FROM Account
      WHERE Id IN :recordIds
      WITH SECURITY_ENFORCED
    ];

    SAPIntegrationService.EndpointConfig sapConfig = SAPIntegrationService.resolveConfig(
      'ClienteSAP'
    );

    for (Account acc : accountList) {
      String docValue = acc.SeCPFouCNPJ__c;
      ClienteRequest corpoRequisicao = new ClienteRequest();
      corpoRequisicao.CardCode = docValue;
      corpoRequisicao.CardName = acc.Name;
      corpoRequisicao.CardType = 'cCustomer';
      corpoRequisicao.EmailAddress = acc.Email__c;
      corpoRequisicao.Phone1 = acc.Phone;
      corpoRequisicao.FederalTaxID = docValue;
      corpoRequisicao.BPAddresses = new List<SAPBusinessPartnerMapper.BPAddress>{};
      corpoRequisicao.BPFiscalTaxIDCollection = new List<SAPBusinessPartnerMapper.BPFiscalTaxID>{};

      if (acc.BillingAddress != null) {
        corpoRequisicao.BPAddresses.add(
          SAPBusinessPartnerMapper.buildBillingAddress(
            docValue,
            acc.BillingStreet,
            acc.NumeroRuaCobranca__c,
            acc.BairroCobranca__c,
            acc.BillingPostalCode,
            acc.BillingCity,
            acc.BillingCity,
            SAPBusinessPartnerMapper.normalizeCountry(acc.BillingCountry),
            SAPBusinessPartnerMapper.normalizeState(acc.BillingState),
            acc.ComplementoCobranca__c
          )
        );
      }

      if (acc.ShippingAddress != null) {
        corpoRequisicao.BPAddresses.add(
          SAPBusinessPartnerMapper.buildShippingAddress(
            docValue,
            acc.ShippingStreet,
            acc.NumeroRuaEntrega__c,
            acc.BairroEntrega__c,
            acc.ShippingPostalCode,
            acc.ShippingCity,
            acc.BillingCity,
            SAPBusinessPartnerMapper.normalizeCountry(acc.ShippingCountry),
            SAPBusinessPartnerMapper.normalizeState(acc.ShippingState),
            acc.ComplementoEntrega__c
          )
        );
      }

      corpoRequisicao.BPFiscalTaxIDCollection.add(
        SAPBusinessPartnerMapper.buildFiscalTaxId(
          acc.CPF__c,
          acc.CNPJ__c,
          docValue
        )
      );

      try {
        String requestBody = JSON.serialize(corpoRequisicao);
        System.debug(
          LoggingLevel.ERROR,
          'IntegracaoSAPCliente request body: ' + requestBody
        );
        HttpResponse response = SAPIntegrationService.post(
          requestBody,
          sapConfig,
          null
        );
        Utils.createLog(
          'IntegracaoSAPCliente',
          'sendCliente ' + acc.Id,
          response
        );

        if (response.getBody() != null && response.getBody() != '') {
          Map<String, Object> responseBody = (Map<String, Object>) JSON.deserializeUntyped(
            response.getBody()
          );
          Integer statusCode = Integer.valueOf(responseBody.get('codigoHttp'));
          acc.SucessoIntegracaoSAP__c = SAPIntegrationService.isSuccess(
            statusCode
          );
          acc.StatusBodyIntegracaoSAP__c =
            statusCode +
            ' ' +
            response.getBody() +
            ' ' +
            response.getStatus();
        }
      } catch (Exception e) {
        Utils.createLog('IntegracaoSAPCliente', 'sendCliente ' + acc.Id, e);
        acc.SucessoIntegracaoSAP__c = false;
        acc.StatusBodyIntegracaoSAP__c =
          e.getMessage() +
          ' ' +
          e.getStackTraceString();
      }
    }

    AccountTriggerHandler.disableTrigger();
    try {
      update accountList;
    } finally {
      AccountTriggerHandler.enableTrigger();
    }
  }

  public class ClienteRequest {
    public String CardCode;
    public String CardName;
    public String CardType;
    public String EmailAddress;
    public String Phone1;
    public String FederalTaxID;
    public SAPBusinessPartnerMapper.BPAddress[] BPAddresses;
    public SAPBusinessPartnerMapper.BPFiscalTaxID[] BPFiscalTaxIDCollection;
  }
}