force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>Campo para CNPJ.</description>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>Campo para CPF.</description>
    <label>CPF</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <description>Campo Id no virtual office.</description>
    <externalId>true</externalId>
    <label>Id no Gerador de Oportunidades</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroIdentificacao__c.field-meta.xml
<CustomField>
    <fullName>NumeroIdentificacao__c</fullName>
    <label>Numero de Identificação</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/modules/collection/CollectionTest.cls
@IsTest
public class CollectionTest {

    @isTest
    static void test1(){
        List<Account> accounts = new List<Account>{
            (Account) TestFactory.createSObject(new Account(
                Name = 'Foo'
            ), true),
            (Account) TestFactory.createSObject(new Account(
                Name                   = 'Bar',
                CPF__c                 = '234.567.897-56',
                CNPJ__c                = '12.345.678/9012-35',
                IdVirtualOffice__c     = 'klskdjf9-dmz-nf-r93u4-edjl-kdna7',
                NumeroIdentificacao__c = '234.567.897-56'
            ), true)
        };

        List<String> names = Collection.of(accounts).pluckNotNullStrings(Account.Name);
		System.assertEquals(2, names.size());
		System.assertEquals('Foo', names[0]);
		System.assertEquals('Bar', names[1]);

		List<Id> ownerIds = Collection.of(accounts).pluckIds();
		Set<Id> idSet = new Set<Id>(ownerIds);
		System.assertEquals(2, idSet.size());
    }
}