force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>Campo para CNPJ.</description>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DescricaoBateria__c.field-meta.xml
<CustomField>
    <fullName>DescricaoBateria__c</fullName>
    <description>Descrição da bateria para exibição em propostas.</description>
    <label>Descrição da Bateria</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <description>Campo para definir o sub-grupo tarifário.</description>
    <label>Grupo Tarifário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
            <value>
                <fullName>Grupo B Optante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isPromotional__c.field-meta.xml
<CustomField>
    <fullName>isPromotional__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promocional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Numeroproposta__c.field-meta.xml
<CustomField>
    <fullName>Numeroproposta__c</fullName>
    <displayFormat>P-{000000}</displayFormat>
    <label>Número da Proposta</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PropostaAlterada__c.field-meta.xml
<CustomField>
    <fullName>PropostaAlterada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proposta Alterada?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SelectedSimulation__c.field-meta.xml
<CustomField>
    <fullName>SelectedSimulation__c</fullName>
    <label>Simulação Selecionada</label>
    <referenceTo>PaymentSimulation__c</referenceTo>
    <relationshipLabel>Oportunidade (Simulação Selecionada)</relationshipLabel>
    <relationshipName>SelectedForOpportunity</relationshipName>
    <type>Lookup</type>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PaymentSimulation__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoKitPromocional__c.field-meta.xml
<CustomField>
    <fullName>TipoKitPromocional__c</fullName>
    <label>Tipo Kit Promocional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoKitPromocional</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorTotalProposta__c.field-meta.xml
<CustomField>
    <fullName>ValorTotalProposta__c</fullName>
    <description
  >Campo que indica o valor total da proposta, incluindo o custo adicional somado ao valor da proposta.</description>
    <formula>IF(
    OR(
        AND(
            RecordType.DeveloperName = &quot;Solar&quot;,
            DATEVALUE(CreatedDate) &gt;= DATE(2025, 8, 12)
        ),
        RecordType.DeveloperName = &quot;Produtos&quot;
    ),
    CustoFinanceiroWeg__c +
    CustoAdicionalFixo__c +
    ValorInstalacao__c +
    Rede3750__c +
    Pontos__c +
    Acoplamento__c +
    BDI__c +
    ValorTotalProdutos__c +
    Direct__c + ClientTotalCost__c + 
    ValorAdicionalVendaFinal__c,
    IF(
        OR(
            RecordType.DeveloperName = &quot;EzeeConnect&quot;,
            RecordType.DeveloperName = &quot;EzeeConnect_Solled&quot;,
            RecordType.DeveloperName = &quot;BowE&quot;,
            RecordType.DeveloperName = &quot;Ultragaz&quot;,
            RecordType.DeveloperName = &quot;Simplifica&quot;,
            RecordType.DeveloperName = &quot;Nextron&quot;,
            RecordType.DeveloperName = &quot;Origo&quot;,
            RecordType.DeveloperName = &quot;Raizen&quot;,
            RecordType.DeveloperName = &quot;Plin&quot;
        ),
        FaturaDescontoFixo__c,
        ValorTotalProdutos__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Campo que indica o valor total da proposta, incluindo o custo adicional somado ao valor da proposta.</inlineHelpText>
    <label>Valor Total da Proposta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ViabilityStudyFinished__c.field-meta.xml
<CustomField>
    <fullName>ViabilityStudyFinished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estudo de Viabilidade Finalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Solar</businessProcess>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <label>Parceiro</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parceiro__c/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <label>Grupo Tarifário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentSimulation__c/PaymentSimulation__c.object-meta.xml
<CustomObject>
    <label>Simulação de Pagamento</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Número da Simulação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulações de Pagamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentSimulation__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Tipo de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Financing</fullName>
            </value>
            <value>
                <fullName>ManualFinancing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/ProposalCover__c.object-meta.xml
<CustomObject>
    <label>Capa de Proposta</label>
    <nameField>
        <label>Nome de Capa de Proposta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capa de Propostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProposalCover__c/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <label>Grupo Tarifario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/IntegrationKey__c.field-meta.xml
<CustomField>
    <fullName>IntegrationKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Chave funcional que identifica o conjunto de tags e seções configuradas para esta capa no sistema de geração de propostas via API. Obrigatória quando &quot;URL do Template&quot; estiver preenchida. Valores conhecidos: GRUPO_B_PADRAO. Sem este campo, a geração via API falhará.</description>
    <externalId>true</externalId>
    <label>Integration Key</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/isPromotional__c.field-meta.xml
<CustomField>
    <fullName>isPromotional__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promocional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ModeloPropostaA</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaB</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaBowe</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaEzeeConnect</fullName>
            </value>
            <value>
                <fullName>WorkDeliveryReportPdf</fullName>
                <isActive>false</isActive>
                <label>WorkDeliveryReportPdf</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/TemplateUrl__c.field-meta.xml
<CustomField>
    <fullName>TemplateUrl__c</fullName>
    <label>URL do Template</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/TipoKitPromocional.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>KITS MONOFÁSICOS</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>KITS TRIFÁSICOS</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>KITS MICRO</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>CAMPANHA WEG - FAST TRACK</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>KITS TRIFÁSICOS PROMO WEG</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>KIT SOLAR + BESS</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>KITS MONOFÁSICOS SEM WEGHOME</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>KITS MICRO SEM WEGHOME</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <masterLabel>Tipo Kit Promocional</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProposalContextResolver.cls
/**
 * @description       :
 * @author            : Daniel Belini
 * @group             :
 * @last modified on  : 04-14-2026
 * @last modified by  : Daniel Belini
 * @test              : ProposalEngineSupportTest
 **/
public with sharing class ProposalContextResolver {
  public class Context {
    public Opportunity opportunity;
    public ProposalCover__c cover;
    public Boolean isPromotional;
    public String scenario;
    public String paymentType;
    public String coverKey;
  }

  public static Boolean determineIsPromotional(Opportunity opportunityRecord) {
    if (opportunityRecord == null) {
      return false;
    }

    return String.isNotBlank(opportunityRecord.TipoKitPromocional__c);
  }

  @TestVisible
  static Boolean shouldShowFinancingInInitial(Opportunity opportunityRecord) {
    if (opportunityRecord == null) {
      return false;
    }

    Decimal amount = opportunityRecord.ValorTotalProposta__c != null &&
      opportunityRecord.ValorTotalProposta__c > 0
      ? opportunityRecord.ValorTotalProposta__c
      : opportunityRecord.Amount;

    String cnpj = opportunityRecord.Account != null
      ? opportunityRecord.Account.CNPJ__c
      : null;

    Boolean eligibleByValue = PaymentSimulationBO.isRentalEligible(
      amount,
      cnpj,
      opportunityRecord.TipoKitPromocional__c
    );

    // Card de aluguel so aparece se elegivel por valor E existir simulacao RENTAL real.
    // Sem isso o PDF renderiza o card "EZEE SOLAR - ALUGUEL" vazio.
    return !(eligibleByValue && hasRentalSimulation(opportunityRecord.Id));
  }

  @TestVisible
  static Boolean hasRentalSimulation(Id opportunityId) {
    if (opportunityId == null) {
      return false;
    }

    for (
      PaymentSimulation__c simulationRecord : PaymentSimulationDAO.getByOpportunityIds(
        new Set<Id>{ opportunityId }
      )
    ) {
      if ('RENTAL'.equalsIgnoreCase(simulationRecord.PaymentType__c)) {
        return true;
      }
    }
    return false;
  }

  public static Context resolve(Id opportunityId, Id coverId) {
    if (opportunityId == null || coverId == null) {
      throw new ProposalGenerationService.ProposalGenerationException(
        'O registro da oportunidade e a capa da proposta sao obrigatorios.'
      );
    }

    Opportunity opportunityRecord = [
      SELECT
        Id,
        Name,
        CreatedDate,
        AccountId,
        Account.Name,
        Account.CNPJ__c,
        Numeroproposta__c,
        GrupoTarifario__c,
        StageName,
        RecordTypeId,
        RecordType.Name,
        RecordType.DeveloperName,
        PropostaAlterada__c,
        Parceiro__c,
        Parceiro__r.Name,
        ViabilityStudyFinished__c,
        TipoKitPromocional__c,
        DescricaoBateria__c,
        ValorTotalProposta__c,
        Amount,
        SelectedSimulation__c,
        SelectedSimulation__r.PaymentType__c,
        isPromotional__c
      FROM Opportunity
      WHERE Id = :opportunityId
      LIMIT 1
    ];

    ProposalCover__c coverRecord = [
      SELECT
        Id,
        Name,
        Template__c,
        TemplateUrl__c,
        IsActive__c,
        IntegrationKey__c,
        isPromotional__c
      FROM ProposalCover__c
      WHERE Id = :coverId
      LIMIT 1
    ];

    if (coverRecord.IsActive__c != true) {
      throw new ProposalGenerationService.ProposalGenerationException(
        'A capa de proposta selecionada esta inativa.'
      );
    }

    Context context = new Context();
    context.opportunity = opportunityRecord;
    context.cover = coverRecord;
    context.coverKey = ProposalCoverRoutingService.resolveCoverKey(coverRecord);
    context.paymentType = opportunityRecord.SelectedSimulation__r != null
      ? opportunityRecord.SelectedSimulation__r.PaymentType__c
      : null;

    if (opportunityRecord.SelectedSimulation__c != null) {
      context.scenario = ProposalConfigurationService.SCENARIO_PAYMENT_SELECTED;
    } else if (shouldShowFinancingInInitial(opportunityRecord)) {
      context.scenario = ProposalConfigurationService.SCENARIO_INITIAL_FINANCING;
    } else {
      context.scenario = ProposalConfigurationService.SCENARIO_INITIAL;
    }

    context.isPromotional = determineIsPromotional(opportunityRecord);

    return context;
  }
}