force-app/main/default/objects/Account/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <referenceTo>Consultor__c</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CertidaoNegativaCriminal__c.field-meta.xml
<CustomField>
    <fullName>CertidaoNegativaCriminal__c</fullName>
    <label>Certidão Negativa Criminal</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/EmailIntegradorWeb__c.field-meta.xml
<CustomField>
    <fullName>EmailIntegradorWeb__c</fullName>
    <label>Email do Integrador</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nome_do_Consultor__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do Consultor</label>
    <referenceTo>Consultor__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/NomeIntegradorWeb__c.field-meta.xml
<CustomField>
    <fullName>NomeIntegradorWeb__c</fullName>
    <label>Nome do Integrador</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ClickSign__c/ClickSign__c.object-meta.xml
<CustomObject>
    <label>ClickSign</label>
    <nameField>
        <displayFormat>DS-{000000000}</displayFormat>
        <label>ClickSign</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClickSign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSign__c/fields/ClickSignEnvelope__c.field-meta.xml
<CustomField>
    <fullName>ClickSignEnvelope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Envelope</label>
    <referenceTo>ClickSignEnvelope__c</referenceTo>
    <relationshipLabel>ClickSign</relationshipLabel>
    <relationshipName>ClickSign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSign__c/fields/ClickSignTemplate__c.field-meta.xml
<CustomField>
    <fullName>ClickSignTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Template</label>
    <referenceTo>ClickSignTemplate__c</referenceTo>
    <relationshipLabel>ClickSign</relationshipLabel>
    <relationshipName>ClickSign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSign__c/fields/CurrentStep__c.field-meta.xml
<CustomField>
    <fullName>CurrentStep__c</fullName>
    <label>Current Step</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>Recipients</fullName>
            </value>
            <value>
                <fullName>Prepare &amp; Send</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Document Send to Assign</fullName>
            </value>
            <value>
                <fullName>Document Assign</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSignEnvelope__c/ClickSignEnvelope__c.object-meta.xml
<CustomObject>
    <label>ClickSign Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClickSignEnvelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSignSigner__c/ClickSignSigner__c.object-meta.xml
<CustomObject>
    <label>ClickSign Signer</label>
    <nameField>
        <label>Nome de ClickSign Signer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClickSignSigners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSignSigner__c/fields/ClickSign__c.field-meta.xml
<CustomField>
    <fullName>ClickSign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign</label>
    <referenceTo>ClickSign__c</referenceTo>
    <relationshipLabel>ClickSignSigners</relationshipLabel>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/ClickSignEnvelope__c.field-meta.xml
<CustomField>
    <fullName>ClickSignEnvelope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Envelope</label>
    <referenceTo>ClickSignEnvelope__c</referenceTo>
    <relationshipLabel>ClickSignSigners</relationshipLabel>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/ClickSignTemplate__c.field-meta.xml
<CustomField>
    <fullName>ClickSignTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Template</label>
    <referenceTo>ClickSignTemplate__c</referenceTo>
    <relationshipLabel>ClickSignSigners</relationshipLabel>
    <relationshipName>ClickSignSigners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClickSignSigner__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Criado</fullName>
            </value>
            <value>
                <fullName>Notificado</fullName>
            </value>
            <value>
                <fullName>Assinado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/ClickSignTemplate__c.object-meta.xml
<CustomObject>
    <label>ClickSign Template</label>
    <nameField>
        <label>ClickSign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Click Sign Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClickSignTemplate__c/fields/ClickSignEnvelope__c.field-meta.xml
<CustomField>
    <fullName>ClickSignEnvelope__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClickSign Envelope</label>
    <referenceTo>ClickSignEnvelope__c</referenceTo>
    <relationshipLabel>Click Sign Templates</relationshipLabel>
    <relationshipName>ClickSignTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/IsActivate__c.field-meta.xml
<CustomField>
    <fullName>IsActivate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Activate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClickSignTemplate__c/fields/ObjectMappings__c.field-meta.xml
<CustomField>
    <fullName>ObjectMappings__c</fullName>
    <label>ObjectMappings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Consultor__c/Consultor__c.object-meta.xml
<CustomObject>
    <label>Consultor</label>
    <nameField>
        <label>Nome do Consultor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Campo para definir E-mail do cliente.</description>
    <inlineHelpText>abcd@gmail.com</inlineHelpText>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Consultor__c/recordTypes/Consultor.recordType-meta.xml
<RecordType>
    <fullName>Consultor</fullName>
    <active>true</active>
    <label>Consultor</label>
</RecordType>

force-app/main/default/classes/ClickSignControllerTest.cls
@isTest
public class ClickSignControllerTest {

    @testSetup
    static void setup() {
        // Create test data

        ClickSignEnvelope__c envelope = new ClickSignEnvelope__c(
            Name = 'Test Envelope',
            Status__c = 'Draft',
            ExternalId__c = 'envelope123'
        );
        insert envelope;

        ClickSignTemplate__c template = new ClickSignTemplate__c(
            Name = 'Test Envelope',
            ExternalId__c = 'envelope123',
            ObjectMappings__c = '[{"id":"field-1738590601283","fieldName":"certidaonegativacriminal__c","relationshipField":null,"relatedField":null,"tag":"{{/case/certidaonegativacriminal__c}}","tagLabel":"{{casecertidaonegativacriminal__c}}","labelFieldName":"Certidão Negativa Criminal","labelRelatedField":null},{"id":"field-1738590604586","fieldName":"nome_do_consultor__c","relationshipField":"Consultor__c","relatedField":null,"tag":"{{/case/nome_do_consultor__c}}","tagLabel":"{{casenome_do_consultor__c}}","labelFieldName":"Nome do Consultor","labelRelatedField":null}]'
        );
        insert template;

        ClickSign__c clickSign = new ClickSign__c(
            CurrentStep__c = 'Documents',
            Status__c = 'Draft', 
            ClickSignEnvelope__c = envelope.Id,
            ClickSignTemplate__c = template.Id
        );
        insert clickSign;


        ClickSignSigner__c signer = new ClickSignSigner__c(
            Name = 'Test Signer',
            Email__c = 'test@example.com',
            Role__c = 'Signer',
            ClickSign__c = clickSign.Id
        );
        insert signer;

        Case caseRecord = new Case(Status='Novo',Origin='Web To Case Integrador',NomeIntegradorWeb__c='Darth Vader2',EmailIntegradorWeb__c='darth.vader2@teste.com',RecordTypeId='012U500000015IbIAI');
        insert caseRecord;
    }

    @IsTest
    static void testPrepareToSend(){

        ClickSign__c clickSign = [SELECT Id, ClickSignEnvelope__c FROM ClickSign__c LIMIT 1];

        String payload = getPayload('document');

        Test.setMock(HttpCalloutMock.class, new ClickSignMock(payload));
        Test.startTest();
        try{
            clickSign = ClickSignController.prepareToSend(clickSign.ClickSignEnvelope__c, clickSign.Id);
        }catch(Exception ex){
            
        }
        
        Test.stopTest();
    }

    @isTest
    static void testProcess() {
        ClickSign__c clickSign = [SELECT Id, CurrentStep__c FROM ClickSign__c LIMIT 1];
        Case c = [SELECT Id FROM Case LIMIT 1];

        String payload = getPayload('documents');

        Test.setMock(HttpCalloutMock.class, new ClickSignMock(payload));
        Test.startTest();
        try{
            String result = ClickSignController.process(clickSign, c.Id, clickSign.CurrentStep__c);
        }catch(Exception ex){

        }
        
        Test.stopTest();
    }

    @isTest
    static void testGetOrCreateClickSign() {
        ClickSign__c clickSign = [SELECT Id FROM ClickSign__c LIMIT 1];
        Test.startTest();
        ClickSign__c result = ClickSignController.getOrCreateClickSign(clickSign.Id);
        Test.stopTest();
        System.assertNotEquals(null, result);
    }

    @isTest
    static void testCreateNewClickSign() {
        ClickSign__c clickSign = [SELECT Id FROM ClickSign__c LIMIT 1];
        Test.startTest();
        ClickSign__c newClickSign = ClickSignController.createNewClickSign(clickSign.Id);
        Test.stopTest();
        System.assertNotEquals(null, newClickSign);
    }

    @isTest
    static void testGetDocuments() {
        ClickSign__c clickSign = [SELECT Id FROM ClickSign__c LIMIT 1];
        Test.startTest();
        List<ContentDocument> documents = ClickSignController.getDocuments(clickSign.Id);
        Test.stopTest();
        System.assertNotEquals(null, documents);
    }

    @isTest
    static void testUploadDocument() {
        ClickSign__c clickSign = [SELECT Id FROM ClickSign__c LIMIT 1];
        Test.startTest();
        ClickSignController.uploadDocument('Test Document', 'dGVzdCBjb250ZW50', 'application/pdf', clickSign.Id);
        Test.stopTest();
        List<ContentDocument> documents = ClickSignController.getDocuments(clickSign.Id);
        ClickSignController.deleteDocument(documents[0].Id);
    }

    @isTest
    static void testSaveRecipient() {
        ClickSign__c clickSign = [SELECT Id FROM ClickSign__c LIMIT 1];
        Map<String, Object> recipient = new Map<String, Object>{
            'name' => 'New Signer',
            'email' => 'new@example.com',
            'role' => 'Signer'
        };
        Test.startTest();
        ClickSignSigner__c signer = ClickSignController.saveRecipient(recipient, clickSign.Id,null);
        Test.stopTest();
        System.assertNotEquals(null, signer);
    }

    @isTest
    static void testGetRecipients() {
        ClickSign__c clickSign = [SELECT Id FROM ClickSign__c LIMIT 1];
        Test.startTest();
        List<ClickSignSigner__c> signers = ClickSignController.getRecipients(clickSign.Id);
        Test.stopTest();
        System.assertNotEquals(0, signers.size());
    }

    @isTest
    static void testDeleteRecipient() {
        ClickSignSigner__c signer = [SELECT Id FROM ClickSignSigner__c LIMIT 1];
        Test.startTest();
        try{
            ClickSignController.deleteRecipient(signer.Id);
        }catch(Exception ex){
            
        }
        Test.stopTest();
    }

    @isTest
    static void testUpdateClickSignCurrentStep() {
        ClickSign__c clickSign = [SELECT Id FROM ClickSign__c LIMIT 1];
        Test.startTest();
        ClickSignController.updateClickSignCurrentStep(clickSign.Id, 'Recipients');
        Test.stopTest();
        ClickSign__c updatedClickSign = [SELECT CurrentStep__c FROM ClickSign__c WHERE Id = :clickSign.Id];
        System.assertEquals('Recipients', updatedClickSign.CurrentStep__c);
    }

    @isTest
    static void testGetClickSignRecords() {
        ClickSign__c clickSign = [SELECT Id FROM ClickSign__c LIMIT 1];
        Test.startTest();
        try{
            List<ClickSign__c> clickSignRecords = ClickSignController.getClickSignRecords(clickSign.Id);
        }catch(Exception ex){
            
        }
        Test.stopTest();
    }

    @isTest
    static void testGetObjectList() {
        Test.startTest();
        List<String> objectList = ClickSignController.getObjectList();
        Test.stopTest();
        System.assertNotEquals(0, objectList.size());
    }

    @isTest
    static void testGetRecordList() {
        Test.startTest();
        try{
            List<SObject> recordList = ClickSignController.getRecordList('Account');
        }catch(Exception ex){
            
        }
        Test.stopTest();
    }

    @isTest
    static void testGetActiveTemplates() {
        Test.startTest();
        try{
            List<ClickSignTemplate__c> templates = ClickSignController.getActiveTemplates();
        }catch(Exception ex){
            
        }
        Test.stopTest();
    }

    @isTest
    static void testSaveTemplateId() {
        ClickSign__c clickSign = [SELECT Id FROM ClickSign__c LIMIT 1];
        ClickSignTemplate__c template = new ClickSignTemplate__c(
            Name = 'Test Template',
            IsActivate__c = true
        );
        insert template;
        Test.startTest();
        ClickSignController.saveTemplateId(clickSign.Id, template.Id);
        Test.stopTest();
        ClickSign__c updatedClickSign = [SELECT ClickSignTemplate__c FROM ClickSign__c WHERE Id = :clickSign.Id];
        System.assertEquals(template.Id, updatedClickSign.ClickSignTemplate__c);
    }

    // Mock class for HttpCallout
    private static String getPayload(String node){

        StaticResource payload = [SELECT Id, Body FROM StaticResource WHERE Name = 'ClickSignMock' LIMIT 1];
        
        Map<String, Object> mapPayload = (Map<String, Object>)JSON.deserializeUntyped(payload.Body.toString());

        return JSON.serialize(mapPayload.get(node));
    }
}