force-app/main/default/objects/Account/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <referenceTo>Consultor__c</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Parceiro.recordType-meta.xml
<RecordType>
    <fullName>Parceiro</fullName>
    <active>true</active>
    <description>Tipo de registro para parceiros franqueados.</description>
    <label>Parceiro</label>
</RecordType>

force-app/main/default/objects/Consultor__c/Consultor__c.object-meta.xml
<CustomObject>
    <label>Consultor</label>
    <nameField>
        <label>Nome do Consultor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultor__c/recordTypes/Consultor.recordType-meta.xml
<RecordType>
    <fullName>Consultor</fullName>
    <active>true</active>
    <label>Consultor</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ConsultorOportunidade__c.field-meta.xml
<CustomField>
    <fullName>ConsultorOportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para relacionar a oportunidade ao consultor.</description>
    <label>Consultor</label>
    <referenceTo>Consultor__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PotenciaPicoSistema__c.field-meta.xml
<CustomField>
    <fullName>PotenciaPicoSistema__c</fullName>
    <description>Campo para definir a potencia pico do sistema.</description>
    <label>Potência Pico do Sistema (kWp)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wemob</fullName>
            </value>
            <value>
                <fullName>Bateria</fullName>
            </value>
            <value>
                <fullName>Estacao de Recarga</fullName>
            </value>
            <value>
                <fullName>Modulos</fullName>
            </value>
            <value>
                <fullName>Inversores</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Solar</businessProcess>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <label>Parceiro</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parceiro__c/fields/CapaProposta__c.field-meta.xml
<CustomField>
    <fullName>CapaProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capa de Proposta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ProposalCover__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProposalCover__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parceiro__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ezee Livre</fullName>
            </value>
            <value>
                <fullName>Ezee Connect</fullName>
            </value>
            <value>
                <fullName>Ezee Solar</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Produtos</fullName>
            </value>
            <value>
                <fullName>Serviços</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/ProposalCover__c.object-meta.xml
<CustomObject>
    <label>Capa de Proposta</label>
    <nameField>
        <label>Nome de Capa de Proposta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capa de Propostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ViabilityStudy__c/ViabilityStudy__c.object-meta.xml
<CustomObject>
    <label>Viabilidade</label>
    <nameField>
        <displayFormat>VS-{0000000}</displayFormat>
        <label>Nome de Viabilidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viabilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ViabilityStudy__c/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Consultor responsável pela análise de viabilidade.</description>
    <inlineHelpText>Selecione o consultor ou integrador responsável pela etapa de viabilidade.</inlineHelpText>
    <label>Consultor</label>
    <referenceTo>Consultor__c</referenceTo>
    <relationshipLabel>Viabilidades</relationshipLabel>
    <relationshipName>ViabilityStudies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ViabilityStudy__c/fields/FixationStructureVerifiedPlace__c.field-meta.xml
<CustomField>
    <fullName>FixationStructureVerifiedPlace__c</fullName>
    <label>Estrutura de fixação (verificado in loco</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ViabilityStudy__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Estudos_de_Viabilidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ViabilityStudy__c/fields/TypeWorkProjectFeasibility__c.field-meta.xml
<CustomField>
    <fullName>TypeWorkProjectFeasibility__c</fullName>
    <label>Tipo de Obra/Projeto:</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UFV Micro</fullName>
            </value>
            <value>
                <fullName>UFV Mini até 300</fullName>
            </value>
            <value>
                <fullName>UFV Mini acima de 300</fullName>
            </value>
            <value>
                <fullName>Bombeamento</fullName>
            </value>
            <value>
                <fullName>Estação de Recarga</fullName>
            </value>
            <value>
                <fullName>Subestação	Subestação</fullName>
            </value>
            <value>
                <fullName>Padrão de Entrada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ViabilityControllerTest.cls
/**
 * @description       :
 * @author            : Daniel Belini
 * @group             :
 * @last modified on  : 03-15-2026
 * @last modified by  : Daniel Belini
 * @test              : N/A - classe de teste executavel
 **/
@isTest
public class ViabilityControllerTest {
  @isTest
  static void updateViabilityTest() {
    ProposalCover__c proposalCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(),
      true
    );
    Parceiro__c parceiro = (Parceiro__c) TestFactory.createSObject(
      new Parceiro__c(CapaProposta__c = proposalCover.Id, Produto__c = 'Solar'),
      true
    );
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Consultor__c consultor = (Consultor__c) TestFactory.createSObject(
      new Consultor__c(),
      true
    );
    Opportunity opportunity = (Opportunity) TestFactory.createSObject(
      new Opportunity(
        AccountId = account.Id,
        ConsultorOportunidade__c = consultor.Id,
        Parceiro__c = parceiro.Id,
        PotenciaPicoSistema__c = 12
      ),
      true
    );
    ViabilityStudy__c viability = new ViabilityStudy__c(
      Opportunity__c = opportunity.Id,
      TypeWorkProjectFeasibility__c = 'UFV Mini acima de 300'
    );
    insert viability;

    Decimal latitude = -15.6131249;
    Decimal longitude = -56.0853574;
    String telhado = 'Ao Solo';

    Test.startTest();
    opportunity.StageName = OpportunityUtils.STATUS_ANALISE_DE_VIABILIDADE;
    update opportunity;
    ViabilityController.updateViability(
      viability.Id,
      latitude,
      longitude,
      telhado
    );
    Test.stopTest();

    ViabilityStudy__c updatedVia = [
      SELECT
        LocalizacaoFixa__Latitude__s,
        LocalizacaoFixa__Longitude__s,
        FixationStructureVerifiedPlace__c
      FROM ViabilityStudy__c
      WHERE Id = :viability.Id
    ];
    Assert.areEqual(
      latitude,
      updatedVia.LocalizacaoFixa__Latitude__s,
      'Latitude não foi atualizada corretamente'
    );
    Assert.areEqual(
      longitude,
      updatedVia.LocalizacaoFixa__Longitude__s,
      'Longitude não foi atualizada corretamente'
    );
    Assert.areEqual(
      telhado,
      updatedVia.FixationStructureVerifiedPlace__c,
      'telhado não foi atualizado corretamente'
    );
  }
}