force-app/main/default/objects/Account/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <referenceTo>Consultor__c</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IdExternoConsultor__c.field-meta.xml
<CustomField>
    <fullName>IdExternoConsultor__c</fullName>
    <description>Armazenar Id Externo do Consultor que será passado via integração, e usar para buscar por registro correspondente</description>
    <label>Id Externo do Consultor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <description>Campo Id no virtual office.</description>
    <externalId>true</externalId>
    <label>Id no Gerador de Oportunidades</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroIdentificacao__c.field-meta.xml
<CustomField>
    <fullName>NumeroIdentificacao__c</fullName>
    <label>Numero de Identificação</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SeCPFouCNPJ__c.field-meta.xml
<CustomField>
    <fullName>SeCPFouCNPJ__c</fullName>
    <description>Campo para pegar ou CPF ou CNPJ.</description>
    <formula>IF( CNPJ__c =null,SUBSTITUTE(SUBSTITUTE(CPF__c, &quot;-&quot;, null),&quot;.&quot;, null),
SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(CNPJ__c , &quot;-&quot;, null),&quot;.&quot;, null), &quot;/&quot;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SeCPFouCNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/Consultor__c.object-meta.xml
<CustomObject>
    <label>Consultor</label>
    <nameField>
        <label>Nome do Consultor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultor__c/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <description>Id do cliente gerado no app Virtual Office (fora do Salesforce)</description>
    <externalId>true</externalId>
    <label>Id no Gerador de Oportunidades</label>
    <length>90</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/NumeroIdentificacao__c.field-meta.xml
<CustomField>
    <fullName>NumeroIdentificacao__c</fullName>
    <externalId>true</externalId>
    <label>Numero de Identificação</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/SeCPFouCNPJ__c.field-meta.xml
<CustomField>
    <fullName>SeCPFouCNPJ__c</fullName>
    <description>Campo para pegar o valor de CPF ou CNPJ.</description>
    <formula>IF( CNPJ__c =null,SUBSTITUTE(SUBSTITUTE(CPF__c, &quot;-&quot;, null),&quot;.&quot;, null),
SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(CNPJ__c , &quot;-&quot;, null),&quot;.&quot;, null), &quot;/&quot;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SeCPFouCNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/recordTypes/Consultor.recordType-meta.xml
<RecordType>
    <fullName>Consultor</fullName>
    <active>true</active>
    <label>Consultor</label>
</RecordType>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
public class AccountTriggerTest {
  @TestSetup
  static void makeData() {
    Consultor__c seller = (Consultor__c) TestFactory.createSObject(
      new Consultor__c(),
      true
    );
  }

  @isTest
  static void assignSellerToIntegratedClientTest() {
    Consultor__c seller = [
      SELECT Id, IdVirtualOffice__c
      FROM Consultor__c
      WHERE
        RecordTypeID = :Schema.SObjectType.Consultor__c.getRecordTypeInfosByDeveloperName()
          .get('Consultor')
          .getRecordTypeId()
      LIMIT 1
    ];

    Account client = (Account) TestFactory.createSObject(
      new Account(IdExternoConsultor__c = seller.IdVirtualOffice__c),
      true
    );

    client = [
      SELECT Consultor__c
      FROM Account
      LIMIT 1
    ];
    System.assertEquals(seller.Id, client.Consultor__c);
  }

  @isTest
  static void assignCPFCNPJToIdentificationNumberTest() {
    Account account = (Account) TestFactory.createSObject(
      new Account(NumeroIdentificacao__c = null),
      true
    );

    account = [
      SELECT SeCPFouCNPJ__c, NumeroIdentificacao__c
      FROM Account
      WHERE Id = :account.Id
    ];

    System.assertEquals(account.SeCPFouCNPJ__c, account.NumeroIdentificacao__c);
  }

  @isTest
  static void coverageOtherTriggerMethods() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);

    account.Name = 'Teste 2';
    update account;

    delete account;

    AccountTriggerHandler.disableTrigger();
    System.assert(!AccountTriggerHandler.isTriggerEnabled());

    AccountTriggerHandler.enableTrigger();
    System.assert(AccountTriggerHandler.isTriggerEnabled());
  }
}