force-app/main/default/objects/Account/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <description>Campo Id no virtual office.</description>
    <externalId>true</externalId>
    <label>Id no Gerador de Oportunidades</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Parceiro.recordType-meta.xml
<RecordType>
    <fullName>Parceiro</fullName>
    <active>true</active>
    <description>Tipo de registro para parceiros franqueados.</description>
    <label>Parceiro</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/IsProposal__c.field-meta.xml
<CustomField>
    <fullName>IsProposal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>É uma proposta?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>IsTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/ProposalCoverKey__c.field-meta.xml
<CustomField>
    <fullName>ProposalCoverKey__c</fullName>
    <label>Proposal Cover Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/ProposalScenario__c.field-meta.xml
<CustomField>
    <fullName>ProposalScenario__c</fullName>
    <label>Proposal Scenario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INITIAL</fullName>
                <default>true</default>
                <label>Initial</label>
            </value>
            <value>
                <fullName>PAYMENT_SELECTED</fullName>
                <label>Payment Selected</label>
            </value>
            <value>
                <fullName>INITIAL_FINANCING</fullName>
                <label>Initial Financing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/ProposalTemplateRole__c.field-meta.xml
<CustomField>
    <fullName>ProposalTemplateRole__c</fullName>
    <label>Proposal Template Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API_PPTX_TEMPLATE</fullName>
                <default>true</default>
                <label>API PPTX Template</label>
            </value>
            <value>
                <fullName>LEGACY_LAYOUT</fullName>
                <label>Legacy Layout</label>
            </value>
            <value>
                <fullName>AUXILIARY_ASSET</fullName>
                <label>Auxiliary Asset</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/TipoKitPromocional__c.field-meta.xml
<CustomField>
    <fullName>TipoKitPromocional__c</fullName>
    <label>Tipo Kit Promocional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoKitPromocional</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <description>Campo para definir o sub-grupo tarifário.</description>
    <label>Grupo Tarifário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
            <value>
                <fullName>Grupo B Optante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id no virtual office</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isPromotional__c.field-meta.xml
<CustomField>
    <fullName>isPromotional__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promocional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NomeDaConta__c.field-meta.xml
<CustomField>
    <fullName>NomeDaConta__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome da Conta</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wemob</fullName>
            </value>
            <value>
                <fullName>Bateria</fullName>
            </value>
            <value>
                <fullName>Estacao de Recarga</fullName>
            </value>
            <value>
                <fullName>Modulos</fullName>
            </value>
            <value>
                <fullName>Inversores</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PropostaGerada__c.field-meta.xml
<CustomField>
    <fullName>PropostaGerada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar se proposta foi gerada, a partir do botão &quot;Gerar Proposta&quot; na tela de Oportunidade</description>
    <label>Proposta foi gerada?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SucessoIntegracaoNivello__c.field-meta.xml
<CustomField>
    <fullName>SucessoIntegracaoNivello__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar se houve sucesso na integração Nivello ao enviar dados.</description>
    <label>Sucesso na Integração Nivello</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoKitPromocional__c.field-meta.xml
<CustomField>
    <fullName>TipoKitPromocional__c</fullName>
    <label>Tipo Kit Promocional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoKitPromocional</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Solar</businessProcess>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/OpportunityAttachmentLink__c/OpportunityAttachmentLink__c.object-meta.xml
<CustomObject>
    <label>Anexo Externo da Oportunidade</label>
    <nameField>
        <label>Nome de OpportunityAttachmentLink</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anexos Externo da Oportunidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityAttachmentLink__c/fields/AttachmentURL__c.field-meta.xml
<CustomField>
    <fullName>AttachmentURL__c</fullName>
    <label>URL do Anexo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/OpportunityAttachmentLink__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Anexos Externo da Oportunidade</relationshipLabel>
    <relationshipName>Anexos_Externo_da_Oportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityAttachmentLink__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <label>Parceiro</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parceiro__c/fields/CapaPromocional__c.field-meta.xml
<CustomField>
    <fullName>CapaPromocional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capa Promocional</label>
    <referenceTo>ProposalCover__c</referenceTo>
    <relationshipLabel>Parceiros (Capa Promocional)</relationshipLabel>
    <relationshipName>Parceiros1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parceiro__c/fields/CapaProposta__c.field-meta.xml
<CustomField>
    <fullName>CapaProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capa de Proposta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ProposalCover__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProposalCover__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parceiro__c/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <label>Grupo Tarifário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parceiro__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ezee Livre</fullName>
            </value>
            <value>
                <fullName>Ezee Connect</fullName>
            </value>
            <value>
                <fullName>Ezee Solar</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Produtos</fullName>
            </value>
            <value>
                <fullName>Serviços</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/ProposalCover__c.object-meta.xml
<CustomObject>
    <label>Capa de Proposta</label>
    <nameField>
        <label>Nome de Capa de Proposta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capa de Propostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProposalCover__c/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <label>Grupo Tarifario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/IntegrationKey__c.field-meta.xml
<CustomField>
    <fullName>IntegrationKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Chave funcional que identifica o conjunto de tags e seções configuradas para esta capa no sistema de geração de propostas via API. Obrigatória quando &quot;URL do Template&quot; estiver preenchida. Valores conhecidos: GRUPO_B_PADRAO. Sem este campo, a geração via API falhará.</description>
    <externalId>true</externalId>
    <label>Integration Key</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/isPromotional__c.field-meta.xml
<CustomField>
    <fullName>isPromotional__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promocional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ModeloPropostaA</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaB</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaBowe</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaEzeeConnect</fullName>
            </value>
            <value>
                <fullName>WorkDeliveryReportPdf</fullName>
                <isActive>false</isActive>
                <label>WorkDeliveryReportPdf</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoKitPromocional.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>KITS MONOFÁSICOS</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>KITS TRIFÁSICOS</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>KITS MICRO</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>CAMPANHA WEG - FAST TRACK</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>KITS TRIFÁSICOS PROMO WEG</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>KIT SOLAR + BESS</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>KITS MONOFÁSICOS SEM WEGHOME</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>KITS MICRO SEM WEGHOME</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <masterLabel>Tipo Kit Promocional</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProposalConsoleControllerApiTest.cls
/**
 * @description       :
 * @author            : Daniel Belini
 * @group             :
 * @last modified on  : 04-10-2026
 * @last modified by  : Daniel Belini
 * @test              : N/A - classe de teste executavel
 **/
@isTest
private class ProposalConsoleControllerApiTest {
  private static final String COVER_KEY = 'API_GROUP_B_TEST';
  private static Integer proposalCallCount = 0;
  private static Integer nivelloCallCount = 0;

  @TestSetup
  static void setup() {
    Account account = (Account) TestFactory.createSObject(
      new Account(Name = 'Conta API Teste'),
      true
    );

    ProposalCover__c apiCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = 'Capa API Teste',
        GrupoTarifario__c = 'Grupo B',
        IntegrationKey__c = COVER_KEY,
        Template__c = 'ModeloPropostaA'
      ),
      true
    );

    Parceiro__c partner = (Parceiro__c) TestFactory.createSObject(
      new Parceiro__c(
        Name = 'Parceiro API Teste',
        Produto__c = 'Solar',
        GrupoTarifario__c = 'Grupo B',
        CapaProposta__c = apiCover.Id
      ),
      true
    );

    TestFactory.createSObject(
      new Opportunity(
        AccountId = account.Id,
        StageName = OpportunityUtils.STATUS_ELABORACAO_DE_PROPOSTA,
        Parceiro__c = partner.Id,
        GrupoTarifario__c = 'Grupo B',
        IdVirtualOffice__c = 'VO-API-001'
      ),
      true
    );

    insert new ContentVersion(
      Title = 'Template API Teste',
      PathOnClient = 'template-api-teste.pptx',
      VersionData = Blob.valueOf('pptx-template'),
      FirstPublishLocationId = apiCover.Id,
      IsTemplate__c = true,
      ProposalTemplateRole__c = 'API_PPTX_TEMPLATE'
    );
  }

  @isTest
  static void generatePreviewAndSendProposalReuseGeneratedFile() {
    Opportunity opportunityRecord = [
      SELECT Id, StageName, PropostaGerada__c
      FROM Opportunity
      WHERE IdVirtualOffice__c = 'VO-API-001'
      LIMIT 1
    ];
    ProposalCover__c cover = [
      SELECT Id
      FROM ProposalCover__c
      WHERE IntegrationKey__c = :COVER_KEY
      LIMIT 1
    ];

    configureApiMappings(COVER_KEY);
    resetCalloutCounters();
    Test.setMock(HttpCalloutMock.class, new ProposalApiAndNivelloMock());

    try {
      ProposalConsoleController.ProposalActionResult previewResult;
      ProposalConsoleController.ProposalActionResult sendResult;

      Test.startTest();
      previewResult = ProposalConsoleController.generatePreview(
        opportunityRecord.Id,
        cover.Id
      );
      sendResult = ProposalConsoleController.sendProposal(
        opportunityRecord.Id,
        cover.Id
      );
      Test.stopTest();

      Assert.isTrue(
        previewResult.success,
        'O preview deve ser gerado com sucesso.'
      );
      Assert.isNotNull(
        previewResult.contentVersionId,
        'O preview deve persistir um ContentVersion reutilizavel.'
      );
      Assert.isTrue(
        String.isNotBlank(previewResult.previewUrl),
        'O preview deve expor uma URL para o iframe.'
      );

      Assert.isTrue(
        sendResult.success,
        'O envio da proposta deve retornar sucesso.'
      );
      Assert.isTrue(
        sendResult.message != null &&
        sendResult.message.contains('envio para o aplicativo iniciado'),
        'O retorno do envio deve explicar que a integração roda em segundo plano.'
      );
      Assert.areEqual(
        previewResult.contentVersionId,
        sendResult.contentVersionId,
        'O envio deve reutilizar o mesmo arquivo gerado no preview.'
      );
      Assert.isTrue(
        sendResult.reusedExistingFile,
        'O fluxo de envio deve indicar que reutilizou o PDF existente.'
      );
      Assert.areEqual(
        1,
        proposalCallCount,
        'A API de conversao deve ser chamada apenas uma vez.'
      );
      Assert.areEqual(
        1,
        nivelloCallCount,
        'O envio ao aplicativo deve ocorrer uma vez.'
      );

      ContentVersion generatedVersion = [
        SELECT
          Id,
          FirstPublishLocationId,
          IsProposal__c,
          ProposalCoverKey__c,
          ProposalScenario__c
        FROM ContentVersion
        WHERE Id = :sendResult.contentVersionId
      ];
      Assert.areEqual(
        opportunityRecord.Id,
        generatedVersion.FirstPublishLocationId,
        'O PDF final precisa estar vinculado a oportunidade.'
      );
      Assert.isTrue(
        generatedVersion.IsProposal__c,
        'O arquivo gerado precisa ser marcado como proposta.'
      );
      Assert.areEqual(
        COVER_KEY,
        generatedVersion.ProposalCoverKey__c,
        'A auditoria do arquivo precisa guardar a chave da capa.'
      );
      Assert.areEqual(
        ProposalConfigurationService.SCENARIO_INITIAL,
        generatedVersion.ProposalScenario__c,
        'O preview inicial deve registrar o cenário correto.'
      );

      Opportunity updatedOpportunity = [
        SELECT PropostaGerada__c, StageName, SucessoIntegracaoNivello__c
        FROM Opportunity
        WHERE Id = :opportunityRecord.Id
      ];
      Assert.isTrue(
        updatedOpportunity.PropostaGerada__c,
        'A oportunidade deve ser marcada como proposta gerada.'
      );
      Assert.areEqual(
        OpportunityUtils.STATUS_PROPOSTA_GERADA,
        updatedOpportunity.StageName,
        'A oportunidade deve avançar para a fase esperada.'
      );
      Assert.isTrue(
        updatedOpportunity.SucessoIntegracaoNivello__c,
        'O envio ao app deve marcar sucesso na oportunidade.'
      );

      List<OpportunityAttachmentLink__c> attachmentLinks = [
        SELECT AttachmentURL__c, ExternalId__c, OpportunityId__c, Type__c
        FROM OpportunityAttachmentLink__c
        WHERE OpportunityId__c = :opportunityRecord.Id
        LIMIT 1
      ];
      if (!attachmentLinks.isEmpty()) {
        OpportunityAttachmentLink__c attachmentLink = attachmentLinks[0];
        Assert.areEqual(
          'https://example.com/proposta-api.pdf',
          attachmentLink.AttachmentURL__c,
          'A URL retornada pelo aplicativo deve ser persistida.'
        );
        Assert.areEqual(
          'ATT-001',
          attachmentLink.ExternalId__c,
          'O identificador externo deve ser guardado no link da proposta.'
        );
        Assert.areEqual(
          'Proposal',
          attachmentLink.Type__c,
          'O anexo externo deve ser classificado como proposta.'
        );
      }
    } finally {
      clearApiMappings();
    }
  }

  @isTest
  static void loadProposalDataUsesPromotionalCoverAsDefault() {
    Account account = new Account(
      Name = TestFactory.nextUniqueValue('ContaPromocional')
    );
    Database.DMLOptions accountOptions = new Database.DMLOptions();
    accountOptions.DuplicateRuleHeader.allowSave = true;
    account.setOptions(accountOptions);
    insert account;
    ProposalCover__c standardCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = TestFactory.nextUniqueValue('CapaPadrao'),
        GrupoTarifario__c = 'Grupo B',
        isPromotional__c = false
      ),
      true
    );
    ProposalCover__c promotionalCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = TestFactory.nextUniqueValue('CapaPromocional'),
        GrupoTarifario__c = 'Grupo B',
        isPromotional__c = true
      ),
      true
    );
    Parceiro__c partner = (Parceiro__c) TestFactory.createSObject(
      new Parceiro__c(
        Name = TestFactory.nextUniqueValue('ParceiroPromocional'),
        Produto__c = 'Solar',
        GrupoTarifario__c = 'Grupo B',
        CapaProposta__c = standardCover.Id,
        CapaPromocional__c = promotionalCover.Id
      ),
      true
    );
    Opportunity promotionalOpportunity = (Opportunity) TestFactory.createSObject(
      new Opportunity(
        AccountId = account.Id,
        StageName = OpportunityUtils.STATUS_ELABORACAO_DE_PROPOSTA,
        Parceiro__c = partner.Id,
        GrupoTarifario__c = 'Grupo B',
        isPromotional__c = true,
        TipoKitPromocional__c = '6'
      ),
      true
    );

    Test.startTest();
    ProposalConsoleController.ProposalDataDTO result = ProposalConsoleController.loadProposalData(
      promotionalOpportunity.Id
    );
    Test.stopTest();

    Assert.areEqual(
      promotionalCover.Id,
      result.defaultTemplateId,
      'O cover promocional deve ser o default quando a oportunidade for promocional.'
    );
    Assert.areEqual(
      2,
      result.templates.size(),
      'As duas capas ativas do parceiro devem ser exibidas.'
    );
  }

  @isTest
  static void loadProposalDataIgnoresPromotionalCoverWhenKitIsBlank() {
    Account account = new Account(
      Name = TestFactory.nextUniqueValue('ContaSemKit')
    );
    Database.DMLOptions accountOptions = new Database.DMLOptions();
    accountOptions.DuplicateRuleHeader.allowSave = true;
    account.setOptions(accountOptions);
    insert account;

    ProposalCover__c standardCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = TestFactory.nextUniqueValue('CapaPadraoSemKit'),
        GrupoTarifario__c = 'Grupo B',
        isPromotional__c = false
      ),
      true
    );
    ProposalCover__c promotionalCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = TestFactory.nextUniqueValue('CapaPromoSemKit'),
        GrupoTarifario__c = 'Grupo B',
        isPromotional__c = true
      ),
      true
    );
    Parceiro__c partner = (Parceiro__c) TestFactory.createSObject(
      new Parceiro__c(
        Name = TestFactory.nextUniqueValue('ParceiroSemKit'),
        Produto__c = 'Solar',
        GrupoTarifario__c = 'Grupo B',
        CapaProposta__c = standardCover.Id,
        CapaPromocional__c = promotionalCover.Id
      ),
      true
    );
    Opportunity opportunityWithoutKit = (Opportunity) TestFactory.createSObject(
      new Opportunity(
        AccountId = account.Id,
        StageName = OpportunityUtils.STATUS_ELABORACAO_DE_PROPOSTA,
        Parceiro__c = partner.Id,
        GrupoTarifario__c = 'Grupo B'
      ),
      true
    );

    update new Opportunity(
      Id = opportunityWithoutKit.Id,
      TipoKitPromocional__c = null,
      isPromotional__c = false
    );

    Test.startTest();
    ProposalConsoleController.ProposalDataDTO result = ProposalConsoleController.loadProposalData(
      opportunityWithoutKit.Id
    );
    Test.stopTest();

    Assert.areEqual(
      standardCover.Id,
      result.defaultTemplateId,
      'Sem kit promocional preenchido, a capa padrão deve continuar como default.'
    );
    Assert.areEqual(
      1,
      result.templates.size(),
      'Sem kit promocional preenchido, a capa promocional não deve ser exibida.'
    );
    Assert.areEqual(
      standardCover.Id,
      result.templates[0].id,
      'A única opção disponível deve ser a capa padrão.'
    );
  }

  @isTest
  static void generatePreviewFailsWhenApiTemplateConfigurationIsAmbiguous() {
    Opportunity opportunityRecord = [
      SELECT Id
      FROM Opportunity
      WHERE IdVirtualOffice__c = 'VO-API-001'
      LIMIT 1
    ];
    ProposalCover__c cover = [
      SELECT Id
      FROM ProposalCover__c
      WHERE IntegrationKey__c = :COVER_KEY
      LIMIT 1
    ];

    insert new ContentVersion(
      Title = 'Template API Duplicado',
      PathOnClient = 'template-api-duplicado.pptx',
      VersionData = Blob.valueOf('pptx-template-2'),
      FirstPublishLocationId = cover.Id,
      IsTemplate__c = true,
      ProposalTemplateRole__c = 'API_PPTX_TEMPLATE'
    );

    configureApiMappings(COVER_KEY);
    Test.setMock(HttpCalloutMock.class, new ProposalApiAndNivelloMock());

    try {
      Test.startTest();
      try {
        ProposalConsoleController.generatePreview(
          opportunityRecord.Id,
          cover.Id
        );
        Assert.fail(
          'A geração deveria falhar quando existir mais de um template válido.'
        );
      } catch (AuraHandledException handledException) {
        Assert.isTrue(
          String.isNotBlank(handledException.getMessage()),
          'O fluxo deve lançar uma exceção quando houver mais de um template válido.'
        );
      }
      Test.stopTest();
    } finally {
      clearApiMappings();
    }
  }

  @isTest
  static void generatePreviewUsesApiFallbackWhenLegacyTemplateIsMapped() {
    Account account = new Account(
      Name = TestFactory.nextUniqueValue('ContaFallbackApi')
    );
    Database.DMLOptions accountOptions = new Database.DMLOptions();
    accountOptions.DuplicateRuleHeader.allowSave = true;
    account.setOptions(accountOptions);
    insert account;

    ProposalCover__c mappedCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = TestFactory.nextUniqueValue('CapaFallbackApi'),
        GrupoTarifario__c = 'Grupo B',
        Template__c = 'ModeloPropostaB'
      ),
      true
    );

    Parceiro__c partner = (Parceiro__c) TestFactory.createSObject(
      new Parceiro__c(
        Name = TestFactory.nextUniqueValue('ParceiroFallbackApi'),
        Produto__c = 'Solar',
        GrupoTarifario__c = 'Grupo B',
        CapaProposta__c = mappedCover.Id
      ),
      true
    );

    Opportunity opportunityRecord = (Opportunity) TestFactory.createSObject(
      new Opportunity(
        AccountId = account.Id,
        StageName = OpportunityUtils.STATUS_ELABORACAO_DE_PROPOSTA,
        Parceiro__c = partner.Id,
        GrupoTarifario__c = 'Grupo B',
        IdVirtualOffice__c = TestFactory.nextUniqueValue('VO-FALLBACK')
      ),
      true
    );

    insert new ContentVersion(
      Title = 'Template Fallback API',
      PathOnClient = 'template-fallback-api.pptx',
      VersionData = Blob.valueOf('pptx-template-fallback'),
      FirstPublishLocationId = mappedCover.Id,
      IsTemplate__c = true,
      ProposalTemplateRole__c = 'API_PPTX_TEMPLATE'
    );

    configureApiMappings('GRUPO_B_PADRAO');
    resetCalloutCounters();
    Test.setMock(HttpCalloutMock.class, new ProposalApiAndNivelloMock());

    try {
      Test.startTest();
      ProposalConsoleController.ProposalActionResult result = ProposalConsoleController.generatePreview(
        opportunityRecord.Id,
        mappedCover.Id
      );
      Test.stopTest();

      Assert.isTrue(
        result.success,
        'A capa legada mapeada deve gerar preview usando a API.'
      );
      Assert.isTrue(
        String.isNotBlank(result.previewUrl),
        'O preview precisa retornar a URL do PDF gerado.'
      );
      Assert.areEqual(
        1,
        proposalCallCount,
        'A geração deve passar pela API quando o template legado estiver mapeado.'
      );
    } finally {
      clearApiMappings();
    }
  }

  private static void configureApiMappings(String coverKey) {
    ProposalConfigurationService.TagConfig tagConfig = new ProposalConfigurationService.TagConfig();
    tagConfig.coverKey = coverKey;
    tagConfig.tagKey = '{{NomeDaConta__c}}';
    tagConfig.sourcePath = 'Account.Name';
    tagConfig.scenario = ProposalConfigurationService.SCENARIO_INITIAL;
    tagConfig.required = true;
    tagConfig.sortOrder = 1;
    tagConfig.active = true;

    ProposalConfigurationService.setTestTagConfigs(
      new List<ProposalConfigurationService.TagConfig>{ tagConfig }
    );
    ProposalConfigurationService.setTestSectionsByKey(
      new Map<String, List<String>>{
        ProposalConfigurationService.SCENARIO_INITIAL => new List<String>{
          'Proposta'
        }
      }
    );
  }

  private static void clearApiMappings() {
    ProposalConfigurationService.setTestTagConfigs(null);
    ProposalConfigurationService.setTestSectionsByKey(null);
  }

  private static void resetCalloutCounters() {
    proposalCallCount = 0;
    nivelloCallCount = 0;
  }

  private class ProposalApiAndNivelloMock implements HttpCalloutMock {
    public HttpResponse respond(HttpRequest request) {
      HttpResponse response = new HttpResponse();
      String endpoint = request.getEndpoint();
      String requestBody = request.getBody();

      if (endpoint != null && endpoint.contains('/convertProposal')) {
        ProposalConsoleControllerApiTest.proposalCallCount++;
        response.setStatusCode(200);
        response.setHeader('Content-Type', 'application/json');
        response.setBody(
          '{"fileBase64":"' +
            EncodingUtil.base64Encode(Blob.valueOf('pdf-api-content')) +
            '","fileName":"proposta-api.pdf","mimeType":"application/pdf"}'
        );
        return response;
      }

      if (requestBody != null && requestBody.contains('"contract"')) {
        ProposalConsoleControllerApiTest.nivelloCallCount++;
      }
      response.setStatusCode(200);
      response.setHeader('Content-Type', 'application/json');
      response.setBody(
        '{"success":true,"data":{"id":"ATT-001","urlFile":"https://example.com/proposta-api.pdf"}}'
      );
      return response;
    }
  }
}