force-app/main/default/objects/Account/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <description>Campo Id no virtual office.</description>
    <externalId>true</externalId>
    <label>Id no Gerador de Oportunidades</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integrador__mdt/Integrador__mdt.object-meta.xml
<CustomObject>
    <description>Metadado para armazenar informações de Endpoints, login, senha</description>
    <label>Integração</label>
    <pluralLabel>Integradores</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id no virtual office</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/StatusViabilidade__c.field-meta.xml
<CustomField>
    <fullName>StatusViabilidade__c</fullName>
    <label>Status da Viabilidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Viável</fullName>
            </value>
            <value>
                <fullName>Inviável</fullName>
            </value>
            <value>
                <fullName>Parcialmente Viável</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TextoEstudo__c.field-meta.xml
<CustomField>
    <fullName>TextoEstudo__c</fullName>
    <inlineHelpText>Informe o campo texto de estudo com o resultado do estudo feito pelo técnico de campo, quando o status da viabilidade estiver parcialmente viável.</inlineHelpText>
    <label>Texto de Estudo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TextoMotivo__c.field-meta.xml
<CustomField>
    <fullName>TextoMotivo__c</fullName>
    <inlineHelpText>Informe o campo texto de motivo com o resultado do estudo feito pelo técnico de campo, quando o status da viabilidade estiver inviável.</inlineHelpText>
    <label>Texto de Motivo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/IntegracaoNivelloAnaliseVTTest.cls
@IsTest
private class IntegracaoNivelloAnaliseVTTest {
  @IsTest
  static void shouldSendVisitAnalysis() {
    if (
      !TestMetadataUtils.hasMetadataRecord(
        'Integrador__mdt',
        'AnaliseVisitaTecnica'
      )
    ) {
      return;
    }

    Account acc = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = (Opportunity) TestFactory.createSObject(
      new Opportunity(
        AccountId = acc.Id,
        IdVirtualOffice__c = 'VO-ANALISE',
        StatusViabilidade__c = 'Viável',
        TextoEstudo__c = 'Estudo',
        TextoMotivo__c = 'Motivo'
      ),
      true
    );

    TokenAPINivelloWs.access_token = 'token';
    Test.setMock(
      HttpCalloutMock.class,
      new TestMetadataUtils.MockHttpSuccess()
    );

    Test.startTest();
    IntegracaoNivelloAnaliseVisitaTecnica.sendTechnicalVisitAnalysis(
      new Set<Id>{ opp.Id }
    );
    Test.stopTest();

    System.assert(true, 'Integracao executada');
  }
}