force-app/main/default/objects/Account/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <description>Campo Id no virtual office.</description>
    <externalId>true</externalId>
    <label>Id no Gerador de Oportunidades</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/IsProposal__c.field-meta.xml
<CustomField>
    <fullName>IsProposal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>É uma proposta?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>IsTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/ProposalTemplateRole__c.field-meta.xml
<CustomField>
    <fullName>ProposalTemplateRole__c</fullName>
    <label>Proposal Template Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API_PPTX_TEMPLATE</fullName>
                <default>true</default>
                <label>API PPTX Template</label>
            </value>
            <value>
                <fullName>LEGACY_LAYOUT</fullName>
                <label>Legacy Layout</label>
            </value>
            <value>
                <fullName>AUXILIARY_ASSET</fullName>
                <label>Auxiliary Asset</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/TipoKitPromocional__c.field-meta.xml
<CustomField>
    <fullName>TipoKitPromocional__c</fullName>
    <label>Tipo Kit Promocional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoKitPromocional</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <description>Campo para definir o sub-grupo tarifário.</description>
    <label>Grupo Tarifário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
            <value>
                <fullName>Grupo B Optante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id no virtual office</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isPromotional__c.field-meta.xml
<CustomField>
    <fullName>isPromotional__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promocional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wemob</fullName>
            </value>
            <value>
                <fullName>Bateria</fullName>
            </value>
            <value>
                <fullName>Estacao de Recarga</fullName>
            </value>
            <value>
                <fullName>Modulos</fullName>
            </value>
            <value>
                <fullName>Inversores</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SelectedSimulation__c.field-meta.xml
<CustomField>
    <fullName>SelectedSimulation__c</fullName>
    <label>Simulação Selecionada</label>
    <referenceTo>PaymentSimulation__c</referenceTo>
    <relationshipLabel>Oportunidade (Simulação Selecionada)</relationshipLabel>
    <relationshipName>SelectedForOpportunity</relationshipName>
    <type>Lookup</type>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PaymentSimulation__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
</CustomField>

force-app/main/default/objects/Opportunity/fields/StatusBodyIntegracaoNivello__c.field-meta.xml
<CustomField>
    <fullName>StatusBodyIntegracaoNivello__c</fullName>
    <description>Status Code e Body do retorno da integração Nivello</description>
    <label>Status e Body Integração Nivello</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SucessoIntegracaoNivello__c.field-meta.xml
<CustomField>
    <fullName>SucessoIntegracaoNivello__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar se houve sucesso na integração Nivello ao enviar dados.</description>
    <label>Sucesso na Integração Nivello</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoKitPromocional__c.field-meta.xml
<CustomField>
    <fullName>TipoKitPromocional__c</fullName>
    <label>Tipo Kit Promocional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoKitPromocional</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Solar</businessProcess>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <label>Parceiro</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parceiro__c/fields/CapaProposta__c.field-meta.xml
<CustomField>
    <fullName>CapaProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capa de Proposta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ProposalCover__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProposalCover__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parceiro__c/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <label>Grupo Tarifário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parceiro__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ezee Livre</fullName>
            </value>
            <value>
                <fullName>Ezee Connect</fullName>
            </value>
            <value>
                <fullName>Ezee Solar</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Produtos</fullName>
            </value>
            <value>
                <fullName>Serviços</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentSimulation__c/PaymentSimulation__c.object-meta.xml
<CustomObject>
    <label>Simulação de Pagamento</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Número da Simulação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulações de Pagamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentSimulation__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Tipo de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Financing</fullName>
            </value>
            <value>
                <fullName>ManualFinancing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/ProposalCover__c.object-meta.xml
<CustomObject>
    <label>Capa de Proposta</label>
    <nameField>
        <label>Nome de Capa de Proposta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capa de Propostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProposalCover__c/fields/GrupoTarifario__c.field-meta.xml
<CustomField>
    <fullName>GrupoTarifario__c</fullName>
    <label>Grupo Tarifario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grupo A</fullName>
            </value>
            <value>
                <fullName>Grupo B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/IntegrationKey__c.field-meta.xml
<CustomField>
    <fullName>IntegrationKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Chave funcional que identifica o conjunto de tags e seções configuradas para esta capa no sistema de geração de propostas via API. Obrigatória quando &quot;URL do Template&quot; estiver preenchida. Valores conhecidos: GRUPO_B_PADRAO. Sem este campo, a geração via API falhará.</description>
    <externalId>true</externalId>
    <label>Integration Key</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/isPromotional__c.field-meta.xml
<CustomField>
    <fullName>isPromotional__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promocional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProposalCover__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ModeloPropostaA</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaB</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaBowe</fullName>
            </value>
            <value>
                <fullName>ModeloPropostaEzeeConnect</fullName>
            </value>
            <value>
                <fullName>WorkDeliveryReportPdf</fullName>
                <isActive>false</isActive>
                <label>WorkDeliveryReportPdf</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoKitPromocional.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>KITS MONOFÁSICOS</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>KITS TRIFÁSICOS</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>KITS MICRO</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>CAMPANHA WEG - FAST TRACK</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>KITS TRIFÁSICOS PROMO WEG</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>KIT SOLAR + BESS</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>KITS MONOFÁSICOS SEM WEGHOME</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>KITS MICRO SEM WEGHOME</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <masterLabel>Tipo Kit Promocional</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProposalEngineSupportTest.cls
/**
 * @description       :
 * @author            : Daniel Belini
 * @group             :
 * @last modified on  : 04-10-2026
 * @last modified by  : Daniel Belini
 * @test              : N/A - classe de teste executavel
 **/
@isTest
private class ProposalEngineSupportTest {
  private static final String COVER_KEY = 'API_ENGINE_SUPPORT';
  private static String apiMockMode = 'BASE64';

  @TestSetup
  static void setup() {
    Account account = new Account(
      Name = TestFactory.nextUniqueValue('ContaEngine')
    );
    Database.DMLOptions accountOptions = new Database.DMLOptions();
    accountOptions.DuplicateRuleHeader.allowSave = true;
    account.setOptions(accountOptions);
    insert account;

    ProposalCover__c apiCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = TestFactory.nextUniqueValue('CapaEngine'),
        GrupoTarifario__c = 'Grupo B',
        IntegrationKey__c = COVER_KEY,
        Template__c = 'ModeloPropostaA'
      ),
      true
    );

    Parceiro__c partner = (Parceiro__c) TestFactory.createSObject(
      new Parceiro__c(
        Name = TestFactory.nextUniqueValue('ParceiroEngine'),
        Produto__c = 'Solar',
        GrupoTarifario__c = 'Grupo B',
        CapaProposta__c = apiCover.Id
      ),
      true
    );

    insert new Opportunity(
      AccountId = account.Id,
      Name = TestFactory.nextUniqueValue('OpportunityEngine'),
      StageName = OpportunityUtils.STATUS_ELABORACAO_DE_PROPOSTA,
      CloseDate = Date.today(),
      Parceiro__c = partner.Id,
      GrupoTarifario__c = 'Grupo B',
      Amount = 123.45,
      IdVirtualOffice__c = 'VO-ENGINE-001'
    );

    insert new ContentVersion(
      Title = 'Template Engine',
      PathOnClient = 'template-engine.pptx',
      VersionData = Blob.valueOf('pptx-engine'),
      FirstPublishLocationId = apiCover.Id,
      IsTemplate__c = true,
      ProposalTemplateRole__c = 'API_PPTX_TEMPLATE'
    );
  }

  @isTest
  static void configurationServiceReturnsExactAndFallbackRules() {
    ProposalConfigurationService.TagConfig genericTag = new ProposalConfigurationService.TagConfig();
    genericTag.coverKey = COVER_KEY;
    genericTag.tagKey = '{{AccountName}}';
    genericTag.sourcePath = 'Account.Name';
    genericTag.scenario = ProposalConfigurationService.SCENARIO_ALL;
    genericTag.sortOrder = 2;
    genericTag.active = true;

    ProposalConfigurationService.TagConfig paymentTag = new ProposalConfigurationService.TagConfig();
    paymentTag.coverKey = COVER_KEY;
    paymentTag.tagKey = '{{PaymentType}}';
    paymentTag.sourcePath = 'SelectedSimulation__r.PaymentType__c';
    paymentTag.scenario = ProposalConfigurationService.SCENARIO_PAYMENT_SELECTED;
    paymentTag.paymentType = 'FINANCING';
    paymentTag.sortOrder = 1;
    paymentTag.active = true;

    ProposalConfigurationService.setTestTagConfigs(
      new List<ProposalConfigurationService.TagConfig>{ genericTag, paymentTag }
    );
    ProposalConfigurationService.setTestSectionsByKey(
      new Map<String, List<String>>{
        ProposalConfigurationService.SCENARIO_INITIAL => new List<String>{
          'Proposta'
        },
        'Financing' => new List<String>{ 'Valor Financiamento' }
      }
    );

    try {
      List<ProposalConfigurationService.TagConfig> genericTags = ProposalConfigurationService.getTagConfigs(
        COVER_KEY,
        ProposalConfigurationService.SCENARIO_INITIAL,
        null
      );
      Assert.areEqual(
        1,
        genericTags.size(),
        'Deve retornar apenas a tag genérica.'
      );
      Assert.areEqual(
        '{{AccountName}}',
        genericTags[0].tagKey,
        'A tag genérica deve permanecer disponível no cenário inicial.'
      );

      List<String> paymentSections = ProposalConfigurationService.getSectionsToShow(
        COVER_KEY,
        ProposalConfigurationService.SCENARIO_PAYMENT_SELECTED,
        'Financing'
      );
      Assert.areEqual(
        1,
        paymentSections.size(),
        'O cenário com tipo de pagamento específico deve preferir a configuração exata.'
      );
      Assert.areEqual(
        'Valor Financiamento',
        paymentSections[0],
        'A section específica do financiamento deve ser selecionada.'
      );
    } finally {
      ProposalConfigurationService.setTestTagConfigs(null);
      ProposalConfigurationService.setTestSectionsByKey(null);
    }
  }

  @isTest
  static void determineIsPromotionalDependsOnTipoKitPromocional() {
    Assert.isFalse(
      ProposalContextResolver.determineIsPromotional(null),
      'O helper deve retornar falso quando a oportunidade não for informada.'
    );

    Opportunity opportunityRecord = new Opportunity(
      isPromotional__c = true,
      TipoKitPromocional__c = null
    );

    Assert.isFalse(
      ProposalContextResolver.determineIsPromotional(opportunityRecord),
      'Sem TipoKitPromocional preenchido, a oportunidade não deve ser tratada como promocional.'
    );

    opportunityRecord.TipoKitPromocional__c = '6';

    Assert.isTrue(
      ProposalContextResolver.determineIsPromotional(opportunityRecord),
      'Com TipoKitPromocional preenchido, a oportunidade deve ser tratada como promocional.'
    );

    Assert.areEqual(
      'GRUPO_B_PADRAO',
      ProposalCoverRoutingService.resolveCoverKey(
        new ProposalCover__c(
          Template__c = 'ModeloPropostaB',
          isPromotional__c = false
        )
      ),
      'A capa padrão ModeloPropostaB não promocional deve ser redirecionada para a chave da API.'
    );
    Assert.isTrue(
      ProposalCoverRoutingService.usesApiFlow(
        new ProposalCover__c(
          Template__c = 'ModeloPropostaB',
          isPromotional__c = false
        )
      ),
      'O fluxo deve reconhecer a capa padrão ModeloPropostaB como elegível para a API.'
    );
    Assert.areEqual(
      'CHAVE_EXPLICITA',
      ProposalCoverRoutingService.resolveCoverKey(
        new ProposalCover__c(IntegrationKey__c = 'CHAVE_EXPLICITA')
      ),
      'Quando existir IntegrationKey explícita ela deve ter prioridade.'
    );
    Assert.areEqual(
      null,
      ProposalCoverRoutingService.resolveCoverKey(
        new ProposalCover__c(
          Template__c = 'ModeloPropostaB',
          isPromotional__c = true
        )
      ),
      'A capa promocional não deve usar o fallback da capa padrão.'
    );
  }

  @isTest
  static void contextResolverValidatesRequiredIdsAndInactiveCover() {
    Opportunity opportunityRecord = [
      SELECT Id
      FROM Opportunity
      WHERE IdVirtualOffice__c = 'VO-ENGINE-001'
      LIMIT 1
    ];

    try {
      ProposalContextResolver.resolve(null, null);
      Assert.fail('Os identificadores obrigatórios deveriam ser validados.');
    } catch (AuraHandledException handledException) {
      Assert.isTrue(
        String.isNotBlank(handledException.getMessage()),
        'A validação precisa retornar uma mensagem de erro.'
      );
    }

    ProposalCover__c inactiveCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = TestFactory.nextUniqueValue('CapaInativa'),
        GrupoTarifario__c = 'Grupo B',
        IsActive__c = false,
        IntegrationKey__c = TestFactory.nextUniqueValue('COVER_INACTIVE')
      ),
      true
    );

    try {
      ProposalContextResolver.resolve(opportunityRecord.Id, inactiveCover.Id);
      Assert.fail('Capas inativas não podem ser resolvidas.');
    } catch (AuraHandledException handledException) {
      Assert.isTrue(
        String.isNotBlank(handledException.getMessage()),
        'A validação da capa inativa precisa retornar uma mensagem de erro.'
      );
    }
  }

  @isTest
  static void payloadBuilderFormatsValuesAndValidatesRequiredFields() {
    Opportunity opportunityRecord = [
      SELECT Id
      FROM Opportunity
      WHERE IdVirtualOffice__c = 'VO-ENGINE-001'
      LIMIT 1
    ];
    ProposalCover__c cover = [
      SELECT Id
      FROM ProposalCover__c
      WHERE IntegrationKey__c = :COVER_KEY
      LIMIT 1
    ];
    ProposalContextResolver.Context context = ProposalContextResolver.resolve(
      opportunityRecord.Id,
      cover.Id
    );

    ProposalConfigurationService.TagConfig accountTag = new ProposalConfigurationService.TagConfig();
    accountTag.tagKey = '{{AccountName}}';
    accountTag.sourcePath = 'Account.Name';
    accountTag.formatValue = 'UPPER';

    ProposalConfigurationService.TagConfig amountTag = new ProposalConfigurationService.TagConfig();
    amountTag.tagKey = '{{Amount}}';
    amountTag.sourcePath = 'Amount';
    amountTag.formatValue = 'CURRENCY_BR';

    ProposalConfigurationService.TagConfig dateTag = new ProposalConfigurationService.TagConfig();
    dateTag.tagKey = '{{CloseDate}}';
    dateTag.sourcePath = 'CloseDate';
    dateTag.formatValue = 'DATE_BR';

    List<ProposalConfigurationService.TagConfig> configs = new List<ProposalConfigurationService.TagConfig>{
      accountTag,
      amountTag,
      dateTag
    };

    Opportunity queriedOpportunity = ProposalPayloadBuilder.queryOpportunityForTags(
      opportunityRecord.Id,
      configs
    );
    ProposalPayloadBuilder.Payload payload = ProposalPayloadBuilder.buildPayload(
      context,
      queriedOpportunity,
      configs,
      new List<String>{ 'Proposta', 'Rodape' },
      '068000000000001AAA'
    );

    Assert.areEqual(
      'CONTAENGINE',
      payload.tags.get('{{AccountName}}').left(11),
      'O payload deve aplicar o formato UPPER.'
    );
    Assert.areEqual(
      '123,45',
      payload.tags.get('{{Amount}}'),
      'O payload deve aplicar formatação monetária pt-BR.'
    );
    Assert.isTrue(
      payload.tags.get('{{CloseDate}}').contains('/'),
      'A data deve ser formatada em dd/MM/yyyy.'
    );
    Assert.isTrue(
      String.isNotBlank(payload.payloadHash),
      'O hash do payload deve ser calculado.'
    );

    ProposalConfigurationService.TagConfig requiredTag = new ProposalConfigurationService.TagConfig();
    requiredTag.tagKey = '{{Missing}}';
    requiredTag.sourcePath = 'Description';
    requiredTag.required = true;

    try {
      ProposalPayloadBuilder.buildPayload(
        context,
        ProposalPayloadBuilder.queryOpportunityForTags(
          opportunityRecord.Id,
          new List<ProposalConfigurationService.TagConfig>{ requiredTag }
        ),
        new List<ProposalConfigurationService.TagConfig>{ requiredTag },
        new List<String>{ 'Proposta' },
        '068000000000001AAA'
      );
      Assert.fail('A tag obrigatória sem valor deveria lançar exceção.');
    } catch (AuraHandledException handledException) {
      Assert.isTrue(
        String.isNotBlank(handledException.getMessage()),
        'A exceção deve retornar uma mensagem de validação.'
      );
    }
  }

  @isTest
  static void fileServiceSavesAndFindsProposal() {
    Opportunity opportunityRecord = [
      SELECT Id
      FROM Opportunity
      WHERE IdVirtualOffice__c = 'VO-ENGINE-001'
      LIMIT 1
    ];
    ProposalCover__c cover = [
      SELECT Id
      FROM ProposalCover__c
      WHERE IntegrationKey__c = :COVER_KEY
      LIMIT 1
    ];
    ProposalContextResolver.Context context = ProposalContextResolver.resolve(
      opportunityRecord.Id,
      cover.Id
    );

    ProposalApiClient.ApiResponse response = new ProposalApiClient.ApiResponse();
    response.fileBlob = Blob.valueOf('pdf-engine');
    response.fileName = null;
    response.mimeType = 'application/pdf';

    Test.startTest();
    Id contentVersionId = ProposalFileService.saveGeneratedProposal(
      context,
      response,
      'HASH-001'
    );
    Test.stopTest();

    Assert.isNotNull(contentVersionId, 'O arquivo gerado deve ser salvo.');
    Assert.isNotNull(
      ProposalFileService.findExistingProposal(
        opportunityRecord.Id,
        'HASH-001'
      ),
      'O serviço deve localizar a proposta já existente pelo hash.'
    );
    Assert.isTrue(
      ProposalFileService.buildPreviewUrl(contentVersionId)
        .contains(String.valueOf(contentVersionId)),
      'A URL de preview deve usar o identificador da versão.'
    );
  }

  @isTest
  static void fileServiceHandlesLatestLookupAndCustomFileNames() {
    Opportunity opportunityRecord = [
      SELECT Id
      FROM Opportunity
      WHERE IdVirtualOffice__c = 'VO-ENGINE-001'
      LIMIT 1
    ];
    ProposalCover__c cover = [
      SELECT Id
      FROM ProposalCover__c
      WHERE IntegrationKey__c = :COVER_KEY
      LIMIT 1
    ];
    ProposalContextResolver.Context context = ProposalContextResolver.resolve(
      opportunityRecord.Id,
      cover.Id
    );

    ProposalApiClient.ApiResponse response = new ProposalApiClient.ApiResponse();
    response.fileBlob = Blob.valueOf('pdf-custom');
    response.fileName = 'arquivo-personalizado';
    response.mimeType = 'application/pdf';

    Id contentVersionId = ProposalFileService.saveGeneratedProposal(
      context,
      response,
      'HASH-LATEST-001'
    );

    ContentVersion latestProposal = ProposalFileService.findLatestProposal(
      opportunityRecord.Id
    );
    Assert.areEqual(
      contentVersionId,
      latestProposal.Id,
      'A busca da proposta mais recente deve retornar o último PDF salvo.'
    );
    Assert.areEqual(
      null,
      ProposalFileService.findLatestProposal(null),
      'Sem oportunidade informada, não deve existir proposta mais recente.'
    );
    Assert.areEqual(
      null,
      ProposalFileService.findExistingProposal(null, 'HASH'),
      'Sem oportunidade informada, a busca por hash deve retornar nulo.'
    );
    Assert.areEqual(
      null,
      ProposalFileService.findExistingProposal(opportunityRecord.Id, null),
      'Sem hash informado, a busca por hash deve retornar nulo.'
    );
    Assert.areEqual(
      null,
      ProposalFileService.buildPreviewUrl(null),
      'Sem versão informada, a URL de preview deve ser nula.'
    );

    ContentVersion savedVersion = [
      SELECT Title, PathOnClient
      FROM ContentVersion
      WHERE Id = :contentVersionId
    ];
    Assert.areEqual(
      'arquivo-personalizado.pdf',
      savedVersion.PathOnClient,
      'O nome do arquivo sugerido pela API deve ser normalizado para PDF.'
    );
    Assert.areEqual(
      'arquivo-personalizado',
      savedVersion.Title,
      'O título salvo não deve repetir a extensão do PDF.'
    );
  }

  @isTest
  static void templateResolverUsesSinglePptxAttachedToStandardCover() {
    Account account = new Account(
      Name = TestFactory.nextUniqueValue('ContaTemplateUnico')
    );
    Database.DMLOptions accountOptions = new Database.DMLOptions();
    accountOptions.DuplicateRuleHeader.allowSave = true;
    account.setOptions(accountOptions);
    insert account;

    ProposalCover__c cover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = TestFactory.nextUniqueValue('CapaTemplateUnico'),
        GrupoTarifario__c = 'Grupo B',
        Template__c = 'ModeloPropostaB',
        isPromotional__c = false
      ),
      true
    );

    Parceiro__c partner = (Parceiro__c) TestFactory.createSObject(
      new Parceiro__c(
        Name = TestFactory.nextUniqueValue('ParceiroTemplateUnico'),
        Produto__c = 'Solar',
        GrupoTarifario__c = 'Grupo B',
        CapaProposta__c = cover.Id
      ),
      true
    );

    Opportunity opportunityRecord = (Opportunity) TestFactory.createSObject(
      new Opportunity(
        AccountId = account.Id,
        StageName = OpportunityUtils.STATUS_ELABORACAO_DE_PROPOSTA,
        Parceiro__c = partner.Id,
        GrupoTarifario__c = 'Grupo B',
        IdVirtualOffice__c = TestFactory.nextUniqueValue('VO-SINGLE-PPTX')
      ),
      true
    );

    insert new ContentVersion(
      Title = 'Template Unico',
      PathOnClient = 'template-unico.pptx',
      VersionData = Blob.valueOf('pptx-single-template'),
      FirstPublishLocationId = cover.Id,
      IsTemplate__c = true,
      TipoKitPromocional__c = '6'
    );

    ProposalContextResolver.Context context = ProposalContextResolver.resolve(
      opportunityRecord.Id,
      cover.Id
    );
    ContentVersion resolvedTemplate = ProposalTemplateResolver.resolveTemplate(
      context
    );

    Assert.areEqual(
      'Template Unico',
      resolvedTemplate.Title,
      'Quando existir apenas um PPTX anexado, ele deve ser utilizado diretamente.'
    );
  }

  @isTest
  static void templateResolverValidatesContext() {
    try {
      ProposalTemplateResolver.resolveTemplate(null);
      Assert.fail('O resolver deveria validar o contexto obrigatório.');
    } catch (AuraHandledException handledException) {
      Assert.isTrue(
        String.isNotBlank(handledException.getMessage()),
        'A validação de contexto inválido deve retornar uma mensagem de erro.'
      );
    }
  }

  @isTest
  static void apiClientSupportsBase64UrlAndPdfResponses() {
    ContentVersion templateVersion = [
      SELECT Id, Title, PathOnClient, FileExtension, VersionData
      FROM ContentVersion
      WHERE ProposalTemplateRole__c = 'API_PPTX_TEMPLATE'
      LIMIT 1
    ];

    Test.setMock(HttpCalloutMock.class, new ProposalApiClientMock());

    apiMockMode = 'BASE64';
    ProposalApiClient.ApiResponse base64Response;
    Test.startTest();
    base64Response = ProposalApiClient.convertProposal(
      templateVersion,
      '{"a":"b"}',
      '["Proposta"]'
    );
    Test.stopTest();
    Assert.areEqual(
      'base64.pdf',
      base64Response.fileName,
      'O cliente deve ler o arquivo retornado em base64.'
    );

    apiMockMode = 'URL';
    ProposalApiClient.ApiResponse urlResponse = ProposalApiClient.convertProposal(
      templateVersion,
      '{"a":"b"}',
      '["Proposta"]'
    );
    Assert.isTrue(
      urlResponse.fileBlob.size() > 0,
      'O cliente deve baixar o PDF quando a API retornar urlFile.'
    );

    apiMockMode = 'PDF';
    ProposalApiClient.ApiResponse pdfResponse = ProposalApiClient.convertProposal(
      templateVersion,
      '{"a":"b"}',
      '["Proposta"]'
    );
    Assert.areEqual(
      'Template Engine.pdf',
      pdfResponse.fileName,
      'Quando a API responder com PDF cru, o fallback deve usar o título do template.'
    );
  }

  @isTest
  static void integracaoNivelloHandlesEmptyAndExplicitProposal() {
    Opportunity opportunityRecord = [
      SELECT Id, SucessoIntegracaoNivello__c
      FROM Opportunity
      WHERE IdVirtualOffice__c = 'VO-ENGINE-001'
      LIMIT 1
    ];

    IntegracaoNivelloProposta.ProposalIntegrationResult emptyResult = IntegracaoNivelloProposta.gerandoPropostaSincrona(
      opportunityRecord.Id,
      null
    );
    Assert.isTrue(
      emptyResult.success == false,
      'Sem arquivo de proposta o serviço deve indicar falha controlada.'
    );

    ContentVersion proposalVersion = new ContentVersion(
      Title = 'Proposta Engine',
      PathOnClient = 'proposta-engine.pdf',
      VersionData = Blob.valueOf('pdf'),
      FirstPublishLocationId = opportunityRecord.Id,
      IsProposal__c = true
    );
    insert proposalVersion;

    Test.setMock(HttpCalloutMock.class, new ProposalApiClientMock());
    apiMockMode = 'NIVELLO_ROOT';

    Test.startTest();
    IntegracaoNivelloProposta.ProposalIntegrationResult successResult = IntegracaoNivelloProposta.gerandoPropostaSincrona(
      opportunityRecord.Id,
      proposalVersion.Id
    );
    Test.stopTest();

    Assert.isTrue(
      successResult.success,
      'A integração deve aceitar o arquivo explícito.'
    );
    Opportunity updatedOpportunity = [
      SELECT SucessoIntegracaoNivello__c, StatusBodyIntegracaoNivello__c
      FROM Opportunity
      WHERE Id = :opportunityRecord.Id
    ];
    Assert.isTrue(
      updatedOpportunity.SucessoIntegracaoNivello__c,
      'A oportunidade deve registrar sucesso na integração.'
    );
    Assert.isTrue(
      String.isNotBlank(updatedOpportunity.StatusBodyIntegracaoNivello__c),
      'O corpo da resposta precisa ser auditado na oportunidade.'
    );
  }

  @isTest
  static void proposalConsoleReturnsLegacyPreviewUrl() {
    Opportunity opportunityRecord = [
      SELECT Id
      FROM Opportunity
      WHERE IdVirtualOffice__c = 'VO-ENGINE-001'
      LIMIT 1
    ];

    ProposalCover__c legacyCover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(
        Name = TestFactory.nextUniqueValue('CapaLegacy'),
        GrupoTarifario__c = 'Grupo B',
        Template__c = 'ModeloPropostaA'
      ),
      true
    );

    ProposalConsoleController.ProposalActionResult result = ProposalConsoleController.generatePreview(
      opportunityRecord.Id,
      legacyCover.Id
    );
    Assert.isTrue(
      result.success,
      'O preview legado deve continuar disponível.'
    );
    Assert.isTrue(
      result.previewUrl.contains('/apex/ModeloPropostaA'),
      'A URL do preview legado deve continuar apontando para a Visualforce.'
    );
  }

  private class ProposalApiClientMock implements HttpCalloutMock {
    public HttpResponse respond(HttpRequest request) {
      HttpResponse response = new HttpResponse();
      String endpoint = request.getEndpoint();

      if (endpoint != null && endpoint.contains('/download/url-file.pdf')) {
        response.setStatusCode(200);
        response.setHeader('Content-Type', 'application/pdf');
        response.setBodyAsBlob(Blob.valueOf('downloaded-pdf'));
        return response;
      }

      if (apiMockMode == 'BASE64') {
        response.setStatusCode(200);
        response.setHeader('Content-Type', 'application/json');
        response.setBody(
          '{"fileBase64":"' +
            EncodingUtil.base64Encode(Blob.valueOf('pdf-base64')) +
            '","fileName":"base64.pdf","mimeType":"application/pdf"}'
        );
        return response;
      }

      if (apiMockMode == 'URL') {
        response.setStatusCode(200);
        response.setHeader('Content-Type', 'application/json');
        response.setBody(
          '{"data":{"urlFile":"https://example.com/download/url-file.pdf","fileName":"url-file.pdf"}}'
        );
        return response;
      }

      if (apiMockMode == 'PDF') {
        response.setStatusCode(200);
        response.setHeader('Content-Type', 'application/pdf');
        response.setBodyAsBlob(Blob.valueOf('raw-pdf'));
        return response;
      }

      response.setStatusCode(200);
      response.setHeader('Content-Type', 'application/json');
      response.setBody(
        '{"success":true,"id":"ROOT-1","urlFile":"https://example.com/proposta-root.pdf"}'
      );
      return response;
    }
  }
}