force-app/main/default/objects/Account/fields/MunicipioInstalacao__c.field-meta.xml
<CustomField>
    <fullName>MunicipioInstalacao__c</fullName>
    <label>Município de Instalação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Parceiro.recordType-meta.xml
<RecordType>
    <fullName>Parceiro</fullName>
    <active>true</active>
    <description>Tipo de registro para parceiros franqueados.</description>
    <label>Parceiro</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/MunicipioInstalacao__c.field-meta.xml
<CustomField>
    <fullName>MunicipioInstalacao__c</fullName>
    <description>Campo para definição de Município da Oportunidade.</description>
    <label>Município Instalação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wemob</fullName>
            </value>
            <value>
                <fullName>Bateria</fullName>
            </value>
            <value>
                <fullName>Estacao de Recarga</fullName>
            </value>
            <value>
                <fullName>Modulos</fullName>
            </value>
            <value>
                <fullName>Inversores</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResponsavelVisita__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelVisita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para associar o responsável pela visita técnica a oportunidade.</description>
    <label>Responsável pela Visita</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Solar</businessProcess>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <label>Parceiro</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parceiro__c/fields/CapaProposta__c.field-meta.xml
<CustomField>
    <fullName>CapaProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capa de Proposta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ProposalCover__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProposalCover__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parceiro__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ezee Livre</fullName>
            </value>
            <value>
                <fullName>Ezee Connect</fullName>
            </value>
            <value>
                <fullName>Ezee Solar</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Produtos</fullName>
            </value>
            <value>
                <fullName>Serviços</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProposalCover__c/ProposalCover__c.object-meta.xml
<CustomObject>
    <label>Capa de Proposta</label>
    <nameField>
        <label>Nome de Capa de Proposta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capa de Propostas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceAppointment/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compromissos de serviços</relationshipLabel>
    <relationshipName>CompromissosServico</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/ResponsavelVisita__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelVisita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para associar o responsável pela visita ao compromisso.</description>
    <label>Responsável pela Visita</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Compromissos de serviços</relationshipLabel>
    <relationshipName>Compromissos_de_servicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssignedResourceTriggerTest.cls
@isTest
public class AssignedResourceTriggerTest {
    @TestSetup
    static void makeData(){
        Account account = (Account) TestFactory.createSObject(new Account(), true);
        ProposalCover__c ProposalCover = (ProposalCover__c) TestFactory.createSObject(new ProposalCover__c(), true);
        Parceiro__c parceiro = (Parceiro__c) TestFactory.createSObject(new Parceiro__c(
            CapaProposta__c = ProposalCover.id,
            Produto__c = 'Solar'
        ), true);

        Opportunity opportunity = (Opportunity) TestFactory.createSObject(new Opportunity(
            AccountId                = account.id,
            MunicipioInstalacao__c   = 'São Paulo',
            Parceiro__c = parceiro.id
        ), true);

        OperatingHours operatingHours = (OperatingHours) TestFactory.createSObject(new OperatingHours(), true);
        
        SchedulingConstraint constraint = (SchedulingConstraint) TestFactory.createSObject(new SchedulingConstraint(), true);

        ServiceTerritory serviceTerritory = (ServiceTerritory) TestFactory.createSObject(new ServiceTerritory(
            OperatingHoursId       = operatingHours.Id,
            Name                   = 'São Paulo',
            SchedulingConstraintId = constraint.Id
        ), true);

        ServiceAppointment serviceAppointment = (ServiceAppointment) TestFactory.createSObject(new ServiceAppointment(
            ParentRecordId     = opportunity.Id,
            Oportunidade__c    = opportunity.Id,
            ServiceTerritoryId = serviceTerritory.Id
        ), true);
        

        ServiceResource serviceRes = (ServiceResource) TestFactory.createSObject(new ServiceResource(
            SchedulingConstraintId = constraint.Id
        ), true);

        ServiceTerritoryMember member = (ServiceTerritoryMember) TestFactory.createSOBject(new ServiceTerritoryMember(
            ServiceResourceId  = serviceRes.Id,
            ServiceTerritoryId = serviceTerritory.Id
        ), true);
    }
    
    @isTest
    static void assignServiceResourceToAppointmentVisitAssigneeTest(){
        ServiceAppointment serviceAppointment = [
            SELECT  Id
            FROM    ServiceAppointment
            LIMIT   1
        ];

        ServiceResource serviceRes = [
            SELECT  Id
            FROM    ServiceResource
            LIMIT   1
        ];
        
        Test.startTest();
        AssignedResource assignedRes = (AssignedResource) TestFactory.createSObject(new AssignedResource(
            ServiceResourceId    = serviceRes.Id,
            ServiceAppointmentId = serviceAppointment.Id
        ), true);
        Test.stopTest();

        serviceAppointment = [
            SELECT  Id, ResponsavelVisita__c
            FROM    ServiceAppointment
            LIMIT   1
        ];
        System.assertEquals(serviceRes.Id, serviceAppointment.ResponsavelVisita__c);
    }

    @isTest
    static void coverageOtherTriggerMethods(){
        /*ServiceAppointment serviceAppointment = [
            SELECT  Id
            FROM    ServiceAppointment
            LIMIT   1
        ];

        ServiceResource serviceRes = [
            SELECT  Id
            FROM    ServiceResource
            LIMIT   1
        ];
        
        AssignedResource assignedRes = (AssignedResource) TestFactory.createSObject(new AssignedResource(
            ServiceResourceId    = serviceRes.Id,
            ServiceAppointmentId = serviceAppointment.Id
        ), true);
        delete assignedRes;*/

        AssignedResourceTriggerHandler.disableTrigger();

        System.assert(!AssignedResourceTriggerHandler.isTriggerEnabled());
        
        AssignedResourceTriggerHandler.enableTrigger();
        System.assert(AssignedResourceTriggerHandler.isTriggerEnabled());
    }
}