force-app/main/default/objects/PricebookEntry/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Preco_Unitario__c.field-meta.xml
<CustomField>
    <fullName>Preco_Unitario__c</fullName>
    <label>Preço Unitário</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductTriggerTest.cls
@isTest
public class ProductTriggerTest {
  @TestSetup
  static void makeData() {
  }

  @isTest
  static void activateProductsTest() {
    Product2 product = (Product2) TestFactory.createSObject(
      new Product2(
        ExternalId__c = 'prod-trigger-1-' +
          String.valueOf(DateTime.now().getTime())
      ),
      true
    );

    product = [
      SELECT Id, IsActive
      FROM Product2
      WHERE Id = :product.Id
    ];
    System.assert(product.IsActive);
  }

  @isTest
  static void assignPricebookToProductTest() {
    Product2 product = (Product2) TestFactory.createSObject(
      new Product2(
        ExternalId__c = 'prod-trigger-2-' +
          String.valueOf(DateTime.now().getTime())
      ),
      true
    );

    List<PricebookEntry> entries = [
      SELECT Id, Product2Id, UnitPrice, IsActive, Pricebook2Id
      FROM PricebookEntry
    ];

    System.assertEquals(1, entries.size());

    PricebookEntry entry = entries[0];
    System.assert(entry.IsActive);
    System.assertEquals(product.Preco_Unitario__c, entry.UnitPrice);
    System.assertEquals(product.Id, entry.Product2Id);
    System.assertEquals(Test.getStandardPricebookId(), entry.Pricebook2Id);
  }

  @isTest
  static void coverageOtherTriggerMethods() {
    Product2 product = (Product2) TestFactory.createSObject(
      new Product2(
        ExternalId__c = 'prod-trigger-3-' +
          String.valueOf(DateTime.now().getTime())
      ),
      true
    );

    product.Name = 'Teste 2';
    update product;

    delete product;

    ProductTriggerHandler.disableTrigger();
    System.assert(!ProductTriggerHandler.isTriggerEnabled());

    ProductTriggerHandler.enableTrigger();
    System.assert(ProductTriggerHandler.isTriggerEnabled());
  }
}