force-app/main/default/objects/Opportunity/fields/PropostaAlterada__c.field-meta.xml
<CustomField>
    <fullName>PropostaAlterada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proposta Alterada?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PropostaGerada__c.field-meta.xml
<CustomField>
    <fullName>PropostaGerada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar se proposta foi gerada, a partir do botão &quot;Gerar Proposta&quot; na tela de Oportunidade</description>
    <label>Proposta foi gerada?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReadequacaoSolicitada__c.field-meta.xml
<CustomField>
    <fullName>ReadequacaoSolicitada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Readequação solicitada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/StatusAprovacaoDesconto__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacaoDesconto__c</fullName>
    <label>Status Aprovação de Desconto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciado</fullName>
                <default>true</default>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ValorTotalProposta__c.field-meta.xml
<CustomField>
    <fullName>ValorTotalProposta__c</fullName>
    <description
  >Campo que indica o valor total da proposta, incluindo o custo adicional somado ao valor da proposta.</description>
    <formula>IF(
    OR(
        AND(
            RecordType.DeveloperName = &quot;Solar&quot;,
            DATEVALUE(CreatedDate) &gt;= DATE(2025, 8, 12)
        ),
        RecordType.DeveloperName = &quot;Produtos&quot;
    ),
    CustoFinanceiroWeg__c +
    CustoAdicionalFixo__c +
    ValorInstalacao__c +
    Rede3750__c +
    Pontos__c +
    Acoplamento__c +
    BDI__c +
    ValorTotalProdutos__c +
    Direct__c + ClientTotalCost__c + 
    ValorAdicionalVendaFinal__c,
    IF(
        OR(
            RecordType.DeveloperName = &quot;EzeeConnect&quot;,
            RecordType.DeveloperName = &quot;EzeeConnect_Solled&quot;,
            RecordType.DeveloperName = &quot;BowE&quot;,
            RecordType.DeveloperName = &quot;Ultragaz&quot;,
            RecordType.DeveloperName = &quot;Simplifica&quot;,
            RecordType.DeveloperName = &quot;Nextron&quot;,
            RecordType.DeveloperName = &quot;Origo&quot;,
            RecordType.DeveloperName = &quot;Raizen&quot;,
            RecordType.DeveloperName = &quot;Plin&quot;
        ),
        FaturaDescontoFixo__c,
        ValorTotalProdutos__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >Campo que indica o valor total da proposta, incluindo o custo adicional somado ao valor da proposta.</inlineHelpText>
    <label>Valor Total da Proposta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/EzeeConnect.recordType-meta.xml
<RecordType>
    <fullName>EzeeConnect</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Ezee Connect</businessProcess>
    <label>Ezee Connect</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Solar</businessProcess>
    <label>Solar</label>
</RecordType>

force-app/main/default/classes/OpportunityPDFHelper.cls
/**
 * @description						 :
 * @author											 : Daniel Belini
 * @group												 :
 * @last modified on	 : 08-13-2025
 * @last modified by	 : Daniel Belini
 **/
public with sharing class OpportunityPDFHelper {
  public OpportunityPDFHelper() {
  }

  public static Boolean generatePDF(
    Opportunity opportunity,
    Opportunity oldOpportunity
  ) {
    if (oldOpportunity == null)
      return false;

    Boolean isEzeeOrSolar =
      opportunity.RecordTypeId ==
      Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        .get('EzeeConnect')
        .getRecordTypeId() ||
      opportunity.RecordTypeId ==
      Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        .get('Solar')
        .getRecordTypeId();

    if (
      (opportunity.ValorTotalProposta__c !=
      oldOpportunity.ValorTotalProposta__c) &&
      OpportunityUtils.isStatusProposalGenerated(opportunity)
    ) {
      return true;
    }

    if (isEzeeOrSolar && opportunity != null) {
      // Consider moving this side effect elsewhere if not expected here
      opportunity.PropostaAlterada__c = true;

      Boolean shouldGenerate =
        (OpportunityUtils.isStatusProposalElaboration(opportunity) ||
        OpportunityUtils.isStatusProposalSimulation(opportunity)) &&
        !OpportunityUtils.hasProposal(opportunity) ||
        (opportunity.StageName != oldOpportunity.StageName &&
        !opportunity.PropostaGerada__c) ||
        (opportunity.StageName == oldOpportunity.StageName &&
        opportunity.ReadequacaoSolicitada__c !=
        oldOpportunity.ReadequacaoSolicitada__c &&
        opportunity.ReadequacaoSolicitada__c) ||
        (oldOpportunity.PropostaGerada__c != opportunity.PropostaGerada__c &&
        opportunity.PropostaGerada__c &&
        opportunity.StatusAprovacaoDesconto__c !=
        oldOpportunity.StatusAprovacaoDesconto__c &&
        opportunity.StatusAprovacaoDesconto__c == 'Aprovado') ||
        (oldOpportunity.ValorTotalProposta__c !=
        opportunity.ValorTotalProposta__c);

      if (shouldGenerate) {
        return true;
      }

      // If only record type matches, still return true as before
      return true;
    }

    return false;
  }
}