force-app/main/default/objects/Opportunity/fields/TipoTelhadoEstrutura__c.field-meta.xml
<CustomField>
    <fullName>TipoTelhadoEstrutura__c</fullName>
    <description>Campo para definir o tipo do telhado ou estrutura de fixação.</description>
    <label>Tipo do telhado - Estrutura de fixação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ao Solo</fullName>
            </value>
            <value>
                <fullName>Cerâmico</fullName>
            </value>
            <value>
                <fullName>Carport</fullName>
            </value>
            <value>
                <fullName>Fibrocimento (Metálico)</fullName>
            </value>
            <value>
                <fullName>Fibrocimento (Madeira)</fullName>
            </value>
            <value>
                <fullName>Metálico</fullName>
            </value>
            <value>
                <fullName>Laje</fullName>
            </value>
            <value>
                <fullName>Zipado</fullName>
            </value>
            <value>
                <fullName>Shingle</fullName>
            </value>
            <value>
                <fullName>Car Port</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ViabilidadeDisponivel__c.field-meta.xml
<CustomField>
    <fullName>ViabilidadeDisponivel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Viabilidade disponível</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityController.cls
public without sharing class OpportunityController {
    @AuraEnabled
    public static void updateOpportunity(Id recordId, Decimal latitude, Decimal longitude, String telhado) {
        try {
            List<Opportunity> oppList = [SELECT Id, LocalizacaoFixa__Latitude__s, LocalizacaoFixa__Longitude__s, TipoTelhadoEstrutura__c FROM Opportunity WHERE Id = :recordId];
            List<Opportunity> oppListUpdt = new List<Opportunity>();

            if (oppList.isEmpty()) {
                throw new AuraHandledException('Oportunidade não encontrada para o ID fornecido, ID:' + recordId);
            }

            for(Opportunity opp : oppList){
            	opp.LocalizacaoFixa__Latitude__s = latitude;
            	opp.LocalizacaoFixa__Longitude__s = longitude;
                opp.TipoTelhadoEstrutura__c = telhado;
                opp.ViabilidadeDisponivel__c = false;
                oppListUpdt.add(opp);
            }
            
            update oppListUpdt;

        } catch (DmlException e) {
            throw new AuraHandledException('Erro ao atualizar a Oportunidade: ' + e.getMessage());
        }
    }
}