force-app/main/default/objects/Consultor__c/Consultor__c.object-meta.xml
<CustomObject>
    <label>Consultor</label>
    <nameField>
        <label>Nome do Consultor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultor__c/fields/Complemento__c.field-meta.xml
<CustomField>
    <fullName>Complemento__c</fullName>
    <description>Campo para definir Complemento do cliente.</description>
    <label>Complemento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/IdVirtualOffice2__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice2__c</fullName>
    <label>Id no Virtual Office</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <description>Id do cliente gerado no app Virtual Office (fora do Salesforce)</description>
    <externalId>true</externalId>
    <label>Id no Gerador de Oportunidades</label>
    <length>90</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/Login_no_virtual__c.field-meta.xml
<CustomField>
    <fullName>Login_no_virtual__c</fullName>
    <label>Login no virtual office</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integrador__mdt/Integrador__mdt.object-meta.xml
<CustomObject>
    <description>Metadado para armazenar informações de Endpoints, login, senha</description>
    <label>Integração</label>
    <pluralLabel>Integradores</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead/fields/ConsultorRegional__c.field-meta.xml
<CustomField>
    <fullName>ConsultorRegional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor regional</label>
    <referenceTo>Consultor__c</referenceTo>
    <relationshipLabel>Leads (Consultor regional)</relationshipLabel>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPFCNPJ__c.field-meta.xml
<CustomField>
    <fullName>CPFCNPJ__c</fullName>
    <label>CPF/CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DataNascimento__c.field-meta.xml
<CustomField>
    <fullName>DataNascimento__c</fullName>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ErrorIntegracaoVO__c.field-meta.xml
<CustomField>
    <fullName>ErrorIntegracaoVO__c</fullName>
    <label>Erro Integração VO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <label>Id no Virtual Office</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/StatusBodyIntegracaoVO__c.field-meta.xml
<CustomField>
    <fullName>StatusBodyIntegracaoVO__c</fullName>
    <label>Status Body Integração VO</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/StreetNumber__c.field-meta.xml
<CustomField>
    <fullName>StreetNumber__c</fullName>
    <label>Numero</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegracaoVOConsultorPreCadastro.cls
public with sharing class IntegracaoVOConsultorPreCadastro {
  @future(callout=true)
  public static void sendConsultor(Set<Id> triggerIds) {
    List<Lead> leadList = [
      SELECT
        Id,
        FirstName,
        LastName,
        Email,
        DataNascimento__c,
        CPFCNPJ__c,
        Street,
        StreetNumber__c,
        PostalCode,
        Complemento__c,
        ConsultorRegional__r.Login_no_virtual__c,
        ConsultorRegional__r.IdVirtualOffice2__c
      FROM Lead
      WHERE Id IN :triggerIds
    ];

    for (Lead lead : leadList) {
      ConsultorRequest corpoRequisicao = new ConsultorRequest();
      corpoRequisicao.IdLeadSalesForce = lead.Id;
      corpoRequisicao.NomeCompleto = lead.FirstName + ' ' + lead.LastName;
      corpoRequisicao.email = lead.Email;
      corpoRequisicao.DataNascimento = lead.DataNascimento__c == null
        ? '2000-01-01'
        : String.valueOf(lead.DataNascimento__c);
      corpoRequisicao.Documento = lead.CPFCNPJ__c;
      corpoRequisicao.LoginUsuarioPai = lead.ConsultorRegional__r.Login_no_virtual__c;
      corpoRequisicao.IdUsuarioPai = lead.ConsultorRegional__r != null
        ? Integer.valueOf(lead.ConsultorRegional__r.IdVirtualOffice2__c)
        : null;

      BPAddress bpAddress = new BPAddress();
      bpAddress.Rua = lead.street;
      bpAddress.Numero = lead.streetNumber__c;
      bpAddress.Cep = lead.postalCode;
      bpAddress.Complemento = lead.complemento__c;

      corpoRequisicao.Endereco = bpAddress;

      try {
        HttpResponse response = chamadaIntegracao(
          JSON.serialize(corpoRequisicao),
          'ConsultorVO'
        );
        Utils.createLog(
          'IntegracaoVOConsultorPreCadastro',
          'sendConsultor ' + lead.Id,
          response
        );

        if (response.getBody() != null && response.getBody() != '') {
          Map<String, Object> responseBody = (Map<String, Object>) JSON.deserializeUntyped(
            response.getBody()
          );
          Boolean success = Boolean.valueOf(responseBody.get('erro'));

          if (!success) {
            String IdVirtualOffice = String.valueOf(
              responseBody.get('idusuario')
            );
            lead.IdVirtualOffice__c = IdVirtualOffice;
          } else {
            String ErrorIntegracaoVO = String.valueOf(
              responseBody.get('retorno')
            );
            lead.ErrorIntegracaoVO__c = ErrorIntegracaoVO != null
              ? ErrorIntegracaoVO
              : 'Erro desconhecido na integração com Virtual Office';
          }

          lead.SucessoIntegracaoVO__c = !success;
          lead.StatusBodyIntegracaoVO__c =
            response.getStatusCode() +
            ' ' +
            response.getBody() +
            ' ' +
            response.getStatus();
        }
      } catch (Exception e) {
        Utils.createLog(
          'IntegracaoVOConsultorPreCadastro',
          'sendConsultor ' + lead.Id,
          e
        );

        lead.SucessoIntegracaoVO__c = false;
        lead.ErrorIntegracaoVO__c = 'Erro desconhecido na integração com Virtual Office';
        lead.StatusBodyIntegracaoVO__c =
          e.getMessage() +
          ' ' +
          e.getStackTraceString();
      }
    }

    LeadTriggerHandler.disableTrigger();
    update leadList;
    LeadTriggerHandler.enableTrigger();
  }

  private static HttpResponse chamadaIntegracao(
    String body,
    String endpointName
  ) {
    Integrador__mdt parametrosIntegracao = [
      SELECT Id, URL__c
      FROM Integrador__mdt
      WHERE DeveloperName = :endpointName
      LIMIT 1
    ];

    if (parametrosIntegracao == null) {
      throw new IllegalArgumentException(
        'Endpoint não encontrado para: ' + endpointName
      );
    }

    Http httpObj = new Http();
    HttpRequest request = new HttpRequest();

    request.setEndpoint(parametrosIntegracao.URL__c);
    request.setMethod('POST');
    request.setHeader('Content-Type', 'application/json');
    request.setBody(body);

    return Utils.callIntegrationVO(request);
  }

  public class ConsultorRequest {
    public Id IdLeadSalesForce;
    public String NomeCompleto;
    public String email;
    public String DataNascimento;
    public String Documento;
    public String LoginUsuarioPai;
    public Integer IdUsuarioPai;
    public BPAddress Endereco;
  }

  public class BPAddress {
    public String Rua;
    public String Numero;
    public String Cep;
    public String Complemento;
  }
}