force-app/main/default/objects/Consultor__c/Consultor__c.object-meta.xml
<CustomObject>
    <label>Consultor</label>
    <nameField>
        <label>Nome do Consultor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultor__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/Celular__c.field-meta.xml
<CustomField>
    <fullName>Celular__c</fullName>
    <label>Celular</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/Comissao__c.field-meta.xml
<CustomField>
    <fullName>Comissao__c</fullName>
    <label>Comissão</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Campo para definir E-mail do cliente.</description>
    <inlineHelpText>abcd@gmail.com</inlineHelpText>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <label>Fax</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/Observacoes__c.field-meta.xml
<CustomField>
    <fullName>Observacoes__c</fullName>
    <label>Observações</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/SeCPFouCNPJ__c.field-meta.xml
<CustomField>
    <fullName>SeCPFouCNPJ__c</fullName>
    <description>Campo para pegar o valor de CPF ou CNPJ.</description>
    <formula>IF( CNPJ__c =null,SUBSTITUTE(SUBSTITUTE(CPF__c, &quot;-&quot;, null),&quot;.&quot;, null),
SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(CNPJ__c , &quot;-&quot;, null),&quot;.&quot;, null), &quot;/&quot;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SeCPFouCNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/StatusBodyIntegracaoSAP__c.field-meta.xml
<CustomField>
    <fullName>StatusBodyIntegracaoSAP__c</fullName>
    <label>Status Body Integração SAP</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/SucessoIntegracaoSAP__c.field-meta.xml
<CustomField>
    <fullName>SucessoIntegracaoSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sucesso Integração SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/Telefone__c.field-meta.xml
<CustomField>
    <fullName>Telefone__c</fullName>
    <description>Campo para definir Telefone do cliente.</description>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Consultor__c/recordTypes/Consultor.recordType-meta.xml
<RecordType>
    <fullName>Consultor</fullName>
    <active>true</active>
    <label>Consultor</label>
</RecordType>

force-app/main/default/classes/IntegracaoSAPRepresentante.cls
/**
 * @description       :
 * @author            : Daniel Belini
 * @group             :
 * @last modified on  : 03-18-2026
 * @last modified by  : Daniel Belini
 * @test              : IntegracaoSAPTest
 **/
public without sharing class IntegracaoSAPRepresentante implements Queueable, Database.AllowsCallouts {
  private final Set<Id> recordIds;

  public IntegracaoSAPRepresentante(Set<Id> recordIds) {
    this.recordIds = recordIds;
  }

  public void execute(QueueableContext ctx) {
    List<Consultor__c> consultorList = [
      SELECT
        Id,
        Name,
        Observacoes__c,
        Comissao__c,
        Ativo__c,
        Telefone__c,
        Celular__c,
        Fax__c,
        Email__c,
        SeCPFOuCNPJ__c
      FROM Consultor__c
      WHERE Id IN :recordIds
    ];

    SAPIntegrationService.EndpointConfig sapConfig = SAPIntegrationService.resolveConfig(
      'RepresentanteSAP'
    );

    for (Consultor__c consultor : consultorList) {
      RepresentanteRequest corpoRequisicao = new RepresentanteRequest();
      corpoRequisicao.U_Alfa_IdIntegracao = consultor.SeCPFOuCNPJ__c;
      corpoRequisicao.SalesEmployeeName = consultor.Name;
      corpoRequisicao.Remarks = consultor.Observacoes__c;
      corpoRequisicao.CommissionForSalesEmployee = consultor.Comissao__c;
      corpoRequisicao.CommissionGroup = null;
      corpoRequisicao.Active = consultor.Ativo__c ? 'tYES' : 'tNO';
      corpoRequisicao.Telephone = consultor.Telefone__c;
      corpoRequisicao.Mobile = consultor.Celular__c;
      corpoRequisicao.Fax = consultor.Fax__c;
      corpoRequisicao.Email = consultor.Email__c;

      try {
        HttpResponse response = SAPIntegrationService.post(
          JSON.serialize(corpoRequisicao),
          sapConfig,
          null
        );
        Utils.createLog(
          'IntegracaoSAPRepresentante',
          'sendRepresentante ' + consultor.Id,
          response
        );

        if (response.getBody() != null && response.getBody() != '') {
          Map<String, Object> responseBody = (Map<String, Object>) JSON.deserializeUntyped(
            response.getBody()
          );
          Integer statusCode = Integer.valueOf(responseBody.get('codigoHttp'));
          consultor.SucessoIntegracaoSAP__c = SAPIntegrationService.isSuccess(
            statusCode
          );
          consultor.StatusBodyIntegracaoSAP__c =
            statusCode +
            ' ' +
            response.getBody() +
            ' ' +
            response.getStatus();
        }
      } catch (Exception e) {
        Utils.createLog(
          'IntegracaoSAPRepresentante',
          'sendRepresentante ' + consultor.Id,
          e
        );
        consultor.SucessoIntegracaoSAP__c = false;
        consultor.StatusBodyIntegracaoSAP__c =
          e.getMessage() +
          ' ' +
          e.getStackTraceString();
      }
    }

    ConsultorTriggerHandler.disableTrigger();
    try {
      update consultorList;
    } finally {
      ConsultorTriggerHandler.enableTrigger();
    }
  }

  public class RepresentanteRequest {
    public String U_Alfa_IdIntegracao;
    public String SalesEmployeeName;
    public String Remarks;
    public Double CommissionForSalesEmployee;
    public Integer CommissionGroup;
    public String Active;
    public String Telephone;
    public String Mobile;
    public String Fax;
    public String Email;
  }
}