force-app/main/default/objects/Consultor__c/Consultor__c.object-meta.xml
<CustomObject>
    <label>Consultor</label>
    <nameField>
        <label>Nome do Consultor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultor__c/fields/NumeroIdentificacao__c.field-meta.xml
<CustomField>
    <fullName>NumeroIdentificacao__c</fullName>
    <externalId>true</externalId>
    <label>Numero de Identificação</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/SeCPFouCNPJ__c.field-meta.xml
<CustomField>
    <fullName>SeCPFouCNPJ__c</fullName>
    <description>Campo para pegar o valor de CPF ou CNPJ.</description>
    <formula>IF( CNPJ__c =null,SUBSTITUTE(SUBSTITUTE(CPF__c, &quot;-&quot;, null),&quot;.&quot;, null),
SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(CNPJ__c , &quot;-&quot;, null),&quot;.&quot;, null), &quot;/&quot;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SeCPFouCNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/Telefone__c.field-meta.xml
<CustomField>
    <fullName>Telefone__c</fullName>
    <description>Campo para definir Telefone do cliente.</description>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Consultor__c/fields/Telefone_Formatado__c.field-meta.xml
<CustomField>
    <fullName>Telefone_Formatado__c</fullName>
    <formula>IF(
    
    LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 13,
    LEFT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 4) &amp; MID(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 6, LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) - 5),
    
   IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 12,
   SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;),

   IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 11,
   LEFT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(&quot;55&quot; + Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 4) &amp; MID(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(&quot;55&quot; + Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 6, LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(&quot;55&quot; + Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) - 5),
    IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 11,
    &quot;55&quot; + SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;),
    IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 10,
    &quot;55&quot; + SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;),
    IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Telefone__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) &lt; 11, &quot;Número faltando informação: &quot; + Telefone__c, Telefone__c))
)))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Telefone Formatado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consultor__c/recordTypes/Consultor.recordType-meta.xml
<RecordType>
    <fullName>Consultor</fullName>
    <active>true</active>
    <label>Consultor</label>
</RecordType>

force-app/main/default/objects/MessagingEndUser/fields/Consultor__c.field-meta.xml
<CustomField>
    <fullName>Consultor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor</label>
    <referenceTo>Consultor__c</referenceTo>
    <relationshipLabel>Usuários do Messaging</relationshipLabel>
    <relationshipName>Usuarios_do_Messaging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MessagingEndUser/fields/Telefone_Formatado__c.field-meta.xml
<CustomField>
    <fullName>Telefone_Formatado__c</fullName>
    <formula>IF(
    
    LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 13,
    LEFT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 4) &amp; MID(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 6, LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) - 5),
    
   IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 12,
   SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;),

   IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 11,
   LEFT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(&quot;55&quot; + MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 4) &amp; MID(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(&quot;55&quot; + MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;), 6, LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(&quot;55&quot; + MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) - 5),
    IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 11,
    &quot;55&quot; + SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;),
    IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) = 10,
    &quot;55&quot; + SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;),
    IF(LEN(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MessagingPlatformKey, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;),&quot;+&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;.&quot;, &quot;&quot;)) &lt; 11, &quot;Número faltando informação: &quot; + MessagingPlatformKey, MessagingPlatformKey))
)))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Telefone Formatado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConsultorBO.cls
public with sharing class ConsultorBO {
  public static Id consultorRT = Schema.SObjectType.Consultor__c.getRecordTypeInfosByDeveloperName()
    .get('Consultor')
    .getRecordTypeId();

  public static void assignCPFCNPJToIdentificationNumber(
    List<Consultor__c> newRecordList
  ) {
    for (Consultor__c consultor : newRecordList) {
      if (consultor.NumeroIdentificacao__c == null) {
        consultor.NumeroIdentificacao__c = consultor.SeCPFouCNPJ__c;
      }
    }
  }

  public static void sendFornecedorRepresentanteRecordToSAP(
    List<Consultor__c> newRecordList
  ) {
    // Representante (SAP) = Consultor = Vendedor
    // Fornecedor (SAP) = Franqueado =  Integrador (DESCONTINUADA)

    User runningUser = [
      SELECT Id, Name, Profile.Name
      FROM User
      WHERE Id = :UserInfo.getUserId()
    ];

    if (!runningUser.Name.equalsIgnoreCase('Integrador SAP')) {
      Set<Id> representanteIds = new Set<Id>();
      Set<Id> fornecedorIds = new Set<Id>();
      for (Consultor__c consultor : newRecordList) {
        if (consultor.RecordTypeID == consultorRT) {
          representanteIds.add(consultor.Id);
          fornecedorIds.add(consultor.Id);
        }
      }

      if (!representanteIds.isEmpty()) {
        IntegracaoSAPRepresentante.sendRepresentante(representanteIds);
      }

      if (!fornecedorIds.isEmpty()) {
        IntegracaoSAPFornecedor.sendFornecedor(fornecedorIds);
      }
    }
  }

  public static void createMessagingUser(
    List<Consultor__c> consultores,
    Map<Id, Consultor__c> oldMap
  ) {
    try {
      List<MessagingEndUser> messagingUsers = new List<MessagingEndUser>();
      Map<String, Consultor__c> consultantByPhone = new Map<String, Consultor__c>();
      Id channelPartnerId = MessagingEndUserService.resolveChannelId(
        '+55 11 4003-8852'
      );

      for (Consultor__c consultant : consultores) {
        if (String.isBlank(consultant.Telefone__c)) {
          continue;
        }

        Consultor__c oldConsultant = oldMap.get(consultant.Id);

        if (
          oldConsultant != null &&
          (oldConsultant.Telefone__c == consultant.Telefone__c)
        )
          continue;

        consultantByPhone.put(consultant.Telefone_Formatado__c, consultant);
      }

      Map<String, MessagingEndUser> endUserByKey = MessagingEndUserService.findAvailableByPhone(
        consultantByPhone.keySet(),
        'Consultor__c',
        null
      );

      for (Consultor__c consultant : consultantByPhone.values()) {
        MessagingEndUser endUser = endUserByKey.get(
          consultant.Telefone_Formatado__c
        );

        if (endUser == null) {
          endUser = MessagingEndUserService.buildNewEndUser(
            consultant.Telefone_Formatado__c,
            consultant.Name,
            channelPartnerId
          );
          endUser.Consultor__c = consultant.Id;
        } else {
          endUser.Consultor__c = consultant.Id;
        }
        messagingUsers.add(endUser);
      }

      MessagingEndUserService.save(messagingUsers, true);
    } catch (Exception ex) {
      System.debug('##Erro ao criar messaging user: ' + ex.getMessage());
      System.debug('##Stack: ' + ex.getStackTraceString());
      System.debug('##Line: ' + ex.getLineNumber());
    }
  }
}