force-app/main/default/objects/Consultor__c/Consultor__c.object-meta.xml
<CustomObject>
    <label>Consultor</label>
    <nameField>
        <label>Nome do Consultor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultor__c/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <description>Id do cliente gerado no app Virtual Office (fora do Salesforce)</description>
    <externalId>true</externalId>
    <label>Id no Gerador de Oportunidades</label>
    <length>90</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/ConsultorRegional__c.field-meta.xml
<CustomField>
    <fullName>ConsultorRegional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor regional</label>
    <referenceTo>Consultor__c</referenceTo>
    <relationshipLabel>Leads (Consultor regional)</relationshipLabel>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IdVirtualOffice__c.field-meta.xml
<CustomField>
    <fullName>IdVirtualOffice__c</fullName>
    <label>Id no Virtual Office</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lab065_IntegracaoDistribuicaoLead__c.field-meta.xml
<CustomField>
    <fullName>Lab065_IntegracaoDistribuicaoLead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Integração Distribuição Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeadIntegrationBatch.cls
/**
 * @description						 :
 * @author											 : Daniel Belini
 * @group												 :
 * @last modified on	 : 10-16-2025
 * @last modified by	 : Daniel Belini
 **/
global class LeadIntegrationBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
  global Database.QueryLocator start(Database.BatchableContext BC) {
    // Query para selecionar os Leads desejados conforme filtros fornecidos
    String query =
      'SELECT Id, Status, Lab065_IntegracaoDistribuicaoLead__c, CreatedDate, LeadSource, RecordType.Name ' +
      'FROM Lead ' +
      'WHERE Lab065_IntegracaoDistribuicaoLead__c = false ' +
      'AND Status = \'Distribuído\' ' +
      'AND RecordType.Name = \'Qualificação de Clientes\' AND ConsultorRegional__r.IdVirtualOffice__c != null ' +
      ' ORDER BY CreatedDate DESC LIMIT 10 ';
    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext BC, List<SObject> scope) {
    List<LeadIntegrationService.LeadInput> inputs = new List<LeadIntegrationService.LeadInput>();
    for (SObject s : scope) {
      Lead l = (Lead) s;
      LeadIntegrationService.LeadInput input = new LeadIntegrationService.LeadInput();
      input.leadId = l.Id;
      inputs.add(input);
    }
    LeadIntegrationService.sendLeadsToExternalApp(inputs);
  }

  global void finish(Database.BatchableContext BC) {
    // Lógica opcional pós-processamento
  }
}