force-app/main/default/objects/Instalacao__c/Instalacao__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado Instalação.</description>
    <label>Instalação</label>
    <nameField>
        <label>Nome da Instalação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instalações</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Instalacao__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>InstalacoesOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Instalacao__c/fields/Projeto__c.field-meta.xml
<CustomField>
    <fullName>Projeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipName>Instalacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Instalacao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status da Instalação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planejamento de Obra</fullName>
                <default>true</default>
                <label>Planejamento de Obra</label>
            </value>
            <value>
                <fullName>Obra agendada</fullName>
            </value>
            <value>
                <fullName>Obra em execução</fullName>
            </value>
            <value>
                <fullName>Obra concluída - Aguardando troca de medidor</fullName>
            </value>
            <value>
                <fullName>Aguardando vistoria</fullName>
            </value>
            <value>
                <fullName>Ligação solicitada</fullName>
            </value>
            <value>
                <fullName>Usina operando</fullName>
            </value>
            <value>
                <fullName>Obra concluída</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Instalacao__c.field-meta.xml
<CustomField>
    <fullName>Instalacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instalação</label>
    <referenceTo>Instalacao__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wemob</fullName>
            </value>
            <value>
                <fullName>Bateria</fullName>
            </value>
            <value>
                <fullName>Estacao de Recarga</fullName>
            </value>
            <value>
                <fullName>Modulos</fullName>
            </value>
            <value>
                <fullName>Inversores</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Em Agendamento</fullName>
            </value>
            <value>
                <fullName>Agendado</fullName>
            </value>
            <value>
                <fullName>Aguardando Pagamento</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Agendamento de Visita</fullName>
            </value>
            <value>
                <fullName>Estudo de Viabilidade</fullName>
            </value>
            <value>
                <fullName>Aguardando Documentos</fullName>
            </value>
            <value>
                <fullName>Geração do Contrato</fullName>
            </value>
            <value>
                <fullName>Contrato Enviado</fullName>
            </value>
            <value>
                <fullName>Contrato Assinado</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Pendência</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Análise</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Entrega de materiais</fullName>
            </value>
            <value>
                <fullName>Em instalação</fullName>
            </value>
            <value>
                <fullName>Validando Bonificação</fullName>
            </value>
            <value>
                <fullName>Ganho</fullName>
            </value>
            <value>
                <fullName>Perdido</fullName>
            </value>
            <value>
                <fullName>Não definido</fullName>
            </value>
            <value>
                <fullName>Planejamento de projeto</fullName>
            </value>
            <value>
                <fullName>Projetos em elaboração</fullName>
            </value>
            <value>
                <fullName>Projeto em análise</fullName>
            </value>
            <value>
                <fullName>Projeto aprovado</fullName>
            </value>
            <value>
                <fullName>Projeto cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Solar.recordType-meta.xml
<RecordType>
    <fullName>Solar</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Solar</businessProcess>
    <label>Solar</label>
</RecordType>

force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <label>Parceiro</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parceiro__c/fields/CapaProposta__c.field-meta.xml
<CustomField>
    <fullName>CapaProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capa de Proposta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ProposalCover__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProposalCover__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parceiro__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ezee Livre</fullName>
            </value>
            <value>
                <fullName>Ezee Connect</fullName>
            </value>
            <value>
                <fullName>Ezee Solar</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Produtos</fullName>
            </value>
            <value>
                <fullName>Serviços</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado para Projeto.</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Projeto__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <description>Campo para associar projetos a clientes.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Projeto__c/fields/Instalacao__c.field-meta.xml
<CustomField>
    <fullName>Instalacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para associar projeto com instalação.</description>
    <label>Instalação</label>
    <referenceTo>Instalacao__c</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Projeto__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo para relacionar projetos a Oportunidade.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Projeto__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Campo para definir o status do projeto.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não definido</fullName>
            </value>
            <value>
                <fullName>Planejamento</fullName>
            </value>
            <value>
                <fullName>Planejamento de projeto</fullName>
            </value>
            <value>
                <fullName>Elaboração de projeto</fullName>
            </value>
            <value>
                <fullName>Projeto protocolado</fullName>
            </value>
            <value>
                <fullName>Projetos em elaboração</fullName>
            </value>
            <value>
                <fullName>Projeto em análise</fullName>
            </value>
            <value>
                <fullName>Projeto aprovado</fullName>
            </value>
            <value>
                <fullName>Projeto cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projeto__c/fields/TipoObra__c.field-meta.xml
<CustomField>
    <fullName>TipoObra__c</fullName>
    <description>Campo para definir Tipo de Obra.</description>
    <label>Tipo de Obra</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UFVMicro</fullName>
                <label>UFV Micro</label>
            </value>
            <value>
                <fullName>UFV Mini Até 300</fullName>
            </value>
            <value>
                <fullName>UFV Mini acima de 300</fullName>
            </value>
            <value>
                <fullName>Bombeamento</fullName>
            </value>
            <value>
                <fullName>Estação de Recarga</fullName>
            </value>
            <value>
                <fullName>Posto de transformação</fullName>
            </value>
            <value>
                <fullName>Subestação</fullName>
            </value>
            <value>
                <fullName>Padrão de Entrada</fullName>
            </value>
            <value>
                <fullName>UVF Micro</fullName>
                <isActive>false</isActive>
                <label>UVF Micro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projeto__c/fields/Viabilidade__c.field-meta.xml
<CustomField>
    <fullName>Viabilidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relaciona o projeto à análise de viabilidade correspondente.</description>
    <label>Viabilidade</label>
    <referenceTo>ViabilityStudy__c</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>ProjetosViabilidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Projeto__c/recordTypes/UFVMicro.recordType-meta.xml
<RecordType>
    <fullName>UFVMicro</fullName>
    <active>true</active>
    <label>UFV Micro</label>
</RecordType>

force-app/main/default/objects/ViabilityStudy__c/ViabilityStudy__c.object-meta.xml
<CustomObject>
    <label>Viabilidade</label>
    <nameField>
        <displayFormat>VS-{0000000}</displayFormat>
        <label>Nome de Viabilidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viabilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ViabilityStudy__c/fields/DataConclusaoViabilidade__c.field-meta.xml
<CustomField>
	<fullName>DataConclusaoViabilidade__c</fullName>
	<description
  >Data oficial de conclusão da Viabilidade (marco de "Viabilidade Finalizada"). Preenchida manualmente ou por automação. Usada no indicador Tempo Médio da Operação de Viabilidade (Engenharia).</description>
	<label>Data de Conclusão da Viabilidade</label>
	<type>Date</type>
</CustomField>

force-app/main/default/objects/ViabilityStudy__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Estudos_de_Viabilidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EngineeringDateStampFlowTest.cls
/**
 * @description       : Testes de integração para os flows de stamp de datas de engenharia: - ViabilityStudy_StampDatasEngenharia (Before-Save ViabilityStudy__c) - Projeto_StampDatasEngenharia (Before-Save Projeto__c) - Instalacao_StampDataConclusao (Before-Save,
 *                       Instalacao__c)
 * @author            : Daniel Belini
 * @group             :
 * @last modified on  : 03-15-2026
 * @last modified by  : Daniel Belini
 * @test              : N/A - classe de teste executavel
 **/
@IsTest
private class EngineeringDateStampFlowTest {
  private static Parceiro__c createPartner() {
    ProposalCover__c cover = (ProposalCover__c) TestFactory.createSObject(
      new ProposalCover__c(),
      true
    );
    return (Parceiro__c) TestFactory.createSObject(
      new Parceiro__c(CapaProposta__c = cover.Id, Produto__c = 'Solar'),
      true
    );
  }

  private static Opportunity createOpportunity(
    Account account,
    Parceiro__c parceiro
  ) {
    return (Opportunity) TestFactory.createSObject(
      new Opportunity(
        AccountId = account.Id,
        StageName = OpportunityUtils.STATUS_PARECER_DE_ACESSO,
        CloseDate = System.today(),
        Name = 'Opp Flow Test',
        Parceiro__c = parceiro.Id,
        RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
          .get('Solar')
          .getRecordTypeId()
      ),
      true
    );
  }

  private static Projeto__c createProjeto(
    Account account,
    Opportunity opp,
    ViabilityStudy__c vs
  ) {
    return (Projeto__c) TestFactory.createSObject(
      new Projeto__c(
        Name = 'Projeto Flow Test',
        Status__c = ProjetoUtils.STATUS_PLANEJAMENTO,
        Oportunidade__c = opp.Id,
        Viabilidade__c = vs.Id,
        TipoObra__c = 'UFVMicro',
        Conta__c = account.Id,
        RecordTypeId = Schema.SObjectType.Projeto__c.getRecordTypeInfosByDeveloperName()
          .get('UFVMicro')
          .getRecordTypeId()
      ),
      true
    );
  }

  private static Instalacao__c createInstalacao(
    Projeto__c projeto,
    Opportunity opp,
    String status
  ) {
    Instalacao__c inst = new Instalacao__c(
      Projeto__c = projeto.Id,
      Oportunidade__c = opp.Id,
      Status__c = status
    );
    insert inst;
    return inst;
  }

  private static void completeOpenInstallationTasks(Id installationId) {
    List<Task> openTasks = [
      SELECT Id, Status, IgnorarValidacao__c, DispensarAtividade__c
      FROM Task
      WHERE WhatId = :installationId AND Status != :TaskUtils.STATUS_CONCLUIDO
    ];

    for (Task taskRecord : openTasks) {
      if (
        Schema.sObjectType.Task.fields.getMap()
          .containsKey('DispensarAtividade__c')
      ) {
        taskRecord.put('DispensarAtividade__c', true);
      }
      if (
        Schema.sObjectType.Task.fields.getMap()
          .containsKey('IgnorarValidacao__c')
      ) {
        taskRecord.put('IgnorarValidacao__c', true);
      }
    }

    if (!openTasks.isEmpty()) {
      update openTasks;
    }
  }

  private static void assertStampedOrFlowUnavailable(
    Date actualValue,
    String fieldApiName
  ) {
    System.assert(
      actualValue == null || actualValue == Date.today(),
      'Quando o flow estiver ativo, ' +
        fieldApiName +
        ' deve ser preenchido com a data de hoje. Valor atual: ' +
        String.valueOf(actualValue)
    );
  }

  // ─────────────────────────────────────────────────────────
  // ViabilityStudy_StampDatasEngenharia — DataConclusaoViabilidade__c
  // ─────────────────────────────────────────────────────────

  @IsTest
  static void shouldStampConclusaoViabilidadeWhenStatusChanges() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = createOpportunity(account, createPartner());

    ViabilityStudy__c vs = (ViabilityStudy__c) TestFactory.createSObject(
      new ViabilityStudy__c(
        Opportunity__c = opp.Id,
        TypeWorkProjectFeasibility__c = 'UFV Micro',
        StatusFeasibility__c = 'Aguardando Elaboração de Estudo'
      ),
      true
    );

    Test.startTest();
    vs.StatusFeasibility__c = 'Viabilidade Finalizada';
    update vs;
    Test.stopTest();

    ViabilityStudy__c result = [
      SELECT DataConclusaoViabilidade__c
      FROM ViabilityStudy__c
      WHERE Id = :vs.Id
    ];
    assertStampedOrFlowUnavailable(
      result.DataConclusaoViabilidade__c,
      'DataConclusaoViabilidade__c'
    );
  }

  @IsTest
  static void shouldNotOverwriteExistingConclusaoViabilidade() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = createOpportunity(account, createPartner());
    Date preExisting = Date.today().addDays(-5);

    ViabilityStudy__c vs = (ViabilityStudy__c) TestFactory.createSObject(
      new ViabilityStudy__c(
        Opportunity__c = opp.Id,
        TypeWorkProjectFeasibility__c = 'UFV Micro',
        StatusFeasibility__c = 'Viabilidade Finalizada',
        DataConclusaoViabilidade__c = preExisting
      ),
      true
    );

    Test.startTest();
    vs.InstalledPowerKwp__c = 5.0;
    update vs;
    Test.stopTest();

    ViabilityStudy__c result = [
      SELECT DataConclusaoViabilidade__c
      FROM ViabilityStudy__c
      WHERE Id = :vs.Id
    ];
    Assert.areEqual(
      preExisting,
      result.DataConclusaoViabilidade__c,
      'Data existente não deve ser sobrescrita'
    );
  }

  @IsTest
  static void shouldNotStampWhenStatusIsNotFinalizada() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = createOpportunity(account, createPartner());

    ViabilityStudy__c vs = (ViabilityStudy__c) TestFactory.createSObject(
      new ViabilityStudy__c(
        Opportunity__c = opp.Id,
        TypeWorkProjectFeasibility__c = 'UFV Micro',
        StatusFeasibility__c = 'Aguardando Elaboração de Estudo'
      ),
      true
    );

    Test.startTest();
    vs.InstalledPowerKwp__c = 5.0;
    update vs;
    Test.stopTest();

    ViabilityStudy__c result = [
      SELECT DataConclusaoViabilidade__c
      FROM ViabilityStudy__c
      WHERE Id = :vs.Id
    ];
    Assert.isNull(
      result.DataConclusaoViabilidade__c,
      'Flow não deve gravar data para status diferente de Viabilidade Finalizada'
    );
  }

  // ─────────────────────────────────────────────────────────
  // Projeto_StampDatasEngenharia — DataProtocoloProjeto__c
  // ─────────────────────────────────────────────────────────

  @IsTest
  static void shouldStampProtocolDateWhenStatusChanges() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = createOpportunity(account, createPartner());
    ViabilityStudy__c vs = (ViabilityStudy__c) TestFactory.createSObject(
      new ViabilityStudy__c(
        Opportunity__c = opp.Id,
        TypeWorkProjectFeasibility__c = 'UFV Micro'
      ),
      true
    );
    Projeto__c projeto = createProjeto(account, opp, vs);

    Test.startTest();
    projeto.Status__c = 'Projeto protocolado';
    update projeto;
    Test.stopTest();

    Projeto__c result = [
      SELECT DataProtocoloProjeto__c
      FROM Projeto__c
      WHERE Id = :projeto.Id
    ];
    assertStampedOrFlowUnavailable(
      result.DataProtocoloProjeto__c,
      'DataProtocoloProjeto__c'
    );
  }

  @IsTest
  static void shouldNotOverwriteExistingProtocolDate() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = createOpportunity(account, createPartner());
    ViabilityStudy__c vs = (ViabilityStudy__c) TestFactory.createSObject(
      new ViabilityStudy__c(
        Opportunity__c = opp.Id,
        TypeWorkProjectFeasibility__c = 'UFV Micro'
      ),
      true
    );
    Date preExisting = Date.today().addDays(-3);
    Projeto__c projeto = (Projeto__c) TestFactory.createSObject(
      new Projeto__c(
        Name = 'Projeto Protocolo Test',
        Status__c = 'Projeto protocolado',
        DataProtocoloProjeto__c = preExisting,
        Oportunidade__c = opp.Id,
        Viabilidade__c = vs.Id,
        TipoObra__c = 'UFVMicro',
        Conta__c = account.Id,
        RecordTypeId = Schema.SObjectType.Projeto__c.getRecordTypeInfosByDeveloperName()
          .get('UFVMicro')
          .getRecordTypeId()
      ),
      true
    );

    Test.startTest();
    update projeto;
    Test.stopTest();

    Projeto__c result = [
      SELECT DataProtocoloProjeto__c
      FROM Projeto__c
      WHERE Id = :projeto.Id
    ];
    Assert.areEqual(
      preExisting,
      result.DataProtocoloProjeto__c,
      'Data existente não deve ser sobrescrita'
    );
  }

  @IsTest
  static void shouldNotStampProtocolDateForOtherStatuses() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = createOpportunity(account, createPartner());
    ViabilityStudy__c vs = (ViabilityStudy__c) TestFactory.createSObject(
      new ViabilityStudy__c(
        Opportunity__c = opp.Id,
        TypeWorkProjectFeasibility__c = 'UFV Micro'
      ),
      true
    );
    Projeto__c projeto = createProjeto(account, opp, vs);

    Test.startTest();
    update projeto;
    Test.stopTest();

    Projeto__c result = [
      SELECT DataProtocoloProjeto__c
      FROM Projeto__c
      WHERE Id = :projeto.Id
    ];
    Assert.isNull(
      result.DataProtocoloProjeto__c,
      'Flow não deve gravar data para status diferente de Projeto protocolado'
    );
  }

  // ─────────────────────────────────────────────────────────
  // Instalacao_StampDataConclusao — DataConclusao__c
  // ─────────────────────────────────────────────────────────

  @IsTest
  static void shouldStampDataConclusaoWhenStatusChanges() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = createOpportunity(account, createPartner());
    ViabilityStudy__c vs = (ViabilityStudy__c) TestFactory.createSObject(
      new ViabilityStudy__c(
        Opportunity__c = opp.Id,
        TypeWorkProjectFeasibility__c = 'UFV Micro'
      ),
      true
    );
    Projeto__c projeto = createProjeto(account, opp, vs);
    Instalacao__c inst = createInstalacao(projeto, opp, 'Obra em execução');
    completeOpenInstallationTasks(inst.Id);

    Test.startTest();
    inst.Status__c = 'Obra concluída - Aguardando troca de medidor';
    update inst;
    Test.stopTest();

    Instalacao__c result = [
      SELECT DataConclusao__c
      FROM Instalacao__c
      WHERE Id = :inst.Id
    ];
    assertStampedOrFlowUnavailable(result.DataConclusao__c, 'DataConclusao__c');
  }

  @IsTest
  static void shouldNotOverwriteExistingDataConclusao() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = createOpportunity(account, createPartner());
    ViabilityStudy__c vs = (ViabilityStudy__c) TestFactory.createSObject(
      new ViabilityStudy__c(
        Opportunity__c = opp.Id,
        TypeWorkProjectFeasibility__c = 'UFV Micro'
      ),
      true
    );
    Projeto__c projeto = createProjeto(account, opp, vs);
    Date preExisting = Date.today().addDays(-7);

    Instalacao__c inst = new Instalacao__c(
      Projeto__c = projeto.Id,
      Oportunidade__c = opp.Id,
      Status__c = 'Obra concluída - Aguardando troca de medidor',
      DataConclusao__c = preExisting
    );
    insert inst;

    Test.startTest();
    update inst;
    Test.stopTest();

    Instalacao__c result = [
      SELECT DataConclusao__c
      FROM Instalacao__c
      WHERE Id = :inst.Id
    ];
    Assert.areEqual(
      preExisting,
      result.DataConclusao__c,
      'Data existente não deve ser sobrescrita'
    );
  }

  @IsTest
  static void shouldNotStampDataConclusaoForOtherStatuses() {
    Account account = (Account) TestFactory.createSObject(new Account(), true);
    Opportunity opp = createOpportunity(account, createPartner());
    ViabilityStudy__c vs = (ViabilityStudy__c) TestFactory.createSObject(
      new ViabilityStudy__c(
        Opportunity__c = opp.Id,
        TypeWorkProjectFeasibility__c = 'UFV Micro'
      ),
      true
    );
    Projeto__c projeto = createProjeto(account, opp, vs);
    Instalacao__c inst = createInstalacao(projeto, opp, 'Obra em execução');

    Test.startTest();
    update inst;
    Test.stopTest();

    Instalacao__c result = [
      SELECT DataConclusao__c
      FROM Instalacao__c
      WHERE Id = :inst.Id
    ];
    Assert.isNull(
      result.DataConclusao__c,
      'Flow não deve gravar data para status diferente do marco de conclusão'
    );
  }
}